import KIP126.Def.StableHomotopy.Cohomology.Coaction.Unit.Data
import KIP126.Def.StableHomotopy.Context.Proofs

/-! The coefficient homology of the sphere is generated by its actual
unit image. These results require neither a ring structure nor Künneth. -/

namespace KIP126.StableHomotopy.Cohomology

noncomputable section

open CategoryTheory MonoidalCategory KIP126.Classical.Adams

universe u v

set_option backward.isDefEq.respectTransparency false

variable {C : Type u} [StableHomotopyCategory.{u, v} C]
  (H : Mod2EilenbergMacLane (C := C))

/-- On the sphere the Adams unit is the specified coefficient unit,
after the actual tensor unitor. -/
theorem adamsUnit_sphere_unitor :
    adamsUnit H.unit (SphereSpectrum : C) ≫ (ρ_ H.HF2).hom = H.unit := by
  simp only [adamsUnit, Category.assoc, rightUnitor_naturality,
    ← unitors_equal, Iso.inv_hom_id_assoc]

/-- Every sphere coefficient class is the image of a genuine sphere
homotopy class under the unit. At degree zero this uses `π₀H = F₂`;
all other degrees vanish by the Eilenberg--Mac Lane property. -/
theorem mod2SphereHomology_unit_surjective (n : ℤ) :
    Function.Surjective (inducedMap (adamsUnit H.unit (SphereSpectrum : C)) n) := by
  intro x
  let e : Mod2Homology H n SphereSpectrum ≃+ HomotopyGroup n H.HF2 :=
    ((homotopyGroupFunctor n).mapIso (ρ_ H.HF2)).addCommGroupIsoToAddEquiv
  by_cases hn : n = 0
  · subst n
    have hgen : e (inducedMap (adamsUnit H.unit (SphereSpectrum : C)) 0
        ((shiftFunctorZero C ℤ).hom.app SphereSpectrum)) = H.pi0Equiv.symm 1 := by
      change ((shiftFunctorZero C ℤ).hom.app SphereSpectrum ≫
        adamsUnit H.unit SphereSpectrum) ≫ (ρ_ H.HF2).hom = _
      rw [Category.assoc, adamsUnit_sphere_unitor]
      simp [Mod2EilenbergMacLane.unit]
    have htwo : ∀ a : ZMod 2, a = 0 ∨ a = 1 := by decide
    rcases htwo (H.pi0Equiv (e x)) with hx | hx
    · refine ⟨0, ?_⟩
      apply e.injective
      apply H.pi0Equiv.injective
      simpa using hx.symm
    · refine ⟨(shiftFunctorZero C ℤ).hom.app SphereSpectrum, ?_⟩
      apply e.injective
      apply H.pi0Equiv.injective
      rw [hgen, H.pi0Equiv.apply_symm_apply]
      exact hx.symm
  · letI := H.homotopy_vanishes n hn
    letI : Subsingleton (Mod2Homology H n SphereSpectrum) := e.injective.subsingleton
    exact ⟨0, Subsingleton.elim _ _⟩

/-- Inner and outer unit insertion agree on any class in the unit image. -/
theorem mod2CoactionMap_unit_image (X : C) (n : ℤ) (x : HomotopyGroup n X) :
    mod2CoactionMap H X n (inducedMap (adamsUnit H.unit X) n x) =
      mod2OuterUnitMap H X n (inducedMap (adamsUnit H.unit X) n x) := by
  change (x ≫ adamsUnit H.unit X) ≫ H.HF2 ◁ adamsUnit H.unit X =
    (x ≫ adamsUnit H.unit X) ≫ adamsUnit H.unit (H.HF2 ⊗ X)
  rw [Category.assoc, mod2AdamsUnit_naturality, Category.assoc]

/-- For sphere coefficient homology the two actual unit insertions agree
on every class. No coordinate or coaction comparison is assumed. -/
theorem mod2CoactionMap_sphere (n : ℤ) (x : Mod2Homology H n SphereSpectrum) :
    mod2CoactionMap H SphereSpectrum n x = mod2OuterUnitMap H SphereSpectrum n x := by
  obtain ⟨z, rfl⟩ := mod2SphereHomology_unit_surjective H n x
  exact mod2CoactionMap_unit_image H SphereSpectrum n z

end

end KIP126.StableHomotopy.Cohomology
