import PageTransitionCertificates.Import
namespace PageTransitionCertificates.Release15
open LinProgramCertificates
def certificate750 : WireComparison := ⟨1, 2, 2, 4, 2, [false, false, false, false], [false, false, false, false, false, false, false, false], [true, false, false, true], [true, false, false, true], [false, false, false, false, false, false, false, false], [false, false, false, false]⟩
theorem comparison750 : certificate750.Valid := by lin_cert using ()
def certificate751 : WireComparison := ⟨1, 3, 2, 4, 0, [false, false, false, false, true, false], [false, false, false, false, false, false, true, false], [], [], [false, false, false, false, false, true, false, false], [false, false, true, false, false, false]⟩
theorem comparison751 : certificate751.Valid := by lin_cert using ()
def certificate752 : WireComparison := ⟨1, 3, 4, 4, 1, [false, false, false, false, true, false, false, false, false, false, false, false], [false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, false], [false, true, false, false], [false, true, false, true], [false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false], [false, true, false, false, false, false, false, false, false, false, false, false]⟩
theorem comparison752 : certificate752.Valid := by lin_cert using ()
def certificate753 : WireComparison := ⟨1, 3, 2, 3, 2, [false, false, false, false, false, false], [false, false, false, false, false, false], [true, false, false, true], [true, false, false, true], [false, false, false, false, false, false], [false, false, false, false, false, false]⟩
theorem comparison753 : certificate753.Valid := by lin_cert using ()
def certificate754 : WireComparison := ⟨1, 3, 1, 2, 0, [false, false, false], [false, true], [], [], [false, true], [false, false, false]⟩
theorem comparison754 : certificate754.Valid := by lin_cert using ()
def certificate755 : WireComparison := ⟨1, 1, 1, 2, 1, [false], [false, false], [true], [true], [false, false], [false]⟩
theorem comparison755 : certificate755.Valid := by lin_cert using ()
def certificate756 : WireComparison := ⟨1, 2, 3, 4, 2, [false, false, false, true, true, false], [false, false, false, false, false, false, false, false, false, false, false, false], [true, false, true, false, false, true], [false, true, false, false, false, true], [false, false, false, false, false, false, false, false, false, false, false, false], [false, true, false, false, false, false]⟩
theorem comparison756 : certificate756.Valid := by lin_cert using ()
def certificate757 : WireComparison := ⟨1, 3, 4, 4, 0, [false, false, false, false, false, true, false, false, true, false, false, false], [false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false], [], [], [false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false], [false, false, true, false, true, false, false, false, false, false, false, false]⟩
theorem comparison757 : certificate757.Valid := by lin_cert using ()
def certificate758 : WireComparison := ⟨1, 1, 2, 4, 2, [false, false], [false, false, false, false, false, false, false, false], [true, false, false, true], [true, false, false, true], [false, false, false, false, false, false, false, false], [false, false]⟩
theorem comparison758 : certificate758.Valid := by lin_cert using ()
def certificate759 : WireComparison := ⟨1, 3, 3, 3, 0, [false, false, false, true, false, false, true, true, false], [false, false, false, false, false, false, true, false, false], [], [], [false, false, true, false, false, false, false, false, false], [false, true, false, false, true, true, false, false, false]⟩
theorem comparison759 : certificate759.Valid := by lin_cert using ()
def certificate760 : WireComparison := ⟨1, 1, 1, 2, 1, [false], [false, false], [true], [true], [false, false], [false]⟩
theorem comparison760 : certificate760.Valid := by lin_cert using ()
def certificate761 : WireComparison := ⟨1, 1, 2, 2, 2, [false, false], [false, false, false, false], [true, false, false, true], [true, false, false, true], [false, false, false, false], [false, false]⟩
theorem comparison761 : certificate761.Valid := by lin_cert using ()
def certificate762 : WireComparison := ⟨1, 2, 3, 2, 2, [false, false, false, false, false, false], [false, false, false, false, true, false], [true, false, false, true, false, false], [true, false, false, false, true, false], [false, false, true, false, false, false], [false, false, false, false, false, false]⟩
theorem comparison762 : certificate762.Valid := by lin_cert using ()
def certificate763 : WireComparison := ⟨1, 2, 3, 4, 1, [false, false, false, true, false, false], [false, false, false, false, true, false, false, false, false, false, false, false], [false, false, true], [false, false, true], [false, true, false, false, false, false, false, false, false, false, false, false], [false, true, false, false, false, false]⟩
theorem comparison763 : certificate763.Valid := by lin_cert using ()
def certificate764 : WireComparison := ⟨1, 1, 3, 2, 3, [false, false, false], [false, false, false, false, false, false], [true, false, false, false, true, false, false, false, true], [true, false, false, false, true, false, false, false, true], [false, false, false, false, false, false], [false, false, false]⟩
theorem comparison764 : certificate764.Valid := by lin_cert using ()
def certificate765 : WireComparison := ⟨1, 4, 2, 3, 2, [false, false, false, false, false, false, false, false], [false, false, false, false, false, false], [true, false, false, true], [true, false, false, true], [false, false, false, false, false, false], [false, false, false, false, false, false, false, false]⟩
theorem comparison765 : certificate765.Valid := by lin_cert using ()
def certificate766 : WireComparison := ⟨1, 0, 1, 1, 1, [], [false], [true], [true], [false], []⟩
theorem comparison766 : certificate766.Valid := by lin_cert using ()
def certificate767 : WireComparison := ⟨1, 1, 2, 3, 0, [true, false], [false, false, false, true, true, false], [], [], [false, true, false, false, false, false], [true, false]⟩
theorem comparison767 : certificate767.Valid := by lin_cert using ()
def certificate768 : WireComparison := ⟨1, 3, 3, 4, 0, [false, false, false, false, false, false, true, false, false], [false, false, false, false, false, true, false, false, true, false, false, false], [], [], [false, false, true, false, true, false, false, false, false, false, false, false], [false, false, true, false, false, false, false, false, false]⟩
theorem comparison768 : certificate768.Valid := by lin_cert using ()
def certificate769 : WireComparison := ⟨1, 1, 1, 2, 0, [true], [false, false], [], [], [false, false], [true]⟩
theorem comparison769 : certificate769.Valid := by lin_cert using ()
def certificate770 : WireComparison := ⟨1, 1, 3, 3, 0, [true, false, false], [false, false, false, true, false, false, true, true, false], [], [], [false, true, false, false, true, true, false, false, false], [true, false, false]⟩
theorem comparison770 : certificate770.Valid := by lin_cert using ()
def certificate771 : WireComparison := ⟨1, 4, 3, 3, 3, [false, false, false, false, false, false, false, false, false, false, false, false], [false, false, false, false, false, false, false, false, false], [true, false, false, false, true, false, false, false, true], [true, false, false, false, true, false, false, false, true], [false, false, false, false, false, false, false, false, false], [false, false, false, false, false, false, false, false, false, false, false, false]⟩
theorem comparison771 : certificate771.Valid := by lin_cert using ()
def certificate772 : WireComparison := ⟨1, 1, 1, 2, 1, [false], [false, false], [true], [true], [false, false], [false]⟩
theorem comparison772 : certificate772.Valid := by lin_cert using ()
def certificate773 : WireComparison := ⟨1, 0, 2, 3, 2, [], [false, false, false, false, false, false], [true, false, false, true], [true, false, false, true], [false, false, false, false, false, false], []⟩
theorem comparison773 : certificate773.Valid := by lin_cert using ()
def certificate774 : WireComparison := ⟨1, 1, 2, 3, 1, [false, false], [false, false, false, true, false, false], [true, false], [true, false], [false, true, false, false, false, false], [false, false]⟩
theorem comparison774 : certificate774.Valid := by lin_cert using ()
def certificate775 : WireComparison := ⟨1, 2, 1, 3, 0, [false, true], [false, false, false], [], [], [false, false, false], [false, true]⟩
theorem comparison775 : certificate775.Valid := by lin_cert using ()
def certificate776 : WireComparison := ⟨1, 2, 4, 2, 3, [false, false, false, false, true, false, false, false], [false, false, false, false, false, false, false, false], [false, false, false, true, false, false, false, true, false, false, false, true], [false, true, false, false, false, false, true, false, false, false, false, true], [false, false, false, false, false, false, false, false], [false, true, false, false, false, false, false, false]⟩
theorem comparison776 : certificate776.Valid := by lin_cert using ()
def certificate777 : WireComparison := ⟨1, 1, 2, 3, 2, [false, false], [false, false, false, false, false, false], [true, false, false, true], [true, false, false, true], [false, false, false, false, false, false], [false, false]⟩
theorem comparison777 : certificate777.Valid := by lin_cert using ()
def certificate778 : WireComparison := ⟨1, 0, 1, 2, 0, [], [true, false], [], [], [true, false], []⟩
theorem comparison778 : certificate778.Valid := by lin_cert using ()
def certificate779 : WireComparison := ⟨1, 1, 3, 3, 2, [false, false, false], [false, false, false, false, false, false, true, false, false], [true, false, false, true, false, false], [true, false, false, false, true, false], [false, false, true, false, false, false, false, false, false], [false, false, false]⟩
theorem comparison779 : certificate779.Valid := by lin_cert using ()
def certificate780 : WireComparison := ⟨1, 1, 1, 1, 0, [false], [true], [], [], [true], [false]⟩
theorem comparison780 : certificate780.Valid := by lin_cert using ()
def certificate781 : WireComparison := ⟨1, 0, 1, 3, 0, [], [true, false, false], [], [], [true, false, false], []⟩
theorem comparison781 : certificate781.Valid := by lin_cert using ()
def certificate782 : WireComparison := ⟨1, 2, 4, 3, 3, [true, true, false, false, false, false, false, false], [false, false, false, false, false, false, false, false, false, false, false, false], [true, false, false, true, false, false, false, true, false, false, false, true], [false, true, false, false, false, false, true, false, false, false, false, true], [false, false, false, false, false, false, false, false, false, false, false, false], [true, false, false, false, false, false, false, false]⟩
theorem comparison782 : certificate782.Valid := by lin_cert using ()
def certificate783 : WireComparison := ⟨1, 4, 1, 1, 0, [false, false, false, true], [false], [], [], [false], [false, false, false, true]⟩
theorem comparison783 : certificate783.Valid := by lin_cert using ()
def certificate784 : WireComparison := ⟨1, 2, 1, 2, 0, [false, true], [false, false], [], [], [false, false], [false, true]⟩
theorem comparison784 : certificate784.Valid := by lin_cert using ()
def certificate785 : WireComparison := ⟨1, 0, 2, 1, 1, [], [false, true], [true, false], [true, false], [false, true], []⟩
theorem comparison785 : certificate785.Valid := by lin_cert using ()
def certificate786 : WireComparison := ⟨1, 2, 2, 4, 1, [false, false, false, false], [false, false, false, false, true, false, false, false], [true, false], [true, false], [false, true, false, false, false, false, false, false], [false, false, false, false]⟩
theorem comparison786 : certificate786.Valid := by lin_cert using ()
def certificate787 : WireComparison := ⟨1, 3, 1, 2, 0, [false, false, true], [false, false], [], [], [false, false], [false, false, true]⟩
theorem comparison787 : certificate787.Valid := by lin_cert using ()
def certificate788 : WireComparison := ⟨1, 1, 1, 2, 1, [false], [false, false], [true], [true], [false, false], [false]⟩
theorem comparison788 : certificate788.Valid := by lin_cert using ()
def certificate789 : WireComparison := ⟨1, 3, 1, 3, 0, [false, true, false], [false, false, false], [], [], [false, false, false], [false, true, false]⟩
theorem comparison789 : certificate789.Valid := by lin_cert using ()
def certificate790 : WireComparison := ⟨1, 0, 1, 1, 1, [], [false], [true], [true], [false], []⟩
theorem comparison790 : certificate790.Valid := by lin_cert using ()
def certificate791 : WireComparison := ⟨1, 2, 2, 4, 0, [false, false, false, true], [true, true, false, false, false, false, false, false], [], [], [true, false, false, false, false, false, false, false], [false, false, false, true]⟩
theorem comparison791 : certificate791.Valid := by lin_cert using ()
def certificate792 : WireComparison := ⟨1, 1, 4, 1, 2, [false, true, false, false], [false, false, false, true], [true, false, false, false, false, true, false, false], [true, false, false, false, false, false, true, false], [false, false, false, true], [false, true, false, false]⟩
theorem comparison792 : certificate792.Valid := by lin_cert using ()
def certificate793 : WireComparison := ⟨1, 2, 1, 3, 1, [false, false], [false, false, false], [true], [true], [false, false, false], [false, false]⟩
theorem comparison793 : certificate793.Valid := by lin_cert using ()
def certificate794 : WireComparison := ⟨1, 0, 2, 1, 1, [], [false, true], [true, false], [true, false], [false, true], []⟩
theorem comparison794 : certificate794.Valid := by lin_cert using ()
def certificate795 : WireComparison := ⟨1, 3, 2, 2, 1, [false, false, true, false, false, false], [false, false, false, false], [false, true], [false, true], [false, false, false, false], [false, true, false, false, false, false]⟩
theorem comparison795 : certificate795.Valid := by lin_cert using ()
def certificate796 : WireComparison := ⟨1, 0, 3, 1, 2, [], [false, false, true], [true, false, false, true, false, false], [true, false, false, false, true, false], [false, false, true], []⟩
theorem comparison796 : certificate796.Valid := by lin_cert using ()
def certificate797 : WireComparison := ⟨1, 2, 1, 1, 0, [false, true], [false], [], [], [false], [false, true]⟩
theorem comparison797 : certificate797.Valid := by lin_cert using ()
def certificate798 : WireComparison := ⟨1, 4, 2, 6, 0, [true, false, false, false, false, false, false, false], [false, false, false, false, false, false, true, true, false, false, false, false], [], [], [false, true, false, false, false, false, false, false, false, false, false, false], [true, false, false, false, false, false, false, false]⟩
theorem comparison798 : certificate798.Valid := by lin_cert using ()
def certificate799 : WireComparison := ⟨1, 1, 2, 2, 1, [false, false], [false, false, false, true], [true, false], [true, false], [false, false, false, true], [false, false]⟩
theorem comparison799 : certificate799.Valid := by lin_cert using ()
end PageTransitionCertificates.Release15
