import Row2796D4Detector.Actual
import PageTransitionCertificates.InducedMap
import PageTransitionCertificates.Import
namespace Row2796D4Detector.Comparison
open LinearCertificates PageTransitionCertificates ResolutionCertificates Actual
def lowerS : WireComparison := ⟨1,6,5,3,2,[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true],[false,false,false,false,false,false,false,false,false,false,true,false,false,false,false],[false,true,true,false,false,false,false,false,false,false],[false,true,false,false,false,true,false,false,false,false],[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true]⟩
theorem lowerS_complete : lowerS.Valid := by lin_cert using ()
def lowerT : WireComparison := ⟨1,10,6,5,2,[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false],[false,true,false,false,false,false,false,false,true,false,false,false],[false,false,false,false,true,false,true,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]⟩
theorem lowerT_complete : lowerT.Valid := by lin_cert using ()
def lowerMiddle : Matrix 6 5 := matrixOf _ _ m9_136.entries
def lowerOut : Matrix 10 6 := matrixOf _ _ m11_137.entries
def lowerIn : Matrix 5 3 := matrixOf _ _ m7_135.entries
theorem lowerCompatible : CompatibleMap (matrixOf lowerS.k lowerS.m lowerS.outgoing) (matrixOf lowerS.m lowerS.n lowerS.incoming) (matrixOf lowerT.k lowerT.m lowerT.outgoing) (matrixOf lowerT.m lowerT.n lowerT.incoming) lowerMiddle lowerOut lowerIn := by lin_cert using ()
def lowerMap := coordinateMap lowerS.comparison lowerT.comparison lowerMiddle
def centerS : WireComparison := ⟨1,3,5,6,1,[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false],[true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true],[false,false,false,true,false],[false,false,false,true,false],[true,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true],[false,false,false,false,false,true,false,false,false,false,false,false,false,false,false]⟩
theorem centerS_complete : centerS.Valid := by lin_cert using ()
def centerT : WireComparison := ⟨1,4,8,10,4,[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true],[false,false,false,false,true,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,true,false,true,false,false,false,false],[false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,true,false,false,false,true,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]⟩
theorem centerT_complete : centerT.Valid := by lin_cert using ()
def centerMiddle : Matrix 8 5 := matrixOf _ _ m12_138.entries
def centerOut : Matrix 4 3 := matrixOf _ _ m14_139.entries
def centerIn : Matrix 10 6 := matrixOf _ _ m10_137.entries
theorem centerCompatible : CompatibleMap (matrixOf centerS.k centerS.m centerS.outgoing) (matrixOf centerS.m centerS.n centerS.incoming) (matrixOf centerT.k centerT.m centerT.outgoing) (matrixOf centerT.m centerT.n centerT.incoming) centerMiddle centerOut centerIn := by lin_cert using ()
def centerMap := coordinateMap centerS.comparison centerT.comparison centerMiddle
def upperS : WireComparison := ⟨1,4,5,3,2,[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,true,false],[false,false,true,false,false,true,false,false,false,false],[false,true,false,false,false,false,false,true,false,false],[false,false,false,false,false,false,false,false,false,true,false,false,false,false,false],[false,false,false,true,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false]⟩
theorem upperS_complete : upperS.Valid := by lin_cert using ()
def upperT : WireComparison := ⟨1,6,6,4,3,[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true],[false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,true,true,false,false,false,false,false,true,true,false,false,false,false,false,false,false],[false,true,false,false,false,false,false,true,false,true,false,false,true,false,false,false,false,false],[false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true]⟩
theorem upperT_complete : upperT.Valid := by lin_cert using ()
def upperMiddle : Matrix 6 5 := matrixOf _ _ m15_140.entries
def upperOut : Matrix 6 4 := matrixOf _ _ m17_141.entries
def upperIn : Matrix 4 3 := matrixOf _ _ m13_139.entries
theorem upperCompatible : CompatibleMap (matrixOf upperS.k upperS.m upperS.outgoing) (matrixOf upperS.m upperS.n upperS.incoming) (matrixOf upperT.k upperT.m upperT.outgoing) (matrixOf upperT.m upperT.n upperT.incoming) upperMiddle upperOut upperIn := by lin_cert using ()
def upperMap := coordinateMap upperS.comparison upperT.comparison upperMiddle
def namedS : WireComparison := ⟨1,5,7,4,2,[false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,true],[false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,true,true,true,false,false,false,false],[false,false,false,true,true,false,false,false,false,false,false,false,false,false],[false,false,true,false,false,false,false,false,true,false,false,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false],[false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true]⟩
theorem namedS_complete : namedS.Valid := by lin_cert using ()
def namedT : WireComparison := ⟨1,9,9,4,2,[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,true],[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,true,true,true,false,false,false,false,false,true,true,true,false],[false,false,false,true,false,true,false,false,false,false,false,false,false,false,true,false,false,false],[false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false],[false,false,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false],[false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false]⟩
theorem namedT_complete : namedT.Valid := by lin_cert using ()
def namedMiddle : Matrix 9 7 := matrixOf _ _ m8_135.entries
def namedOut : Matrix 9 5 := matrixOf _ _ m10_136.entries
def namedIn : Matrix 4 4 := matrixOf _ _ m6_134.entries
theorem namedCompatible : CompatibleMap (matrixOf namedS.k namedS.m namedS.outgoing) (matrixOf namedS.m namedS.n namedS.incoming) (matrixOf namedT.k namedT.m namedT.outgoing) (matrixOf namedT.m namedT.n namedT.incoming) namedMiddle namedOut namedIn := by lin_cert using ()
def namedMap := coordinateMap namedS.comparison namedT.comparison namedMiddle
def source : WireComparison := ⟨1,2,1,2,1,[false,false],[false,false],[true],[true],[false,false],[false,false]⟩
theorem source_complete : source.Valid := by lin_cert using ()
def target : WireComparison := ⟨1,3,4,2,3,[false,false,false,false,false,false,false,false,false,false,false,false],[false,true,false,false,false,false,false,false],[false,false,false,true,false,false,false,true,false,false,false,true],[false,true,false,false,false,false,true,false,false,false,false,true],[false,false,false,false,true,false,false,false],[false,false,false,false,false,false,false,false,false,false,false,false]⟩
theorem target_complete : target.Valid := by lin_cert using ()
theorem compatible : CompatibleMap (matrixOf source.k source.m source.outgoing) (matrixOf source.m source.n source.incoming) (matrixOf target.k target.m target.outgoing) (matrixOf target.m target.n target.incoming) centerMap upperMap lowerMap := by lin_cert using ()
def namedSource : WireComparison := ⟨1,2,2,0,2,[false,false,false,false],[],[true,false,false,true],[true,false,false,true],[],[false,false,false,false]⟩
theorem namedSource_complete : namedSource.Valid := by lin_cert using ()
end Row2796D4Detector.Comparison
