import AggregateTargetInventory.EventAudit.Events
import AggregateTargetInventory.Bases
namespace AggregateTargetInventory.EventAudit.CoordinateLinks
open LinearCertificates PageTransitionCertificates Data Events
theorem event2435_source_recursive : event2435Source = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event2435Source i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event2435_target_recursive : event2435Target = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event2435Target i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2435_inventory_basis_column : event2435Source = (fun i => AggregateTargetInventory.Bases.f5.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 1, event2435Source i = (fun i => AggregateTargetInventory.Bases.f5.basis i ⟨0,by decide⟩) i from by decide) i
theorem event2492_source_recursive : event2492Source = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event2492Source i = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) i from by decide) i
theorem event2492_target_recursive : event2492Target = (eval b_S0_10_134_d3.comparison.projection (eval b_S0_10_134_d2.comparison.projection (fun i => ([true,false,false,true,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 4, event2492Target i = (eval b_S0_10_134_d3.comparison.projection (eval b_S0_10_134_d2.comparison.projection (fun i => ([true,false,false,true,false] : List Bool)[i.val]!))) i from by decide) i
theorem event2492_inventory_basis_column : event2492Source = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f6.basis i ⟨0,by decide⟩))) := by funext i; exact (show ∀ i : Fin 2, event2492Source i = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f6.basis i ⟨0,by decide⟩))) i from by decide) i
theorem event2493_source_recursive : event2493Source = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => ([false,true] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event2493Source i = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => ([false,true] : List Bool)[i.val]!))) i from by decide) i
theorem event2493_target_recursive : event2493Target = (eval b_S0_10_134_d3.comparison.projection (eval b_S0_10_134_d2.comparison.projection (fun i => ([true,true,false,true,true] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 4, event2493Target i = (eval b_S0_10_134_d3.comparison.projection (eval b_S0_10_134_d2.comparison.projection (fun i => ([true,true,false,true,true] : List Bool)[i.val]!))) i from by decide) i
theorem event2493_inventory_basis_column : event2493Source = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f6.basis i ⟨1,by decide⟩))) := by funext i; exact (show ∀ i : Fin 2, event2493Source i = (eval b_S0_6_131_d3.comparison.projection (eval b_S0_6_131_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f6.basis i ⟨1,by decide⟩))) i from by decide) i
theorem event2572_source_recursive : event2572Source = (eval b_S0_4_130_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event2572Source i = (eval b_S0_4_130_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2572_target_recursive : event2572Target = (eval b_S0_7_132_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event2572Target i = (eval b_S0_7_132_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!)) i from by decide) i
theorem event2572_inventory_basis_column : event2572Target = (eval b_S0_7_132_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f7.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event2572Target i = (eval b_S0_7_132_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f7.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event2629_source_recursive : event2629Source = (eval b_S0_8_133_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event2629Source i = (eval b_S0_8_133_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2629_target_recursive : event2629Target = (eval b_S0_11_135_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event2629Target i = (eval b_S0_11_135_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2629_inventory_basis_column : event2629Source = (eval b_S0_8_133_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f8.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event2629Source i = (eval b_S0_8_133_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f8.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event2630_source_recursive : event2630Source = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event2630Source i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2630_target_recursive : event2630Target = (fun i => ([false,false,true,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2630Target i = (fun i => ([false,false,true,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2630_inventory_basis_column : event2630Source = (fun i => AggregateTargetInventory.Bases.f8.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event2630Source i = (fun i => AggregateTargetInventory.Bases.f8.basis i ⟨1,by decide⟩) i from by decide) i
theorem event2698_source_recursive : event2698Source = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2698Source i = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2698_target_recursive : event2698Target = (fun i => ([false,false,false,true,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2698Target i = (fun i => ([false,false,false,true,true] : List Bool)[i.val]!) i from by decide) i
theorem event2698_inventory_basis_column : event2698Source = (fun i => AggregateTargetInventory.Bases.f9.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2698Source i = (fun i => AggregateTargetInventory.Bases.f9.basis i ⟨3,by decide⟩) i from by decide) i
theorem event2699_source_recursive : event2699Source = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2699Source i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2699_target_recursive : event2699Target = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2699Target i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2699_inventory_basis_column : event2699Source = (fun i => AggregateTargetInventory.Bases.f9.basis i ⟨4,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2699Source i = (fun i => AggregateTargetInventory.Bases.f9.basis i ⟨4,by decide⟩) i from by decide) i
theorem event2783_source_recursive : event2783Source = (fun i => ([false,true,false,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 6, event2783Source i = (fun i => ([false,true,false,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2783_target_recursive : event2783Target = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2783Target i = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event2783_inventory_basis_column : event2783Target = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2783Target i = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨0,by decide⟩) i from by decide) i
theorem event2784_source_recursive : event2784Source = (eval b_S0_10_135_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event2784Source i = (eval b_S0_10_135_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2784_target_recursive : event2784Target = (eval b_S0_13_137_d2.comparison.projection (fun i => ([true,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 3, event2784Target i = (eval b_S0_13_137_d2.comparison.projection (fun i => ([true,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2784_inventory_basis_column : event2784Source = (eval b_S0_10_135_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨1,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event2784Source i = (eval b_S0_10_135_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨1,by decide⟩)) i from by decide) i
theorem event2785_source_recursive : event2785Source = (fun i => ([false,true,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2785Source i = (fun i => ([false,true,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2785_target_recursive : event2785Target = (fun i => ([false,true,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2785Target i = (fun i => ([false,true,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2785_inventory_basis_column : event2785Source = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2785Source i = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨2,by decide⟩) i from by decide) i
theorem event2786_source_recursive : event2786Source = (fun i => ([false,false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2786Source i = (fun i => ([false,false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2786_target_recursive : event2786Target = (fun i => ([false,false,false,true,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2786Target i = (fun i => ([false,false,false,true,true] : List Bool)[i.val]!) i from by decide) i
theorem event2786_inventory_basis_column : event2786Source = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2786Source i = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨3,by decide⟩) i from by decide) i
theorem event2787_source_recursive : event2787Source = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2787Source i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2787_target_recursive : event2787Target = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2787Target i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2787_inventory_basis_column : event2787Source = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨4,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2787Source i = (fun i => AggregateTargetInventory.Bases.f10.basis i ⟨4,by decide⟩) i from by decide) i
theorem event2850_source_recursive : event2850Source = (eval b_S0_8_134_d2.comparison.projection (fun i => ([false,false,false,true,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 4, event2850Source i = (eval b_S0_8_134_d2.comparison.projection (fun i => ([false,false,false,true,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2850_target_recursive : event2850Target = (eval b_S0_11_136_d2.comparison.projection (fun i => ([false,true,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 4, event2850Target i = (eval b_S0_11_136_d2.comparison.projection (fun i => ([false,true,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2850_inventory_basis_column : event2850Target = (eval b_S0_11_136_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 4, event2850Target i = (eval b_S0_11_136_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event2851_source_recursive : event2851Source = (eval b_S0_8_134_d2.comparison.projection (fun i => ([false,false,true,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 4, event2851Source i = (eval b_S0_8_134_d2.comparison.projection (fun i => ([false,false,true,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2851_target_recursive : event2851Target = (eval b_S0_11_136_d2.comparison.projection (fun i => ([false,false,true,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 4, event2851Target i = (eval b_S0_11_136_d2.comparison.projection (fun i => ([false,false,true,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2851_inventory_basis_column : event2851Target = (eval b_S0_11_136_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨1,by decide⟩)) := by funext i; exact (show ∀ i : Fin 4, event2851Target i = (eval b_S0_11_136_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨1,by decide⟩)) i from by decide) i
theorem event2853_source_recursive : event2853Source = (eval b_S0_11_136_d3.comparison.projection (eval b_S0_11_136_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event2853Source i = (eval b_S0_11_136_d3.comparison.projection (eval b_S0_11_136_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event2853_target_recursive : event2853Target = (eval b_S0_15_139_d3.comparison.projection (eval b_S0_15_139_d2.comparison.projection (fun i => ([true,false,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event2853Target i = (eval b_S0_15_139_d3.comparison.projection (eval b_S0_15_139_d2.comparison.projection (fun i => ([true,false,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event2853_inventory_basis_column : event2853Source = (eval b_S0_11_136_d3.comparison.projection (eval b_S0_11_136_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨3,by decide⟩))) := by funext i; exact (show ∀ i : Fin 2, event2853Source i = (eval b_S0_11_136_d3.comparison.projection (eval b_S0_11_136_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨3,by decide⟩))) i from by decide) i
theorem event2854_source_recursive : event2854Source = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2854Source i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2854_target_recursive : event2854Target = (fun i => ([false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event2854Target i = (fun i => ([false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2854_inventory_basis_column : event2854Source = (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨4,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2854Source i = (fun i => AggregateTargetInventory.Bases.f11.basis i ⟨4,by decide⟩) i from by decide) i
theorem event2918_source_recursive : event2918Source = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2918Source i = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2918_target_recursive : event2918Target = (fun i => ([false,false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2918Target i = (fun i => ([false,false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2918_inventory_basis_column : event2918Target = (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2918Target i = (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨0,by decide⟩) i from by decide) i
theorem event2919_source_recursive : event2919Source = (eval b_S0_9_135_d2.comparison.projection (fun i => ([true,false,false,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 4, event2919Source i = (eval b_S0_9_135_d2.comparison.projection (fun i => ([true,false,false,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2919_target_recursive : event2919Target = (eval b_S0_12_137_d2.comparison.projection (fun i => ([false,false,false,true,true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event2919Target i = (eval b_S0_12_137_d2.comparison.projection (fun i => ([false,false,false,true,true] : List Bool)[i.val]!)) i from by decide) i
theorem event2919_inventory_basis_column : event2919Target = (eval b_S0_12_137_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨1,by decide⟩)) := by funext i; exact (show ∀ i : Fin 2, event2919Target i = (eval b_S0_12_137_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨1,by decide⟩)) i from by decide) i
theorem event2920_source_recursive : event2920Source = (eval b_S0_9_135_d2.comparison.projection (fun i => ([true,false,false,true,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 4, event2920Source i = (eval b_S0_9_135_d2.comparison.projection (fun i => ([true,false,false,true,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event2920_target_recursive : event2920Target = (eval b_S0_12_137_d2.comparison.projection (fun i => ([false,false,false,false,true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event2920Target i = (eval b_S0_12_137_d2.comparison.projection (fun i => ([false,false,false,false,true] : List Bool)[i.val]!)) i from by decide) i
theorem event2920_inventory_basis_column : event2920Target = (eval b_S0_12_137_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨2,by decide⟩)) := by funext i; exact (show ∀ i : Fin 2, event2920Target i = (eval b_S0_12_137_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨2,by decide⟩)) i from by decide) i
theorem event2921_source_recursive : event2921Source = (fun i => ([false,true,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2921Source i = (fun i => ([false,true,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2921_target_recursive : event2921Target = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2921Target i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event2921_inventory_basis_column : event2921Source = (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2921Source i = (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨3,by decide⟩) i from by decide) i
theorem event2922_source_recursive : event2922Source = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2922Source i = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event2922_target_recursive : event2922Target = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event2922Target i = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event2922_inventory_basis_column : event2922Source = (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨4,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event2922Source i = (fun i => AggregateTargetInventory.Bases.f12.basis i ⟨4,by decide⟩) i from by decide) i
theorem event3008_source_recursive : event3008Source = (fun i => ([true,false,false,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 6, event3008Source i = (fun i => ([true,false,false,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3008_target_recursive : event3008Target = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event3008Target i = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3008_inventory_basis_column : event3008Target = (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event3008Target i = (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨0,by decide⟩) i from by decide) i
theorem event3009_source_recursive : event3009Source = (fun i => ([false,false,false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 6, event3009Source i = (fun i => ([false,false,false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3009_target_recursive : event3009Target = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event3009Target i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3009_inventory_basis_column : event3009Target = (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event3009Target i = (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨1,by decide⟩) i from by decide) i
theorem event3010_source_recursive : event3010Source = (eval b_S0_9_135_d3.comparison.projection (eval b_S0_9_135_d2.comparison.projection (fun i => ([false,false,true,false,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event3010Source i = (eval b_S0_9_135_d3.comparison.projection (eval b_S0_9_135_d2.comparison.projection (fun i => ([false,false,true,false,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event3010_target_recursive : event3010Target = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event3010Target i = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => ([true,false,false,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event3010_inventory_basis_column : event3010Target = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨2,by decide⟩))) := by funext i; exact (show ∀ i : Fin 2, event3010Target i = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨2,by decide⟩))) i from by decide) i
theorem event3011_source_recursive : event3011Source = (eval b_S0_9_135_d3.comparison.projection (eval b_S0_9_135_d2.comparison.projection (fun i => ([false,true,false,false,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event3011Source i = (eval b_S0_9_135_d3.comparison.projection (eval b_S0_9_135_d2.comparison.projection (fun i => ([false,true,false,false,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event3011_target_recursive : event3011Target = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => ([false,false,true,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event3011Target i = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => ([false,false,true,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event3011_inventory_basis_column : event3011Target = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨3,by decide⟩))) := by funext i; exact (show ∀ i : Fin 2, event3011Target i = (eval b_S0_13_138_d3.comparison.projection (eval b_S0_13_138_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨3,by decide⟩))) i from by decide) i
theorem event3012_source_recursive : event3012Source = (eval b_S0_13_138_d2.comparison.projection (fun i => ([false,true,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 3, event3012Source i = (eval b_S0_13_138_d2.comparison.projection (fun i => ([false,true,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3012_target_recursive : event3012Target = (eval b_S0_16_140_d2.comparison.projection (fun i => ([false,true,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 3, event3012Target i = (eval b_S0_16_140_d2.comparison.projection (fun i => ([false,true,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3012_inventory_basis_column : event3012Source = (eval b_S0_13_138_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨4,by decide⟩)) := by funext i; exact (show ∀ i : Fin 3, event3012Source i = (eval b_S0_13_138_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f13.basis i ⟨4,by decide⟩)) i from by decide) i
theorem event3079_source_recursive : event3079Source = (fun i => ([false,true,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event3079Source i = (fun i => ([false,true,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3079_target_recursive : event3079Target = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3079Target i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3079_inventory_basis_column : event3079Target = (fun i => AggregateTargetInventory.Bases.f14.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3079Target i = (fun i => AggregateTargetInventory.Bases.f14.basis i ⟨0,by decide⟩) i from by decide) i
theorem event3081_source_recursive : event3081Source = (fun i => ([true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3081Source i = (fun i => ([true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3081_target_recursive : event3081Target = (fun i => ([false,false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event3081Target i = (fun i => ([false,false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3081_inventory_basis_column : event3081Source = (fun i => AggregateTargetInventory.Bases.f14.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3081Source i = (fun i => AggregateTargetInventory.Bases.f14.basis i ⟨2,by decide⟩) i from by decide) i
theorem event3150_source_recursive : event3150Source = (fun i => ([false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3150Source i = (fun i => ([false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3150_target_recursive : event3150Target = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event3150Target i = (fun i => ([false,false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3150_inventory_basis_column : event3150Target = (fun i => AggregateTargetInventory.Bases.f15.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event3150Target i = (fun i => AggregateTargetInventory.Bases.f15.basis i ⟨0,by decide⟩) i from by decide) i
theorem event3153_source_recursive : event3153Source = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event3153Source i = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3153_target_recursive : event3153Target = (fun i => ([false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3153Target i = (fun i => ([false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3153_inventory_basis_column : event3153Source = (fun i => AggregateTargetInventory.Bases.f15.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event3153Source i = (fun i => AggregateTargetInventory.Bases.f15.basis i ⟨3,by decide⟩) i from by decide) i
theorem event3154_source_recursive : event3154Source = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event3154Source i = (fun i => ([false,false,false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3154_target_recursive : event3154Target = (fun i => ([false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3154Target i = (fun i => ([false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3154_inventory_basis_column : event3154Source = (fun i => AggregateTargetInventory.Bases.f15.basis i ⟨4,by decide⟩) := by funext i; exact (show ∀ i : Fin 5, event3154Source i = (fun i => AggregateTargetInventory.Bases.f15.basis i ⟨4,by decide⟩) i from by decide) i
theorem event3253_source_recursive : event3253Source = (fun i => ([false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3253Source i = (fun i => ([false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3253_target_recursive : event3253Target = (fun i => ([false,false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3253Target i = (fun i => ([false,false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3253_inventory_basis_column : event3253Target = (fun i => AggregateTargetInventory.Bases.f16.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event3253Target i = (fun i => AggregateTargetInventory.Bases.f16.basis i ⟨0,by decide⟩) i from by decide) i
theorem event3255_source_recursive : event3255Source = (fun i => ([true,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3255Source i = (fun i => ([true,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3255_target_recursive : event3255Target = (fun i => ([true,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3255Target i = (fun i => ([true,true] : List Bool)[i.val]!) i from by decide) i
theorem event3255_inventory_basis_column : event3255Source = (fun i => AggregateTargetInventory.Bases.f16.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event3255Source i = (fun i => AggregateTargetInventory.Bases.f16.basis i ⟨2,by decide⟩) i from by decide) i
theorem event3256_source_recursive : event3256Source = (fun i => ([false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3256Source i = (fun i => ([false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3256_target_recursive : event3256Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3256Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3256_inventory_basis_column : event3256Source = (fun i => AggregateTargetInventory.Bases.f16.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event3256Source i = (fun i => AggregateTargetInventory.Bases.f16.basis i ⟨3,by decide⟩) i from by decide) i
theorem event3319_source_recursive : event3319Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3319Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3319_target_recursive : event3319Target = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3319Target i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3319_inventory_basis_column : event3319Target = (fun i => AggregateTargetInventory.Bases.f17.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event3319Target i = (fun i => AggregateTargetInventory.Bases.f17.basis i ⟨0,by decide⟩) i from by decide) i
theorem event3320_source_recursive : event3320Source = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3320Source i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3320_target_recursive : event3320Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3320Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3320_inventory_basis_column : event3320Source = (fun i => AggregateTargetInventory.Bases.f17.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event3320Source i = (fun i => AggregateTargetInventory.Bases.f17.basis i ⟨1,by decide⟩) i from by decide) i
theorem event3392_source_recursive : event3392Source = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3392Source i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3392_target_recursive : event3392Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3392Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3392_inventory_basis_column : event3392Source = (fun i => AggregateTargetInventory.Bases.f18.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event3392Source i = (fun i => AggregateTargetInventory.Bases.f18.basis i ⟨1,by decide⟩) i from by decide) i
theorem event3486_source_recursive : event3486Source = (eval b_S0_19_144_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event3486Source i = (eval b_S0_19_144_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3486_target_recursive : event3486Target = (eval b_S0_22_146_d2.comparison.projection (fun i => ([false,true,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event3486Target i = (eval b_S0_22_146_d2.comparison.projection (fun i => ([false,true,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3486_inventory_basis_column : event3486Source = (eval b_S0_19_144_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f19.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event3486Source i = (eval b_S0_19_144_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f19.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event3487_source_recursive : event3487Source = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3487Source i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3487_target_recursive : event3487Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3487Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3487_inventory_basis_column : event3487Source = (fun i => AggregateTargetInventory.Bases.f19.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3487Source i = (fun i => AggregateTargetInventory.Bases.f19.basis i ⟨1,by decide⟩) i from by decide) i
theorem event3488_source_recursive : event3488Source = (fun i => ([false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3488Source i = (fun i => ([false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3488_target_recursive : event3488Target = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3488Target i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3488_inventory_basis_column : event3488Source = (fun i => AggregateTargetInventory.Bases.f19.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3488Source i = (fun i => AggregateTargetInventory.Bases.f19.basis i ⟨2,by decide⟩) i from by decide) i
theorem event3556_source_recursive : event3556Source = (fun i => ([true,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3556Source i = (fun i => ([true,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3556_target_recursive : event3556Target = (fun i => ([false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3556Target i = (fun i => ([false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3556_inventory_basis_column : event3556Target = (fun i => AggregateTargetInventory.Bases.f20.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3556Target i = (fun i => AggregateTargetInventory.Bases.f20.basis i ⟨0,by decide⟩) i from by decide) i
theorem event3557_source_recursive : event3557Source = (eval b_S0_20_145_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event3557Source i = (eval b_S0_20_145_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3557_target_recursive : event3557Target = (eval b_S0_23_147_d2.comparison.projection (fun i => ([false,false,true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event3557Target i = (eval b_S0_23_147_d2.comparison.projection (fun i => ([false,false,true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3557_inventory_basis_column : event3557Source = (eval b_S0_20_145_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f20.basis i ⟨1,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event3557Source i = (eval b_S0_20_145_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f20.basis i ⟨1,by decide⟩)) i from by decide) i
theorem event3558_source_recursive : event3558Source = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3558Source i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3558_target_recursive : event3558Target = (fun i => ([false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3558Target i = (fun i => ([false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3558_inventory_basis_column : event3558Source = (fun i => AggregateTargetInventory.Bases.f20.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3558Source i = (fun i => AggregateTargetInventory.Bases.f20.basis i ⟨2,by decide⟩) i from by decide) i
theorem event3629_source_recursive : event3629Source = (eval b_S0_17_143_d3.comparison.projection (eval b_S0_17_143_d2.comparison.projection (fun i => ([false,true,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event3629Source i = (eval b_S0_17_143_d3.comparison.projection (eval b_S0_17_143_d2.comparison.projection (fun i => ([false,true,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event3629_target_recursive : event3629Target = (eval b_S0_21_146_d3.comparison.projection (eval b_S0_21_146_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event3629Target i = (eval b_S0_21_146_d3.comparison.projection (eval b_S0_21_146_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event3629_inventory_basis_column : event3629Target = (eval b_S0_21_146_d3.comparison.projection (eval b_S0_21_146_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f21.basis i ⟨0,by decide⟩))) := by funext i; exact (show ∀ i : Fin 1, event3629Target i = (eval b_S0_21_146_d3.comparison.projection (eval b_S0_21_146_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f21.basis i ⟨0,by decide⟩))) i from by decide) i
theorem event3630_source_recursive : event3630Source = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3630Source i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3630_target_recursive : event3630Target = (fun i => ([false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3630Target i = (fun i => ([false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3630_inventory_basis_column : event3630Source = (fun i => AggregateTargetInventory.Bases.f21.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3630Source i = (fun i => AggregateTargetInventory.Bases.f21.basis i ⟨1,by decide⟩) i from by decide) i
theorem event3631_source_recursive : event3631Source = (fun i => ([false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3631Source i = (fun i => ([false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3631_target_recursive : event3631Target = (fun i => ([false,true,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3631Target i = (fun i => ([false,true,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3631_inventory_basis_column : event3631Source = (fun i => AggregateTargetInventory.Bases.f21.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event3631Source i = (fun i => AggregateTargetInventory.Bases.f21.basis i ⟨2,by decide⟩) i from by decide) i
theorem event3746_source_recursive : event3746Source = (fun i => ([false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3746Source i = (fun i => ([false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3746_target_recursive : event3746Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3746Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3746_inventory_basis_column : event3746Source = (fun i => AggregateTargetInventory.Bases.f22.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event3746Source i = (fun i => AggregateTargetInventory.Bases.f22.basis i ⟨2,by decide⟩) i from by decide) i
theorem event3747_source_recursive : event3747Source = (fun i => ([false,false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3747Source i = (fun i => ([false,false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3747_target_recursive : event3747Target = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3747Target i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3747_inventory_basis_column : event3747Source = (fun i => AggregateTargetInventory.Bases.f22.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event3747Source i = (fun i => AggregateTargetInventory.Bases.f22.basis i ⟨3,by decide⟩) i from by decide) i
theorem event3812_source_recursive : event3812Source = (eval b_S0_23_148_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event3812Source i = (eval b_S0_23_148_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3812_target_recursive : event3812Target = (eval b_S0_26_150_d2.comparison.projection (fun i => ([false,false,true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event3812Target i = (eval b_S0_26_150_d2.comparison.projection (fun i => ([false,false,true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event3812_inventory_basis_column : event3812Source = (eval b_S0_23_148_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f23.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event3812Source i = (eval b_S0_23_148_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f23.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event3813_source_recursive : event3813Source = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3813Source i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3813_target_recursive : event3813Target = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event3813Target i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event3813_inventory_basis_column : event3813Source = (fun i => AggregateTargetInventory.Bases.f23.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event3813Source i = (fun i => AggregateTargetInventory.Bases.f23.basis i ⟨1,by decide⟩) i from by decide) i
theorem event3896_source_recursive : event3896Source = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event3896Source i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event3896_target_recursive : event3896Target = (fun i => ([false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3896Target i = (fun i => ([false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3896_inventory_basis_column : event3896Source = (fun i => AggregateTargetInventory.Bases.f24.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 1, event3896Source i = (fun i => AggregateTargetInventory.Bases.f24.basis i ⟨0,by decide⟩) i from by decide) i
theorem event3995_source_recursive : event3995Source = (fun i => ([false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event3995Source i = (fun i => ([false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event3995_target_recursive : event3995Target = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event3995Target i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event3995_inventory_basis_column : event3995Source = (fun i => AggregateTargetInventory.Bases.f25.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event3995Source i = (fun i => AggregateTargetInventory.Bases.f25.basis i ⟨3,by decide⟩) i from by decide) i
theorem event4092_source_recursive : event4092Source = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event4092Source i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event4092_target_recursive : event4092Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4092Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4092_inventory_basis_column : event4092Source = (fun i => AggregateTargetInventory.Bases.f26.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 1, event4092Source i = (fun i => AggregateTargetInventory.Bases.f26.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4162_source_recursive : event4162Source = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4162Source i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4162_target_recursive : event4162Target = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event4162Target i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4162_inventory_basis_column : event4162Source = (fun i => AggregateTargetInventory.Bases.f27.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event4162Source i = (fun i => AggregateTargetInventory.Bases.f27.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4163_source_recursive : event4163Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4163Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4163_target_recursive : event4163Target = (fun i => ([true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event4163Target i = (fun i => ([true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4163_inventory_basis_column : event4163Source = (fun i => AggregateTargetInventory.Bases.f27.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event4163Source i = (fun i => AggregateTargetInventory.Bases.f27.basis i ⟨1,by decide⟩) i from by decide) i
theorem event4263_source_recursive : event4263Source = (fun i => ([true,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event4263Source i = (fun i => ([true,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4263_target_recursive : event4263Target = (fun i => ([false,false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event4263Target i = (fun i => ([false,false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4263_inventory_basis_column : event4263Target = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event4263Target i = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4264_source_recursive : event4264Source = (fun i => ([false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event4264Source i = (fun i => ([false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4264_target_recursive : event4264Target = (fun i => ([false,true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event4264Target i = (fun i => ([false,true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4264_inventory_basis_column : event4264Target = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event4264Target i = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨1,by decide⟩) i from by decide) i
theorem event4265_source_recursive : event4265Source = (fun i => ([false,false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event4265Source i = (fun i => ([false,false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4265_target_recursive : event4265Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4265Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4265_inventory_basis_column : event4265Source = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨2,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event4265Source i = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨2,by decide⟩) i from by decide) i
theorem event4266_source_recursive : event4266Source = (fun i => ([true,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 4, event4266Source i = (fun i => ([true,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4266_target_recursive : event4266Target = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4266Target i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4266_inventory_basis_column : event4266Source = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨3,by decide⟩) := by funext i; exact (show ∀ i : Fin 4, event4266Source i = (fun i => AggregateTargetInventory.Bases.f28.basis i ⟨3,by decide⟩) i from by decide) i
theorem event4337_source_recursive : event4337Source = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 5, event4337Source i = (fun i => ([true,false,false,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4337_target_recursive : event4337Target = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4337Target i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4337_inventory_basis_column : event4337Target = (fun i => AggregateTargetInventory.Bases.f29.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event4337Target i = (fun i => AggregateTargetInventory.Bases.f29.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4338_source_recursive : event4338Source = (eval b_S0_29_154_d2.comparison.projection (fun i => ([false,true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event4338Source i = (eval b_S0_29_154_d2.comparison.projection (fun i => ([false,true] : List Bool)[i.val]!)) i from by decide) i
theorem event4338_target_recursive : event4338Target = (eval b_S0_32_156_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event4338Target i = (eval b_S0_32_156_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event4338_inventory_basis_column : event4338Source = (eval b_S0_29_154_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f29.basis i ⟨1,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event4338Source i = (eval b_S0_29_154_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f29.basis i ⟨1,by decide⟩)) i from by decide) i
theorem event4411_source_recursive : event4411Source = (fun i => ([true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event4411Source i = (fun i => ([true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4411_target_recursive : event4411Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4411Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4411_inventory_basis_column : event4411Target = (fun i => AggregateTargetInventory.Bases.f30.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event4411Target i = (fun i => AggregateTargetInventory.Bases.f30.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4412_source_recursive : event4412Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4412Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4412_target_recursive : event4412Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4412Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4412_inventory_basis_column : event4412Source = (fun i => AggregateTargetInventory.Bases.f30.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event4412Source i = (fun i => AggregateTargetInventory.Bases.f30.basis i ⟨1,by decide⟩) i from by decide) i
theorem event4501_source_recursive : event4501Source = (fun i => ([true,false,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event4501Source i = (fun i => ([true,false,false] : List Bool)[i.val]!) i from by decide) i
theorem event4501_target_recursive : event4501Target = (fun i => ([false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event4501Target i = (fun i => ([false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4501_inventory_basis_column : event4501Target = (fun i => AggregateTargetInventory.Bases.f31.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event4501Target i = (fun i => AggregateTargetInventory.Bases.f31.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4502_source_recursive : event4502Source = (fun i => ([false,true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event4502Source i = (fun i => ([false,true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4502_target_recursive : event4502Target = (fun i => ([false,false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 3, event4502Target i = (fun i => ([false,false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4502_inventory_basis_column : event4502Target = (fun i => AggregateTargetInventory.Bases.f31.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 3, event4502Target i = (fun i => AggregateTargetInventory.Bases.f31.basis i ⟨1,by decide⟩) i from by decide) i
theorem event4503_source_recursive : event4503Source = (eval b_S0_31_156_d3.comparison.projection (eval b_S0_31_156_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event4503Source i = (eval b_S0_31_156_d3.comparison.projection (eval b_S0_31_156_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!))) i from by decide) i
theorem event4503_target_recursive : event4503Target = (eval b_S0_35_159_d3.comparison.projection (eval b_S0_35_159_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event4503Target i = (eval b_S0_35_159_d3.comparison.projection (eval b_S0_35_159_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) i from by decide) i
theorem event4503_inventory_basis_column : event4503Source = (eval b_S0_31_156_d3.comparison.projection (eval b_S0_31_156_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f31.basis i ⟨2,by decide⟩))) := by funext i; exact (show ∀ i : Fin 1, event4503Source i = (eval b_S0_31_156_d3.comparison.projection (eval b_S0_31_156_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f31.basis i ⟨2,by decide⟩))) i from by decide) i
theorem event4671_source_recursive : event4671Source = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event4671Source i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event4671_target_recursive : event4671Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4671Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4671_inventory_basis_column : event4671Source = (fun i => AggregateTargetInventory.Bases.f33.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 1, event4671Source i = (fun i => AggregateTargetInventory.Bases.f33.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4763_source_recursive : event4763Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4763Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4763_target_recursive : event4763Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4763Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4763_inventory_basis_column : event4763Target = (fun i => AggregateTargetInventory.Bases.f34.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event4763Target i = (fun i => AggregateTargetInventory.Bases.f34.basis i ⟨0,by decide⟩) i from by decide) i
theorem event4764_source_recursive : event4764Source = (eval b_S0_31_157_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event4764Source i = (eval b_S0_31_157_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event4764_target_recursive : event4764Target = (eval b_S0_34_159_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event4764Target i = (eval b_S0_34_159_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event4764_inventory_basis_column : event4764Target = (eval b_S0_34_159_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f34.basis i ⟨1,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event4764Target i = (eval b_S0_34_159_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f34.basis i ⟨1,by decide⟩)) i from by decide) i
theorem event4929_source_recursive : event4929Source = (eval b_S0_33_159_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event4929Source i = (eval b_S0_33_159_d2.comparison.projection (fun i => ([true,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event4929_target_recursive : event4929Target = (eval b_S0_36_161_d2.comparison.projection (fun i => ([false,true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event4929Target i = (eval b_S0_36_161_d2.comparison.projection (fun i => ([false,true] : List Bool)[i.val]!)) i from by decide) i
theorem event4929_inventory_basis_column : event4929Target = (eval b_S0_36_161_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f36.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event4929Target i = (eval b_S0_36_161_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f36.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event4930_source_recursive : event4930Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4930Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event4930_target_recursive : event4930Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event4930Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event4930_inventory_basis_column : event4930Source = (fun i => AggregateTargetInventory.Bases.f36.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event4930Source i = (fun i => AggregateTargetInventory.Bases.f36.basis i ⟨1,by decide⟩) i from by decide) i
theorem event5027_source_recursive : event5027Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5027Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event5027_target_recursive : event5027Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5027Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event5027_inventory_basis_column : event5027Target = (fun i => AggregateTargetInventory.Bases.f37.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event5027Target i = (fun i => AggregateTargetInventory.Bases.f37.basis i ⟨0,by decide⟩) i from by decide) i
theorem event5028_source_recursive : event5028Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5028Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event5028_target_recursive : event5028Target = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event5028Target i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event5028_inventory_basis_column : event5028Source = (fun i => AggregateTargetInventory.Bases.f37.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event5028Source i = (fun i => AggregateTargetInventory.Bases.f37.basis i ⟨1,by decide⟩) i from by decide) i
theorem event5143_source_recursive : event5143Source = (eval b_S0_38_163_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event5143Source i = (eval b_S0_38_163_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!)) i from by decide) i
theorem event5143_target_recursive : event5143Target = (eval b_S0_41_165_d2.comparison.projection (fun i => ([false,true,true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 2, event5143Target i = (eval b_S0_41_165_d2.comparison.projection (fun i => ([false,true,true] : List Bool)[i.val]!)) i from by decide) i
theorem event5143_inventory_basis_column : event5143Source = (eval b_S0_38_163_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f38.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event5143Source i = (eval b_S0_38_163_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f38.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event5217_source_recursive : event5217Source = (eval b_S0_39_164_d3.comparison.projection (eval b_S0_39_164_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event5217Source i = (eval b_S0_39_164_d3.comparison.projection (eval b_S0_39_164_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) i from by decide) i
theorem event5217_target_recursive : event5217Target = (eval b_S0_43_167_d3.comparison.projection (eval b_S0_43_167_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event5217Target i = (eval b_S0_43_167_d3.comparison.projection (eval b_S0_43_167_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) i from by decide) i
theorem event5217_inventory_basis_column : event5217Source = (eval b_S0_39_164_d3.comparison.projection (eval b_S0_39_164_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f39.basis i ⟨0,by decide⟩))) := by funext i; exact (show ∀ i : Fin 1, event5217Source i = (eval b_S0_39_164_d3.comparison.projection (eval b_S0_39_164_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f39.basis i ⟨0,by decide⟩))) i from by decide) i
theorem event5326_source_recursive : event5326Source = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event5326Source i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event5326_target_recursive : event5326Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5326Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event5326_inventory_basis_column : event5326Target = (fun i => AggregateTargetInventory.Bases.f40.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event5326Target i = (fun i => AggregateTargetInventory.Bases.f40.basis i ⟨0,by decide⟩) i from by decide) i
theorem event5327_source_recursive : event5327Source = (fun i => ([true,false] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5327Source i = (fun i => ([true,false] : List Bool)[i.val]!) i from by decide) i
theorem event5327_target_recursive : event5327Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5327Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event5327_inventory_basis_column : event5327Source = (fun i => AggregateTargetInventory.Bases.f40.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event5327Source i = (fun i => AggregateTargetInventory.Bases.f40.basis i ⟨1,by decide⟩) i from by decide) i
theorem event5441_source_recursive : event5441Source = (eval b_S0_41_166_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event5441Source i = (eval b_S0_41_166_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event5441_target_recursive : event5441Target = (eval b_S0_44_168_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event5441Target i = (eval b_S0_44_168_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!)) i from by decide) i
theorem event5441_inventory_basis_column : event5441Source = (eval b_S0_41_166_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f41.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event5441Source i = (eval b_S0_41_166_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f41.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event5442_source_recursive : event5442Source = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5442Source i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event5442_target_recursive : event5442Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5442Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event5442_inventory_basis_column : event5442Source = (fun i => AggregateTargetInventory.Bases.f41.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event5442Source i = (fun i => AggregateTargetInventory.Bases.f41.basis i ⟨1,by decide⟩) i from by decide) i
theorem event5540_source_recursive : event5540Source = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event5540Source i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event5540_target_recursive : event5540Target = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5540Target i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event5540_inventory_basis_column : event5540Source = (fun i => AggregateTargetInventory.Bases.f42.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 1, event5540Source i = (fun i => AggregateTargetInventory.Bases.f42.basis i ⟨0,by decide⟩) i from by decide) i
theorem event5635_source_recursive : event5635Source = (eval b_S0_43_168_d3.comparison.projection (eval b_S0_43_168_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event5635Source i = (eval b_S0_43_168_d3.comparison.projection (eval b_S0_43_168_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) i from by decide) i
theorem event5635_target_recursive : event5635Target = (eval b_S0_47_171_d3.comparison.projection (eval b_S0_47_171_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event5635Target i = (eval b_S0_47_171_d3.comparison.projection (eval b_S0_47_171_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) i from by decide) i
theorem event5635_inventory_basis_column : event5635Source = (eval b_S0_43_168_d3.comparison.projection (eval b_S0_43_168_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f43.basis i ⟨0,by decide⟩))) := by funext i; exact (show ∀ i : Fin 1, event5635Source i = (eval b_S0_43_168_d3.comparison.projection (eval b_S0_43_168_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f43.basis i ⟨0,by decide⟩))) i from by decide) i
theorem event5636_source_recursive : event5636Source = (fun i => ([false,true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 2, event5636Source i = (fun i => ([false,true] : List Bool)[i.val]!) i from by decide) i
theorem event5636_target_recursive : event5636Target = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event5636Target i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event5636_inventory_basis_column : event5636Source = (fun i => AggregateTargetInventory.Bases.f43.basis i ⟨1,by decide⟩) := by funext i; exact (show ∀ i : Fin 2, event5636Source i = (fun i => AggregateTargetInventory.Bases.f43.basis i ⟨1,by decide⟩) i from by decide) i
theorem event5772_source_recursive : event5772Source = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event5772Source i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event5772_target_recursive : event5772Target = (fun i => ([true] : List Bool)[i.val]!) := by funext i; exact (show ∀ i : Fin 1, event5772Target i = (fun i => ([true] : List Bool)[i.val]!) i from by decide) i
theorem event5772_inventory_basis_column : event5772Source = (fun i => AggregateTargetInventory.Bases.f44.basis i ⟨0,by decide⟩) := by funext i; exact (show ∀ i : Fin 1, event5772Source i = (fun i => AggregateTargetInventory.Bases.f44.basis i ⟨0,by decide⟩) i from by decide) i
theorem event5862_source_recursive : event5862Source = (eval b_S0_42_168_d2.comparison.projection (fun i => ([true,false,false,false] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 3, event5862Source i = (eval b_S0_42_168_d2.comparison.projection (fun i => ([true,false,false,false] : List Bool)[i.val]!)) i from by decide) i
theorem event5862_target_recursive : event5862Target = (eval b_S0_45_170_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!)) := by funext i; exact (show ∀ i : Fin 1, event5862Target i = (eval b_S0_45_170_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!)) i from by decide) i
theorem event5862_inventory_basis_column : event5862Target = (eval b_S0_45_170_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f45.basis i ⟨0,by decide⟩)) := by funext i; exact (show ∀ i : Fin 1, event5862Target i = (eval b_S0_45_170_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f45.basis i ⟨0,by decide⟩)) i from by decide) i
theorem event5977_source_recursive : event5977Source = (eval b_S0_42_168_d3.comparison.projection (eval b_S0_42_168_d2.comparison.projection (fun i => ([false,false,true,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event5977Source i = (eval b_S0_42_168_d3.comparison.projection (eval b_S0_42_168_d2.comparison.projection (fun i => ([false,false,true,false] : List Bool)[i.val]!))) i from by decide) i
theorem event5977_target_recursive : event5977Target = (eval b_S0_46_171_d3.comparison.projection (eval b_S0_46_171_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event5977Target i = (eval b_S0_46_171_d3.comparison.projection (eval b_S0_46_171_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) i from by decide) i
theorem event5977_inventory_basis_column : event5977Target = (eval b_S0_46_171_d3.comparison.projection (eval b_S0_46_171_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f46.basis i ⟨0,by decide⟩))) := by funext i; exact (show ∀ i : Fin 1, event5977Target i = (eval b_S0_46_171_d3.comparison.projection (eval b_S0_46_171_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f46.basis i ⟨0,by decide⟩))) i from by decide) i
theorem event6296_source_recursive : event6296Source = (eval b_S0_45_171_d3.comparison.projection (eval b_S0_45_171_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 2, event6296Source i = (eval b_S0_45_171_d3.comparison.projection (eval b_S0_45_171_d2.comparison.projection (fun i => ([true,false] : List Bool)[i.val]!))) i from by decide) i
theorem event6296_target_recursive : event6296Target = (eval b_S0_49_174_d3.comparison.projection (eval b_S0_49_174_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) := by funext i; exact (show ∀ i : Fin 1, event6296Target i = (eval b_S0_49_174_d3.comparison.projection (eval b_S0_49_174_d2.comparison.projection (fun i => ([true] : List Bool)[i.val]!))) i from by decide) i
theorem event6296_inventory_basis_column : event6296Target = (eval b_S0_49_174_d3.comparison.projection (eval b_S0_49_174_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f49.basis i ⟨0,by decide⟩))) := by funext i; exact (show ∀ i : Fin 1, event6296Target i = (eval b_S0_49_174_d3.comparison.projection (eval b_S0_49_174_d2.comparison.projection (fun i => AggregateTargetInventory.Bases.f49.basis i ⟨0,by decide⟩))) i from by decide) i
end AggregateTargetInventory.EventAudit.CoordinateLinks
