import StaircaseCertificates.Import
namespace StaircaseCertificates.Release45
open LinProgramCertificates
def c4500 : Wire := ⟨1, "Joker", 15, 138, 4, [false, false, false, true, false, true, false, false, false, false, true, false, true, false, false, false], [false, false, false, true, false, true, false, false, false, false, true, false, true, false, false, false], [2, 9994, 9997, 9998], [false, true, false, false]⟩
theorem basis4500 : IsBasis c4500.certificate := by lin_cert using ()
def c4501 : Wire := ⟨1, "Joker", 15, 139, 4, [false, false, false, true, false, false, true, false, false, true, false, false, true, false, false, false], [false, false, false, true, false, false, true, false, false, true, false, false, true, false, false, false], [2, 3, 9997, 9998], [false, false, false, true]⟩
theorem basis4501 : IsBasis c4501.certificate := by lin_cert using ()
def c4502 : Wire := ⟨1, "Joker", 15, 140, 4, [false, true, false, false, false, false, false, true, false, true, true, false, true, false, false, false], [false, false, false, true, true, false, false, false, true, false, true, false, false, true, false, false], [2, 5, 9000, 9997], [false, false, true, false]⟩
theorem basis4502 : IsBasis c4502.certificate := by lin_cert using ()
def c4503 : Wire := ⟨1, "Joker", 15, 141, 5, [true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, true], [true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, true, false, false, true], [5, 9000, 9995, 9998, 9998], [false, true, true, false, false]⟩
theorem basis4503 : IsBasis c4503.certificate := by lin_cert using ()
def c4504 : Wire := ⟨1, "Joker", 15, 142, 5, [false, false, false, true, false, false, false, false, true, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, true, true, false, false, false], [2, 9997, 9998, 9998, 9998], [false, true, false, false, true]⟩
theorem basis4504 : IsBasis c4504.certificate := by lin_cert using ()
def c4505 : Wire := ⟨1, "Joker", 16, 138, 4, [false, false, true, false, false, false, false, true, false, true, false, false, true, false, false, false], [false, false, false, true, false, false, true, false, true, false, false, false, false, true, false, false], [3, 9000, 9000, 9998], [false, true, true, false]⟩
theorem basis4505 : IsBasis c4505.certificate := by lin_cert using ()
def c4506 : Wire := ⟨1, "Joker", 16, 139, 5, [false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false], [false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false], [3, 9000, 9995, 9995, 9998], [false, true, true, true, false]⟩
theorem basis4506 : IsBasis c4506.certificate := by lin_cert using ()
def c4507 : Wire := ⟨1, "Joker", 16, 140, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [4, 9000, 9998], [false, true, false]⟩
theorem basis4507 : IsBasis c4507.certificate := by lin_cert using ()
def c4508 : Wire := ⟨1, "Joker", 16, 141, 5, [false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false, false, true, false, false, true], [false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, true], [2, 9000, 9000, 9992, 9992], [false, true, true, true, true]⟩
theorem basis4508 : IsBasis c4508.certificate := by lin_cert using ()
def c4509 : Wire := ⟨1, "Joker", 16, 142, 8, [false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true, false], [2, 2, 9000, 9000, 9994, 9994, 9996, 9998], [false, false, true, true, true, true, true, false]⟩
theorem basis4509 : IsBasis c4509.certificate := by lin_cert using ()
def c4510 : Wire := ⟨1, "Joker", 16, 143, 5, [false, false, false, false, true, true, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false], [false, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, true, false, false, false, false], [2, 9000, 9997, 9998, 9998], [false, true, false, false, false]⟩
theorem basis4510 : IsBasis c4510.certificate := by lin_cert using ()
def c4511 : Wire := ⟨1, "Joker", 17, 139, 7, [false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false], [false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false], [2, 3, 9000, 9000, 9000, 9000, 9998], [false, false, true, true, true, true, false]⟩
theorem basis4511 : IsBasis c4511.certificate := by lin_cert using ()
def c4512 : Wire := ⟨1, "Joker", 17, 140, 4, [false, false, false, true, false, true, false, false, false, false, true, false, true, false, false, false], [false, false, false, true, false, true, false, false, false, false, true, false, true, false, false, false], [3, 3, 9998, 9998], [false, false, false, false]⟩
theorem basis4512 : IsBasis c4512.certificate := by lin_cert using ()
def c4513 : Wire := ⟨1, "Joker", 17, 141, 4, [false, false, false, true, false, true, false, false, true, false, false, false, false, false, true, false], [false, false, true, false, false, true, false, false, false, false, false, true, true, false, false, false], [3, 3, 9000, 9997], [false, false, true, false]⟩
theorem basis4513 : IsBasis c4513.certificate := by lin_cert using ()
def c4514 : Wire := ⟨1, "Joker", 17, 142, 7, [false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, true, true, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, true, true, false, false, true, false, false, false, false, false, false], [2, 2, 3, 9993, 9996, 9997, 9998], [false, false, false, true, false, false, false]⟩
theorem basis4514 : IsBasis c4514.certificate := by lin_cert using ()
def c4515 : Wire := ⟨1, "Joker", 17, 143, 5, [false, false, false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, true, false, false, false], [false, false, true, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, false, false, false], [2, 2, 3, 9998, 9998], [false, false, false, false, false]⟩
theorem basis4515 : IsBasis c4515.certificate := by lin_cert using ()
def c4516 : Wire := ⟨1, "Joker", 17, 144, 5, [true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, true, false, false, false], [true, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false], [2, 3, 9992, 9992, 9998], [false, false, true, true, false]⟩
theorem basis4516 : IsBasis c4516.certificate := by lin_cert using ()
def c4517 : Wire := ⟨1, "Joker", 18, 140, 6, [false, false, false, true, false, false, false, false, false, true, true, false, false, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, false, false, false, true, false, false], [2, 3, 9000, 9997, 9997, 9998], [false, false, true, false, false, false]⟩
theorem basis4517 : IsBasis c4517.certificate := by lin_cert using ()
def c4518 : Wire := ⟨1, "Joker", 18, 141, 5, [false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true], [false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, true], [2, 3, 9998, 9998, 9998], [false, false, false, false, false]⟩
theorem basis4518 : IsBasis c4518.certificate := by lin_cert using ()
def c4519 : Wire := ⟨1, "Joker", 18, 142, 2, [false, true, true, false], [false, true, true, false], [3, 9000], [false, true]⟩
theorem basis4519 : IsBasis c4519.certificate := by lin_cert using ()
def c4520 : Wire := ⟨1, "Joker", 18, 143, 3, [false, true, false, false, true, true, true, false, false], [false, false, true, true, false, false, true, true, false], [2, 9997, 9998], [false, false, false]⟩
theorem basis4520 : IsBasis c4520.certificate := by lin_cert using ()
def c4521 : Wire := ⟨1, "Joker", 18, 144, 5, [false, true, false, false, false, true, false, false, false, false, true, true, false, false, true, false, false, false, true, false, false, false, true, false, false], [false, true, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, true, false, true, true, true, false, false], [2, 2, 4, 9000, 9997], [false, false, false, true, false]⟩
theorem basis4521 : IsBasis c4521.certificate := by lin_cert using ()
def c4522 : Wire := ⟨1, "Joker", 18, 145, 5, [true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, true, true, false, false, false], [true, false, false, false, false, true, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false], [2, 3, 9000, 9996, 9998], [false, false, true, false, false]⟩
theorem basis4522 : IsBasis c4522.certificate := by lin_cert using ()
def c4523 : Wire := ⟨1, "Joker", 19, 141, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [2, 2, 9997], [false, false, false]⟩
theorem basis4523 : IsBasis c4523.certificate := by lin_cert using ()
def c4524 : Wire := ⟨1, "Joker", 19, 142, 2, [true, false, false, true], [true, false, false, true], [9000, 9998], [true, false]⟩
theorem basis4524 : IsBasis c4524.certificate := by lin_cert using ()
def c4525 : Wire := ⟨1, "Joker", 19, 143, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 9996, 9998], [false, false, false]⟩
theorem basis4525 : IsBasis c4525.certificate := by lin_cert using ()
def c4526 : Wire := ⟨1, "Joker", 19, 144, 4, [false, true, false, false, false, false, false, true, true, false, false, false, false, false, true, false], [false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, false], [2, 2, 9997, 9997], [false, false, false, false]⟩
theorem basis4526 : IsBasis c4526.certificate := by lin_cert using ()
def c4527 : Wire := ⟨1, "Joker", 19, 145, 5, [false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false], [false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false], [2, 3, 9997, 9997, 9997], [false, false, false, false, true]⟩
theorem basis4527 : IsBasis c4527.certificate := by lin_cert using ()
def c4528 : Wire := ⟨1, "Joker", 19, 146, 6, [false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, true, false, true, true, false, false, false, false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, true, false, true, true, false, false], [3, 9000, 9997, 9997, 9998, 9998], [false, true, false, false, false, false]⟩
theorem basis4528 : IsBasis c4528.certificate := by lin_cert using ()
def c4529 : Wire := ⟨1, "Joker", 20, 142, 5, [false, false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false], [false, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false], [2, 2, 2, 9000, 9998], [false, false, false, true, false]⟩
theorem basis4529 : IsBasis c4529.certificate := by lin_cert using ()
def c4530 : Wire := ⟨1, "Joker", 20, 143, 4, [true, false, false, false, false, true, false, false, true, false, true, false, false, false, false, true], [true, false, false, false, false, true, false, false, true, false, true, false, false, false, false, true], [3, 9000, 9000, 9998], [false, true, true, false]⟩
theorem basis4530 : IsBasis c4530.certificate := by lin_cert using ()
def c4531 : Wire := ⟨1, "Joker", 20, 144, 5, [false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false], [false, false, false, false, true, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false], [2, 3, 9000, 9997, 9997], [false, false, true, false, true]⟩
theorem basis4531 : IsBasis c4531.certificate := by lin_cert using ()
def c4532 : Wire := ⟨1, "Joker", 20, 145, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [9995, 9995, 9997], [false, true, false]⟩
theorem basis4532 : IsBasis c4532.certificate := by lin_cert using ()
def c4533 : Wire := ⟨1, "Joker", 20, 146, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 9996, 9997], [false, false, false]⟩
theorem basis4533 : IsBasis c4533.certificate := by lin_cert using ()
def c4534 : Wire := ⟨1, "Joker", 20, 147, 2, [true, false, false, true], [true, false, false, true], [9995, 9998], [true, false]⟩
theorem basis4534 : IsBasis c4534.certificate := by lin_cert using ()
def c4535 : Wire := ⟨1, "Joker", 21, 143, 4, [false, false, true, false, false, false, false, true, false, true, false, false, true, false, false, false], [false, false, false, true, false, false, true, false, true, false, false, false, false, true, false, false], [2, 9000, 9997, 9998], [false, true, false, false]⟩
theorem basis4535 : IsBasis c4535.certificate := by lin_cert using ()
def c4536 : Wire := ⟨1, "Joker", 21, 144, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 9998, 9998], [false, false, false]⟩
theorem basis4536 : IsBasis c4536.certificate := by lin_cert using ()
def c4537 : Wire := ⟨1, "Joker", 21, 145, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [3, 4, 9998], [false, false, false]⟩
theorem basis4537 : IsBasis c4537.certificate := by lin_cert using ()
def c4538 : Wire := ⟨1, "Joker", 21, 146, 1, [true], [true], [3], [false]⟩
theorem basis4538 : IsBasis c4538.certificate := by lin_cert using ()
def c4539 : Wire := ⟨1, "Joker", 21, 147, 2, [false, true, true, false], [false, true, true, false], [2, 2], [false, false]⟩
theorem basis4539 : IsBasis c4539.certificate := by lin_cert using ()
def c4540 : Wire := ⟨1, "Joker", 21, 148, 5, [false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false], [false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false], [2, 9000, 9998, 9998, 9998], [false, true, false, false, false]⟩
theorem basis4540 : IsBasis c4540.certificate := by lin_cert using ()
def c4541 : Wire := ⟨1, "Joker", 22, 144, 1, [true], [true], [2], [false]⟩
theorem basis4541 : IsBasis c4541.certificate := by lin_cert using ()
def c4542 : Wire := ⟨1, "Joker", 22, 145, 2, [false, true, true, false], [false, true, true, false], [9000, 9998], [true, false]⟩
theorem basis4542 : IsBasis c4542.certificate := by lin_cert using ()
def c4543 : Wire := ⟨1, "Joker", 22, 146, 4, [false, false, true, false, false, true, false, false, false, false, true, true, true, false, false, false], [false, false, false, true, false, true, false, false, true, false, false, false, true, false, true, false], [3, 3, 9000, 9998], [false, false, true, false]⟩
theorem basis4543 : IsBasis c4543.certificate := by lin_cert using ()
def c4544 : Wire := ⟨1, "Joker", 22, 147, 4, [false, false, false, true, false, false, true, false, true, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, true, false, true, false, false, true, false, false, false], [3, 3, 3, 9000], [false, false, true, true]⟩
theorem basis4544 : IsBasis c4544.certificate := by lin_cert using ()
def c4545 : Wire := ⟨1, "Joker", 22, 148, 6, [false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false], [2, 3, 3, 4, 9997, 9998], [false, false, false, false, false, false]⟩
theorem basis4545 : IsBasis c4545.certificate := by lin_cert using ()
def c4546 : Wire := ⟨1, "Joker", 22, 149, 5, [false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, true, true, false, false], [false, true, false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, true, false, true, false, false, false, false], [4, 9996, 9998, 9998, 9998], [false, false, false, false, false]⟩
theorem basis4546 : IsBasis c4546.certificate := by lin_cert using ()
def c4547 : Wire := ⟨1, "Joker", 23, 145, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 2, 9998], [false, false, false]⟩
theorem basis4547 : IsBasis c4547.certificate := by lin_cert using ()
def c4548 : Wire := ⟨1, "Joker", 23, 146, 6, [false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, false, false], [false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, true, false, false, false], [2, 3, 4, 9000, 9000, 9998], [false, false, false, true, true, false]⟩
theorem basis4548 : IsBasis c4548.certificate := by lin_cert using ()
def c4549 : Wire := ⟨1, "Joker", 23, 147, 3, [true, false, false, false, true, false, false, false, true], [true, false, false, false, true, false, false, false, true], [3, 9000, 9997], [false, true, false]⟩
theorem basis4549 : IsBasis c4549.certificate := by lin_cert using ()
def c4550 : Wire := ⟨1, "Joker", 23, 148, 2, [true, false, false, true], [true, false, false, true], [3, 9998], [false, false]⟩
theorem basis4550 : IsBasis c4550.certificate := by lin_cert using ()
def c4551 : Wire := ⟨1, "Joker", 23, 149, 5, [false, false, true, false, false, false, false, false, false, true, false, false, true, true, false, true, false, false, false, false, false, true, false, false, false], [false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, true, false, true, false, false, false, true, false, false, false], [2, 2, 2, 9996, 9998], [false, false, false, false, false]⟩
theorem basis4551 : IsBasis c4551.certificate := by lin_cert using ()
def c4552 : Wire := ⟨1, "Joker", 23, 150, 2, [false, true, true, false], [false, true, true, false], [3, 9997], [false, false]⟩
theorem basis4552 : IsBasis c4552.certificate := by lin_cert using ()
def c4553 : Wire := ⟨1, "Joker", 24, 146, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [2, 9000, 9997], [false, true, false]⟩
theorem basis4553 : IsBasis c4553.certificate := by lin_cert using ()
def c4554 : Wire := ⟨1, "Joker", 24, 147, 2, [false, true, true, false], [false, true, true, false], [2, 9997], [false, false]⟩
theorem basis4554 : IsBasis c4554.certificate := by lin_cert using ()
def c4555 : Wire := ⟨1, "Joker", 24, 148, 2, [false, true, true, false], [false, true, true, false], [9000, 9998], [true, false]⟩
theorem basis4555 : IsBasis c4555.certificate := by lin_cert using ()
def c4556 : Wire := ⟨1, "Joker", 24, 149, 2, [false, true, true, false], [false, true, true, false], [2, 4], [false, false]⟩
theorem basis4556 : IsBasis c4556.certificate := by lin_cert using ()
def c4557 : Wire := ⟨1, "Joker", 24, 150, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [2, 2, 2], [false, false, false]⟩
theorem basis4557 : IsBasis c4557.certificate := by lin_cert using ()
def c4558 : Wire := ⟨1, "Joker", 24, 151, 2, [false, true, true, false], [false, true, true, false], [2, 9998], [false, false]⟩
theorem basis4558 : IsBasis c4558.certificate := by lin_cert using ()
def c4559 : Wire := ⟨1, "Joker", 25, 147, 1, [true], [true], [2], [false]⟩
theorem basis4559 : IsBasis c4559.certificate := by lin_cert using ()
def c4560 : Wire := ⟨1, "Joker", 25, 148, 2, [false, true, true, false], [false, true, true, false], [9997, 9998], [false, false]⟩
theorem basis4560 : IsBasis c4560.certificate := by lin_cert using ()
def c4561 : Wire := ⟨1, "Joker", 25, 149, 2, [true, false, false, true], [true, false, false, true], [2, 5], [false, false]⟩
theorem basis4561 : IsBasis c4561.certificate := by lin_cert using ()
def c4562 : Wire := ⟨1, "Joker", 25, 150, 2, [true, false, false, true], [true, false, false, true], [2, 3], [false, false]⟩
theorem basis4562 : IsBasis c4562.certificate := by lin_cert using ()
def c4563 : Wire := ⟨1, "Joker", 25, 151, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [9000, 9998, 9998], [true, false, false]⟩
theorem basis4563 : IsBasis c4563.certificate := by lin_cert using ()
def c4564 : Wire := ⟨1, "Joker", 25, 152, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [4, 9996, 9998], [false, false, false]⟩
theorem basis4564 : IsBasis c4564.certificate := by lin_cert using ()
def c4565 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 1, 128, 1, [true], [true], [9993], [true]⟩
theorem basis4565 : IsBasis c4565.certificate := by lin_cert using ()
def c4566 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 2, 128, 1, [true], [true], [9000], [true]⟩
theorem basis4566 : IsBasis c4566.certificate := by lin_cert using ()
def c4567 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 4, 130, 1, [true], [true], [9993], [true]⟩
theorem basis4567 : IsBasis c4567.certificate := by lin_cert using ()
def c4568 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 4, 131, 1, [true], [true], [9997], [false]⟩
theorem basis4568 : IsBasis c4568.certificate := by lin_cert using ()
def c4569 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 5, 130, 1, [true], [true], [9995], [true]⟩
theorem basis4569 : IsBasis c4569.certificate := by lin_cert using ()
def c4570 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 5, 132, 1, [true], [true], [9995], [true]⟩
theorem basis4570 : IsBasis c4570.certificate := by lin_cert using ()
def c4571 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 6, 130, 1, [true], [true], [9995], [false]⟩
theorem basis4571 : IsBasis c4571.certificate := by lin_cert using ()
def c4572 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 6, 131, 1, [true], [true], [9993], [true]⟩
theorem basis4572 : IsBasis c4572.certificate := by lin_cert using ()
def c4573 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 6, 132, 3, [true, false, false, true, true, false, true, false, true], [true, false, false, true, true, false, true, false, true], [9996, 9997, 9997], [true, false, false]⟩
theorem basis4573 : IsBasis c4573.certificate := by lin_cert using ()
def c4574 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 6, 133, 2, [false, true, true, false], [false, true, true, false], [2, 9997], [false, true]⟩
theorem basis4574 : IsBasis c4574.certificate := by lin_cert using ()
def c4575 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 7, 129, 2, [true, false, false, true], [true, false, false, true], [9996, 9997], [true, false]⟩
theorem basis4575 : IsBasis c4575.certificate := by lin_cert using ()
def c4576 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 7, 130, 1, [true], [true], [9995], [true]⟩
theorem basis4576 : IsBasis c4576.certificate := by lin_cert using ()
def c4577 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 7, 131, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [9987, 9997, 9998], [true, false, false]⟩
theorem basis4577 : IsBasis c4577.certificate := by lin_cert using ()
def c4578 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 7, 132, 3, [true, false, false, false, true, false, false, true, true], [true, false, false, false, true, false, false, true, true], [9996, 9997, 9998], [true, false, false]⟩
theorem basis4578 : IsBasis c4578.certificate := by lin_cert using ()
def c4579 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 7, 133, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [3, 9998, 9998], [false, false, false]⟩
theorem basis4579 : IsBasis c4579.certificate := by lin_cert using ()
def c4580 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 7, 134, 4, [false, false, false, true, true, false, false, false, false, true, false, false, false, true, true, false], [false, true, false, false, false, false, true, false, false, false, true, true, true, false, false, false], [9993, 9993, 9993, 9998], [true, true, true, false]⟩
theorem basis4580 : IsBasis c4580.certificate := by lin_cert using ()
def c4581 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 8, 130, 1, [true], [true], [9997], [false]⟩
theorem basis4581 : IsBasis c4581.certificate := by lin_cert using ()
def c4582 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 8, 131, 3, [false, true, false, true, false, false, true, false, true], [false, true, false, true, false, false, false, true, true], [9996, 9996, 9996], [false, true, true]⟩
theorem basis4582 : IsBasis c4582.certificate := by lin_cert using ()
def c4583 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 8, 132, 2, [false, true, true, false], [false, true, true, false], [9990, 9996], [true, true]⟩
theorem basis4583 : IsBasis c4583.certificate := by lin_cert using ()
def c4584 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 8, 133, 2, [false, true, true, false], [false, true, true, false], [9997, 9998], [false, false]⟩
theorem basis4584 : IsBasis c4584.certificate := by lin_cert using ()
def c4585 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 8, 134, 6, [false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false], [9000, 9992, 9996, 9996, 9997, 9998], [true, true, false, true, false, true]⟩
theorem basis4585 : IsBasis c4585.certificate := by lin_cert using ()
def c4586 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 8, 135, 6, [false, false, false, false, true, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, true, true, false, false, false, false], [9000, 9990, 9990, 9996, 9997, 9997], [true, true, true, false, false, false]⟩
theorem basis4586 : IsBasis c4586.certificate := by lin_cert using ()
def c4587 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 9, 131, 2, [false, true, true, false], [false, true, true, false], [9000, 9997], [true, true]⟩
theorem basis4587 : IsBasis c4587.certificate := by lin_cert using ()
def c4588 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 9, 132, 2, [false, true, true, false], [false, true, true, false], [2, 9998], [false, false]⟩
theorem basis4588 : IsBasis c4588.certificate := by lin_cert using ()
def c4589 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 9, 133, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 9997, 9998], [false, false, false]⟩
theorem basis4589 : IsBasis c4589.certificate := by lin_cert using ()
def c4590 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 9, 134, 5, [false, false, false, false, true, false, false, true, false, false, true, false, false, false, false, true, true, false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false], [2, 2, 3, 3, 9998], [false, false, false, false, false]⟩
theorem basis4590 : IsBasis c4590.certificate := by lin_cert using ()
def c4591 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 9, 135, 5, [false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, false], [false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, false], [2, 9000, 9993, 9997, 9997], [false, true, true, false, true]⟩
theorem basis4591 : IsBasis c4591.certificate := by lin_cert using ()
def c4592 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 9, 136, 6, [true, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, true, false, false, true, false, false], [true, false, false, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false, false, true, true, true, false, false, true, false, false, false, true, false, false, false], [3, 9991, 9994, 9996, 9997, 9998], [false, true, true, false, false, false]⟩
theorem basis4592 : IsBasis c4592.certificate := by lin_cert using ()
def c4593 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 10, 132, 3, [false, false, true, true, false, false, true, true, false], [false, true, false, false, true, true, true, false, false], [9993, 9996, 9997], [true, true, false]⟩
theorem basis4593 : IsBasis c4593.certificate := by lin_cert using ()
def c4594 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 10, 133, 2, [true, false, true, true], [true, false, true, true], [3, 9000], [false, true]⟩
theorem basis4594 : IsBasis c4594.certificate := by lin_cert using ()
def c4595 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 10, 134, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 3, 9992], [false, false, true]⟩
theorem basis4595 : IsBasis c4595.certificate := by lin_cert using ()
def c4596 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 10, 135, 5, [false, false, false, true, false, false, false, false, true, true, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false], [false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, false, false, false], [9000, 9995, 9996, 9996, 9996], [true, false, true, true, true]⟩
theorem basis4596 : IsBasis c4596.certificate := by lin_cert using ()
def c4597 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 10, 136, 6, [false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, true, true, false, false, false, false, false, true, false, true, false, false, false], [false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, true, false, false], [9994, 9994, 9996, 9996, 9998, 9998], [true, true, false, true, false, false]⟩
theorem basis4597 : IsBasis c4597.certificate := by lin_cert using ()
def c4598 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 10, 137, 5, [false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, true, false, false], [false, true, false, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false], [2, 2, 9992, 9995, 9998], [false, false, true, false, false]⟩
theorem basis4598 : IsBasis c4598.certificate := by lin_cert using ()
def c4599 : Wire := ⟨1, "CW_eta_2_eta_Eq_2_nu", 11, 133, 1, [true], [true], [2], [false]⟩
theorem basis4599 : IsBasis c4599.certificate := by lin_cert using ()
end StaircaseCertificates.Release45
