import StaircaseCertificates.Import
namespace StaircaseCertificates.Release11
open LinProgramCertificates
def c1100 : Wire := ⟨1, "CW_nu_eta", 21, 145, 4, [false, false, false, true, false, false, true, false, true, false, false, false, true, true, false, false], [false, false, true, false, false, false, true, true, false, true, false, false, true, false, false, false], [2, 2, 4, 9000], [false, false, false, true]⟩
theorem basis1100 : IsBasis c1100.certificate := by lin_cert using ()
def c1101 : Wire := ⟨1, "CW_nu_eta", 21, 146, 5, [false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true], [false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true], [2, 3, 3, 9000, 9998], [false, false, false, true, false]⟩
theorem basis1101 : IsBasis c1101.certificate := by lin_cert using ()
def c1102 : Wire := ⟨1, "CW_nu_eta", 21, 147, 5, [false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false], [false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false], [2, 2, 3, 4, 9000], [false, false, false, false, true]⟩
theorem basis1102 : IsBasis c1102.certificate := by lin_cert using ()
def c1103 : Wire := ⟨1, "CW_nu_eta", 21, 148, 4, [false, true, false, false, false, false, false, true, true, false, false, false, false, false, true, false], [false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, false], [9000, 9996, 9997, 9998], [true, false, false, false]⟩
theorem basis1103 : IsBasis c1103.certificate := by lin_cert using ()
def c1104 : Wire := ⟨1, "CW_nu_eta", 22, 144, 2, [false, true, true, false], [false, true, true, false], [9996, 9998], [false, false]⟩
theorem basis1104 : IsBasis c1104.certificate := by lin_cert using ()
def c1105 : Wire := ⟨1, "CW_nu_eta", 22, 145, 2, [false, true, true, false], [false, true, true, false], [3, 9000], [false, true]⟩
theorem basis1105 : IsBasis c1105.certificate := by lin_cert using ()
def c1106 : Wire := ⟨1, "CW_nu_eta", 22, 146, 3, [true, false, false, false, false, true, true, true, false], [true, false, false, true, false, true, false, true, false], [2, 2, 9998], [false, false, false]⟩
theorem basis1106 : IsBasis c1106.certificate := by lin_cert using ()
def c1107 : Wire := ⟨1, "CW_nu_eta", 22, 147, 3, [false, false, true, true, false, false, true, true, false], [false, true, false, false, true, true, true, false, false], [3, 9997, 9998], [false, false, false]⟩
theorem basis1107 : IsBasis c1107.certificate := by lin_cert using ()
def c1108 : Wire := ⟨1, "CW_nu_eta", 22, 148, 5, [false, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false], [false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, true, false, false, false, true, false, false, false, false], [2, 3, 3, 9996, 9997], [false, false, false, false, false]⟩
theorem basis1108 : IsBasis c1108.certificate := by lin_cert using ()
def c1109 : Wire := ⟨1, "CW_nu_eta", 22, 149, 3, [true, false, false, true, true, false, false, false, true], [true, false, false, true, true, false, false, false, true], [2, 3, 9997], [false, false, false]⟩
theorem basis1109 : IsBasis c1109.certificate := by lin_cert using ()
def c1110 : Wire := ⟨1, "CW_nu_eta", 23, 145, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [3, 3, 9998], [false, false, false]⟩
theorem basis1110 : IsBasis c1110.certificate := by lin_cert using ()
def c1111 : Wire := ⟨1, "CW_nu_eta", 23, 147, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 9998, 9998], [false, false, false]⟩
theorem basis1111 : IsBasis c1111.certificate := by lin_cert using ()
def c1112 : Wire := ⟨1, "CW_nu_eta", 23, 148, 5, [true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false], [true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false], [3, 3, 9000, 9997, 9998], [false, false, true, false, false]⟩
theorem basis1112 : IsBasis c1112.certificate := by lin_cert using ()
def c1113 : Wire := ⟨1, "CW_nu_eta", 23, 149, 3, [true, false, false, false, false, true, false, true, false], [true, false, false, false, false, true, false, true, false], [2, 3, 3], [false, false, false]⟩
theorem basis1113 : IsBasis c1113.certificate := by lin_cert using ()
def c1114 : Wire := ⟨1, "CW_nu_eta", 23, 150, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [9997, 9998, 9998], [false, false, false]⟩
theorem basis1114 : IsBasis c1114.certificate := by lin_cert using ()
def c1115 : Wire := ⟨1, "CW_nu_eta", 24, 146, 1, [true], [true], [9997], [false]⟩
theorem basis1115 : IsBasis c1115.certificate := by lin_cert using ()
def c1116 : Wire := ⟨1, "CW_nu_eta", 24, 147, 2, [false, true, true, false], [false, true, true, false], [2, 9998], [false, false]⟩
theorem basis1116 : IsBasis c1116.certificate := by lin_cert using ()
def c1117 : Wire := ⟨1, "CW_nu_eta", 24, 148, 5, [false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, true, true, false, false, false], [false, false, false, true, false, false, false, false, true, true, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false], [2, 4, 9000, 9000, 9998], [false, false, true, true, false]⟩
theorem basis1117 : IsBasis c1117.certificate := by lin_cert using ()
def c1118 : Wire := ⟨1, "CW_nu_eta", 24, 149, 1, [true], [true], [9997], [false]⟩
theorem basis1118 : IsBasis c1118.certificate := by lin_cert using ()
def c1119 : Wire := ⟨1, "CW_nu_eta", 24, 150, 2, [false, true, true, false], [false, true, true, false], [3, 9998], [false, false]⟩
theorem basis1119 : IsBasis c1119.certificate := by lin_cert using ()
def c1120 : Wire := ⟨1, "CW_nu_eta", 24, 151, 6, [false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, false, false], [2, 2, 9996, 9997, 9998, 9998], [false, false, false, false, false, false]⟩
theorem basis1120 : IsBasis c1120.certificate := by lin_cert using ()
def c1121 : Wire := ⟨1, "CW_nu_eta", 25, 147, 1, [true], [true], [9998], [false]⟩
theorem basis1121 : IsBasis c1121.certificate := by lin_cert using ()
def c1122 : Wire := ⟨1, "CW_nu_eta", 25, 148, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 2, 9997], [false, false, false]⟩
theorem basis1122 : IsBasis c1122.certificate := by lin_cert using ()
def c1123 : Wire := ⟨1, "CW_nu_eta", 25, 149, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 3, 9997], [false, false, false]⟩
theorem basis1123 : IsBasis c1123.certificate := by lin_cert using ()
def c1124 : Wire := ⟨1, "CW_nu_eta", 25, 150, 3, [false, true, false, true, false, false, true, false, true], [false, true, false, true, false, false, false, true, true], [3, 9998, 9998], [false, false, false]⟩
theorem basis1124 : IsBasis c1124.certificate := by lin_cert using ()
def c1125 : Wire := ⟨1, "CW_nu_eta", 25, 151, 4, [false, true, false, false, false, false, false, true, true, false, false, false, false, false, true, false], [false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, false], [2, 2, 3, 4], [false, false, false, false]⟩
theorem basis1125 : IsBasis c1125.certificate := by lin_cert using ()
def c1126 : Wire := ⟨1, "CW_nu_eta", 25, 152, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 9997, 9997], [false, false, false]⟩
theorem basis1126 : IsBasis c1126.certificate := by lin_cert using ()
def c1127 : Wire := ⟨1, "CW_sigma_nu", 1, 128, 1, [true], [true], [9998], [false]⟩
theorem basis1127 : IsBasis c1127.certificate := by lin_cert using ()
def c1128 : Wire := ⟨1, "CW_sigma_nu", 2, 128, 1, [true], [true], [9993], [true]⟩
theorem basis1128 : IsBasis c1128.certificate := by lin_cert using ()
def c1129 : Wire := ⟨1, "CW_sigma_nu", 2, 129, 1, [true], [true], [9998], [false]⟩
theorem basis1129 : IsBasis c1129.certificate := by lin_cert using ()
def c1130 : Wire := ⟨1, "CW_sigma_nu", 3, 129, 1, [true], [true], [2], [false]⟩
theorem basis1130 : IsBasis c1130.certificate := by lin_cert using ()
def c1131 : Wire := ⟨1, "CW_sigma_nu", 3, 130, 2, [true, false, false, true], [true, false, false, true], [9986, 9998], [true, false]⟩
theorem basis1131 : IsBasis c1131.certificate := by lin_cert using ()
def c1132 : Wire := ⟨1, "CW_sigma_nu", 4, 130, 2, [false, true, true, false], [false, true, true, false], [2, 9997], [false, false]⟩
theorem basis1132 : IsBasis c1132.certificate := by lin_cert using ()
def c1133 : Wire := ⟨1, "CW_sigma_nu", 4, 131, 1, [true], [true], [9998], [false]⟩
theorem basis1133 : IsBasis c1133.certificate := by lin_cert using ()
def c1134 : Wire := ⟨1, "CW_sigma_nu", 5, 128, 1, [true], [true], [9998], [false]⟩
theorem basis1134 : IsBasis c1134.certificate := by lin_cert using ()
def c1135 : Wire := ⟨1, "CW_sigma_nu", 5, 130, 1, [true], [true], [9998], [false]⟩
theorem basis1135 : IsBasis c1135.certificate := by lin_cert using ()
def c1136 : Wire := ⟨1, "CW_sigma_nu", 5, 131, 1, [true], [true], [2], [false]⟩
theorem basis1136 : IsBasis c1136.certificate := by lin_cert using ()
def c1137 : Wire := ⟨1, "CW_sigma_nu", 5, 132, 1, [true], [true], [9998], [false]⟩
theorem basis1137 : IsBasis c1137.certificate := by lin_cert using ()
def c1138 : Wire := ⟨1, "CW_sigma_nu", 6, 128, 2, [true, false, false, true], [true, false, false, true], [9994, 9995], [true, true]⟩
theorem basis1138 : IsBasis c1138.certificate := by lin_cert using ()
def c1139 : Wire := ⟨1, "CW_sigma_nu", 6, 129, 1, [true], [true], [9994], [true]⟩
theorem basis1139 : IsBasis c1139.certificate := by lin_cert using ()
def c1140 : Wire := ⟨1, "CW_sigma_nu", 6, 130, 1, [true], [true], [9995], [false]⟩
theorem basis1140 : IsBasis c1140.certificate := by lin_cert using ()
def c1141 : Wire := ⟨1, "CW_sigma_nu", 6, 131, 2, [true, false, false, true], [true, false, false, true], [9995, 9996], [true, false]⟩
theorem basis1141 : IsBasis c1141.certificate := by lin_cert using ()
def c1142 : Wire := ⟨1, "CW_sigma_nu", 6, 132, 2, [false, true, true, false], [false, true, true, false], [2, 9997], [false, true]⟩
theorem basis1142 : IsBasis c1142.certificate := by lin_cert using ()
def c1143 : Wire := ⟨1, "CW_sigma_nu", 6, 133, 2, [true, false, false, true], [true, false, false, true], [9996, 9998], [true, false]⟩
theorem basis1143 : IsBasis c1143.certificate := by lin_cert using ()
def c1144 : Wire := ⟨1, "CW_sigma_nu", 7, 129, 1, [true], [true], [2], [false]⟩
theorem basis1144 : IsBasis c1144.certificate := by lin_cert using ()
def c1145 : Wire := ⟨1, "CW_sigma_nu", 7, 131, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 9995, 9997], [false, false, false]⟩
theorem basis1145 : IsBasis c1145.certificate := by lin_cert using ()
def c1146 : Wire := ⟨1, "CW_sigma_nu", 7, 132, 2, [false, true, true, false], [false, true, true, false], [3, 9996], [false, true]⟩
theorem basis1146 : IsBasis c1146.certificate := by lin_cert using ()
def c1147 : Wire := ⟨1, "CW_sigma_nu", 7, 133, 1, [true], [true], [2], [false]⟩
theorem basis1147 : IsBasis c1147.certificate := by lin_cert using ()
def c1148 : Wire := ⟨1, "CW_sigma_nu", 7, 134, 5, [false, false, true, false, false, false, false, true, true, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true], [false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, true, true, false, false, false, false, false, false, false, true], [2, 9990, 9997, 9998, 9998], [false, true, true, false, false]⟩
theorem basis1148 : IsBasis c1148.certificate := by lin_cert using ()
def c1149 : Wire := ⟨1, "CW_sigma_nu", 8, 130, 2, [false, true, true, false], [false, true, true, false], [9994, 9994], [true, true]⟩
theorem basis1149 : IsBasis c1149.certificate := by lin_cert using ()
def c1150 : Wire := ⟨1, "CW_sigma_nu", 8, 131, 1, [true], [true], [9997], [false]⟩
theorem basis1150 : IsBasis c1150.certificate := by lin_cert using ()
def c1151 : Wire := ⟨1, "CW_sigma_nu", 8, 132, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [9996, 9998, 9998], [false, false, false]⟩
theorem basis1151 : IsBasis c1151.certificate := by lin_cert using ()
def c1152 : Wire := ⟨1, "CW_sigma_nu", 8, 133, 2, [true, false, false, true], [true, false, false, true], [9993, 9998], [true, false]⟩
theorem basis1152 : IsBasis c1152.certificate := by lin_cert using ()
def c1153 : Wire := ⟨1, "CW_sigma_nu", 8, 134, 6, [false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false], [2, 9000, 9991, 9991, 9997, 9998], [false, true, true, true, false, false]⟩
theorem basis1153 : IsBasis c1153.certificate := by lin_cert using ()
def c1154 : Wire := ⟨1, "CW_sigma_nu", 8, 135, 7, [false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true], [false, false, false, true, false, false, false, false, false, false, true, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true], [2, 2, 9000, 9991, 9992, 9998, 9998], [false, false, true, true, true, false, false]⟩
theorem basis1154 : IsBasis c1154.certificate := by lin_cert using ()
def c1155 : Wire := ⟨1, "CW_sigma_nu", 9, 131, 2, [false, true, true, false], [false, true, true, false], [9000, 9997], [true, false]⟩
theorem basis1155 : IsBasis c1155.certificate := by lin_cert using ()
def c1156 : Wire := ⟨1, "CW_sigma_nu", 9, 132, 4, [true, false, false, false, false, false, false, true, false, true, false, false, false, true, true, false], [true, false, false, false, false, false, true, false, false, false, true, true, false, true, false, false], [9000, 9988, 9993, 9998], [true, true, true, false]⟩
theorem basis1156 : IsBasis c1156.certificate := by lin_cert using ()
def c1157 : Wire := ⟨1, "CW_sigma_nu", 9, 133, 3, [true, false, false, false, true, false, true, true, true], [true, false, false, false, true, false, true, true, true], [9996, 9997, 9998], [false, false, false]⟩
theorem basis1157 : IsBasis c1157.certificate := by lin_cert using ()
def c1158 : Wire := ⟨1, "CW_sigma_nu", 9, 134, 5, [false, true, false, false, false, false, true, false, true, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, true], [false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, true, true, false, false, false, true, false, false, false, true], [9000, 9990, 9992, 9997, 9997], [true, true, true, false, true]⟩
theorem basis1158 : IsBasis c1158.certificate := by lin_cert using ()
def c1159 : Wire := ⟨1, "CW_sigma_nu", 9, 135, 8, [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false], [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false], [2, 2, 9994, 9994, 9996, 9997, 9997, 9997], [false, false, true, true, false, false, false, false]⟩
theorem basis1159 : IsBasis c1159.certificate := by lin_cert using ()
def c1160 : Wire := ⟨1, "CW_sigma_nu", 9, 136, 5, [false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true], [false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true], [2, 9992, 9998, 9998, 9998], [false, true, false, false, false]⟩
theorem basis1160 : IsBasis c1160.certificate := by lin_cert using ()
def c1161 : Wire := ⟨1, "CW_sigma_nu", 10, 132, 2, [false, true, true, false], [false, true, true, false], [9993, 9998], [true, false]⟩
theorem basis1161 : IsBasis c1161.certificate := by lin_cert using ()
def c1162 : Wire := ⟨1, "CW_sigma_nu", 10, 133, 6, [false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, true, false, false, true, false, true, false, false, false, true, false, true, false, false, true, true, true, false, false, false, false], [false, true, false, false, false, false, false, true, false, false, false, true, false, true, false, true, false, false, false, true, true, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false], [2, 2, 3, 9000, 9998, 9998], [false, false, false, true, false, false]⟩
theorem basis1162 : IsBasis c1162.certificate := by lin_cert using ()
def c1163 : Wire := ⟨1, "CW_sigma_nu", 10, 134, 5, [false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true, true, true, true, false, false], [false, false, true, false, false, false, true, false, false, false, false, true, true, false, true, true, false, false, false, false, false, false, false, true, false], [2, 4, 9000, 9000, 9995], [false, false, true, true, false]⟩
theorem basis1163 : IsBasis c1163.certificate := by lin_cert using ()
def c1164 : Wire := ⟨1, "CW_sigma_nu", 10, 135, 4, [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [2, 9997, 9997, 9998], [false, false, false, false]⟩
theorem basis1164 : IsBasis c1164.certificate := by lin_cert using ()
def c1165 : Wire := ⟨1, "CW_sigma_nu", 10, 136, 7, [false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, true, false, false, false, true, false, false, false, false, false, false], [2, 2, 9000, 9995, 9995, 9998, 9998], [false, false, true, false, true, false, false]⟩
theorem basis1165 : IsBasis c1165.certificate := by lin_cert using ()
def c1166 : Wire := ⟨1, "CW_sigma_nu", 10, 137, 7, [false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, true], [false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, true, false, true, false, true, false, true, false, false, false, false, true, false, true, false, false, false, true], [9000, 9993, 9994, 9994, 9996, 9998, 9998], [true, true, true, true, false, false, false]⟩
theorem basis1166 : IsBasis c1166.certificate := by lin_cert using ()
def c1167 : Wire := ⟨1, "CW_sigma_nu", 11, 133, 4, [true, false, false, false, true, false, true, false, false, true, false, false, false, true, false, true], [true, false, false, false, false, false, true, false, true, true, false, false, false, false, true, true], [2, 3, 9000, 9000], [false, false, true, true]⟩
theorem basis1167 : IsBasis c1167.certificate := by lin_cert using ()
def c1168 : Wire := ⟨1, "CW_sigma_nu", 11, 134, 7, [false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, true, false, true, false, false, false, false, false, false], [false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, true, false, false, false, false], [2, 5, 9000, 9992, 9995, 9998, 9998], [false, false, true, true, true, false, false]⟩
theorem basis1168 : IsBasis c1168.certificate := by lin_cert using ()
def c1169 : Wire := ⟨1, "CW_sigma_nu", 11, 135, 4, [true, false, false, false, false, false, false, true, false, true, false, false, false, true, true, false], [true, false, false, false, false, false, true, false, false, false, true, true, false, true, false, false], [9000, 9992, 9997, 9998], [true, true, false, false]⟩
theorem basis1169 : IsBasis c1169.certificate := by lin_cert using ()
def c1170 : Wire := ⟨1, "CW_sigma_nu", 11, 136, 6, [false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, false], [false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false], [3, 9000, 9992, 9994, 9996, 9998], [false, true, true, true, false, false]⟩
theorem basis1170 : IsBasis c1170.certificate := by lin_cert using ()
def c1171 : Wire := ⟨1, "CW_sigma_nu", 11, 137, 7, [true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, true, true, true, true, false, false, false, false, false, true, false, true, false, false, false, false], [true, false, false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, true, false, false], [2, 2, 2, 9994, 9994, 9997, 9998], [false, false, false, true, true, false, false]⟩
theorem basis1171 : IsBasis c1171.certificate := by lin_cert using ()
def c1172 : Wire := ⟨1, "CW_sigma_nu", 11, 138, 6, [false, false, false, true, false, false, false, false, false, true, false, true, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false], [false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false], [9000, 9000, 9000, 9997, 9998, 9998], [true, true, true, false, false, false]⟩
theorem basis1172 : IsBasis c1172.certificate := by lin_cert using ()
def c1173 : Wire := ⟨1, "CW_sigma_nu", 12, 134, 4, [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [2, 2, 9000, 9000], [false, false, true, true]⟩
theorem basis1173 : IsBasis c1173.certificate := by lin_cert using ()
def c1174 : Wire := ⟨1, "CW_sigma_nu", 12, 135, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [3, 4, 5], [false, false, false]⟩
theorem basis1174 : IsBasis c1174.certificate := by lin_cert using ()
def c1175 : Wire := ⟨1, "CW_sigma_nu", 12, 136, 5, [false, false, false, true, false, false, false, false, false, true, false, true, false, false, false, true, false, false, false, false, true, false, true, false, false], [false, false, false, true, false, false, false, true, false, false, false, false, false, true, true, true, false, false, false, false, false, true, false, false, false], [2, 3, 9000, 9000, 9997], [false, false, true, true, false]⟩
theorem basis1175 : IsBasis c1175.certificate := by lin_cert using ()
def c1176 : Wire := ⟨1, "CW_sigma_nu", 12, 137, 7, [false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, true, false, false, false, true, false, false, false, false, false, false], [2, 2, 3, 3, 3, 9997, 9998], [false, false, false, false, false, false, false]⟩
theorem basis1176 : IsBasis c1176.certificate := by lin_cert using ()
def c1177 : Wire := ⟨1, "CW_sigma_nu", 12, 138, 4, [false, false, false, true, true, false, false, false, false, false, true, false, true, true, false, false], [false, true, false, false, false, true, false, true, false, false, true, false, true, false, false, false], [2, 2, 9996, 9998], [false, false, false, false]⟩
theorem basis1177 : IsBasis c1177.certificate := by lin_cert using ()
def c1178 : Wire := ⟨1, "CW_sigma_nu", 12, 139, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [2, 9993, 9998], [false, true, false]⟩
theorem basis1178 : IsBasis c1178.certificate := by lin_cert using ()
def c1179 : Wire := ⟨1, "CW_sigma_nu", 13, 135, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 2, 9997], [false, false, false]⟩
theorem basis1179 : IsBasis c1179.certificate := by lin_cert using ()
def c1180 : Wire := ⟨1, "CW_sigma_nu", 13, 136, 4, [false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false], [false, true, false, false, false, true, true, false, false, false, false, true, true, false, false, false], [2, 4, 9994, 9998], [false, false, true, false]⟩
theorem basis1180 : IsBasis c1180.certificate := by lin_cert using ()
def c1181 : Wire := ⟨1, "CW_sigma_nu", 13, 137, 4, [false, false, false, true, true, false, false, false, false, false, true, false, true, true, false, false], [false, true, false, false, false, true, false, true, false, false, true, false, true, false, false, false], [2, 3, 3, 9998], [false, false, false, false]⟩
theorem basis1181 : IsBasis c1181.certificate := by lin_cert using ()
def c1182 : Wire := ⟨1, "CW_sigma_nu", 13, 138, 3, [false, true, false, false, true, true, true, false, false], [false, false, true, true, false, false, true, true, false], [2, 4, 9998], [false, false, false]⟩
theorem basis1182 : IsBasis c1182.certificate := by lin_cert using ()
def c1183 : Wire := ⟨1, "CW_sigma_nu", 13, 139, 5, [false, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, true, true, false, false, true, false, false, false, false], [false, false, false, false, true, true, false, false, false, false, true, false, false, true, false, false, true, false, false, false, false, false, true, false, false], [2, 2, 9995, 9997, 9998], [false, false, false, false, false]⟩
theorem basis1183 : IsBasis c1183.certificate := by lin_cert using ()
def c1184 : Wire := ⟨1, "CW_sigma_nu", 13, 140, 5, [true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true], [true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true], [3, 3, 9000, 9994, 9998], [false, false, true, true, false]⟩
theorem basis1184 : IsBasis c1184.certificate := by lin_cert using ()
def c1185 : Wire := ⟨1, "CW_sigma_nu", 14, 136, 5, [false, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false], [false, false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false], [9000, 9000, 9000, 9998, 9998], [true, true, true, false, false]⟩
theorem basis1185 : IsBasis c1185.certificate := by lin_cert using ()
def c1186 : Wire := ⟨1, "CW_sigma_nu", 14, 137, 4, [false, false, false, true, false, false, true, false, false, true, false, false, true, false, false, false], [false, false, false, true, false, false, true, false, false, true, false, false, true, false, false, false], [3, 9996, 9996, 9998], [false, false, true, false]⟩
theorem basis1186 : IsBasis c1186.certificate := by lin_cert using ()
def c1187 : Wire := ⟨1, "CW_sigma_nu", 14, 138, 4, [false, false, false, true, true, false, false, false, false, false, true, false, false, true, false, false], [false, true, false, false, false, false, false, true, false, false, true, false, true, false, false, false], [2, 9000, 9996, 9997], [false, true, false, false]⟩
theorem basis1187 : IsBasis c1187.certificate := by lin_cert using ()
def c1188 : Wire := ⟨1, "CW_sigma_nu", 14, 139, 6, [false, false, true, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false], [2, 3, 9997, 9997, 9998, 9998], [false, false, false, false, false, false]⟩
theorem basis1188 : IsBasis c1188.certificate := by lin_cert using ()
def c1189 : Wire := ⟨1, "CW_sigma_nu", 14, 140, 6, [false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true, true, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false], [false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, false], [2, 3, 4, 9997, 9998, 9998], [false, false, false, false, false, false]⟩
theorem basis1189 : IsBasis c1189.certificate := by lin_cert using ()
def c1190 : Wire := ⟨1, "CW_sigma_nu", 14, 141, 2, [true, false, false, true], [true, false, false, true], [9995, 9998], [true, false]⟩
theorem basis1190 : IsBasis c1190.certificate := by lin_cert using ()
def c1191 : Wire := ⟨1, "CW_sigma_nu", 15, 137, 6, [false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false], [false, false, false, true, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, true, false, false, false], [2, 9997, 9998, 9998, 9998, 9998], [false, false, false, false, false, false]⟩
theorem basis1191 : IsBasis c1191.certificate := by lin_cert using ()
def c1192 : Wire := ⟨1, "CW_sigma_nu", 15, 138, 4, [false, false, false, true, false, true, false, false, false, false, true, false, true, false, false, false], [false, false, false, true, false, true, false, false, false, false, true, false, true, false, false, false], [2, 3, 5, 9000], [false, false, false, true]⟩
theorem basis1192 : IsBasis c1192.certificate := by lin_cert using ()
def c1193 : Wire := ⟨1, "CW_sigma_nu", 15, 139, 6, [false, false, false, false, false, true, false, true, false, false, false, false, false, true, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false], [2, 3, 4, 9000, 9000, 9000], [false, false, false, true, true, true]⟩
theorem basis1193 : IsBasis c1193.certificate := by lin_cert using ()
def c1194 : Wire := ⟨1, "CW_sigma_nu", 15, 140, 6, [false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, true], [false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, true], [2, 5, 9995, 9995, 9998, 9998], [false, false, false, true, false, false]⟩
theorem basis1194 : IsBasis c1194.certificate := by lin_cert using ()
def c1195 : Wire := ⟨1, "CW_sigma_nu", 15, 141, 2, [false, true, true, false], [false, true, true, false], [2, 9000], [false, true]⟩
theorem basis1195 : IsBasis c1195.certificate := by lin_cert using ()
def c1196 : Wire := ⟨1, "CW_sigma_nu", 15, 142, 7, [false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true], [false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true], [9000, 9995, 9995, 9997, 9997, 9997, 9998], [true, false, false, false, false, false, false]⟩
theorem basis1196 : IsBasis c1196.certificate := by lin_cert using ()
def c1197 : Wire := ⟨1, "CW_sigma_nu", 16, 138, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 9000, 9998], [false, true, false]⟩
theorem basis1197 : IsBasis c1197.certificate := by lin_cert using ()
def c1198 : Wire := ⟨1, "CW_sigma_nu", 16, 139, 2, [false, true, true, false], [false, true, true, false], [9000, 9998], [true, false]⟩
theorem basis1198 : IsBasis c1198.certificate := by lin_cert using ()
def c1199 : Wire := ⟨1, "CW_sigma_nu", 16, 140, 8, [false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false], [false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false], [2, 2, 9000, 9995, 9995, 9996, 9996, 9996], [false, false, true, false, true, false, false, true]⟩
theorem basis1199 : IsBasis c1199.certificate := by lin_cert using ()
end StaircaseCertificates.Release11
