import StaircaseCertificates.Import
namespace StaircaseCertificates.Release8
open LinProgramCertificates
def c800 : Wire := ⟨1, "CW_eta_2", 12, 138, 3, [true, false, false, false, false, true, false, true, false], [true, false, false, false, false, true, false, true, false], [2, 2, 9996], [false, false, true]⟩
theorem basis800 : IsBasis c800.certificate := by lin_cert using ()
def c801 : Wire := ⟨1, "CW_eta_2", 12, 139, 6, [false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, false, true, false, true, true, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true], [false, true, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false, true], [2, 2, 2, 9994, 9998, 9998], [false, false, false, true, false, false]⟩
theorem basis801 : IsBasis c801.certificate := by lin_cert using ()
def c802 : Wire := ⟨1, "CW_eta_2", 13, 135, 4, [false, true, false, false, false, false, false, true, true, false, false, false, true, false, true, false], [false, false, true, false, true, false, false, false, false, false, true, true, false, true, false, false], [9995, 9996, 9997, 9997], [true, false, false, true]⟩
theorem basis802 : IsBasis c802.certificate := by lin_cert using ()
def c803 : Wire := ⟨1, "CW_eta_2", 13, 136, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 9997, 9997], [false, false, false]⟩
theorem basis803 : IsBasis c803.certificate := by lin_cert using ()
def c804 : Wire := ⟨1, "CW_eta_2", 13, 137, 4, [false, false, false, true, false, false, true, false, false, true, false, false, true, false, false, false], [false, false, false, true, false, false, true, false, false, true, false, false, true, false, false, false], [2, 3, 9994, 9998], [false, false, true, false]⟩
theorem basis804 : IsBasis c804.certificate := by lin_cert using ()
def c805 : Wire := ⟨1, "CW_eta_2", 13, 138, 4, [false, false, false, true, false, false, true, false, true, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, true, false, true, false, false, true, false, false, false], [2, 2, 9997, 9998], [false, false, false, false]⟩
theorem basis805 : IsBasis c805.certificate := by lin_cert using ()
def c806 : Wire := ⟨1, "CW_eta_2", 13, 139, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 9000, 9998], [false, true, false]⟩
theorem basis806 : IsBasis c806.certificate := by lin_cert using ()
def c807 : Wire := ⟨1, "CW_eta_2", 13, 140, 7, [false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true], [false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, true], [2, 2, 9000, 9000, 9997, 9998, 9998], [false, false, true, true, false, false, false]⟩
theorem basis807 : IsBasis c807.certificate := by lin_cert using ()
def c808 : Wire := ⟨1, "CW_eta_2", 14, 136, 2, [false, true, true, false], [false, true, true, false], [2, 3], [false, false]⟩
theorem basis808 : IsBasis c808.certificate := by lin_cert using ()
def c809 : Wire := ⟨1, "CW_eta_2", 14, 137, 4, [true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true], [true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true], [2, 9993, 9997, 9997], [false, true, false, false]⟩
theorem basis809 : IsBasis c809.certificate := by lin_cert using ()
def c810 : Wire := ⟨1, "CW_eta_2", 14, 138, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [9000, 9998, 9998], [true, false, false]⟩
theorem basis810 : IsBasis c810.certificate := by lin_cert using ()
def c811 : Wire := ⟨1, "CW_eta_2", 14, 139, 2, [true, false, false, true], [true, false, false, true], [9997, 9998], [false, false]⟩
theorem basis811 : IsBasis c811.certificate := by lin_cert using ()
def c812 : Wire := ⟨1, "CW_eta_2", 14, 140, 7, [true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, true, false, true, false, false, false, false, false], [true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, true, false], [2, 2, 9000, 9000, 9000, 9997, 9998], [false, false, true, true, true, false, false]⟩
theorem basis812 : IsBasis c812.certificate := by lin_cert using ()
def c813 : Wire := ⟨1, "CW_eta_2", 14, 141, 6, [true, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true], [true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, true, false, true, false, false, false, true, false, false, false, false, true], [4, 9000, 9000, 9996, 9997, 9998], [false, true, true, false, false, false]⟩
theorem basis813 : IsBasis c813.certificate := by lin_cert using ()
def c814 : Wire := ⟨1, "CW_eta_2", 15, 137, 3, [true, false, false, false, false, true, false, true, false], [true, false, false, false, false, true, false, true, false], [9000, 9997, 9998], [true, false, false]⟩
theorem basis814 : IsBasis c814.certificate := by lin_cert using ()
def c815 : Wire := ⟨1, "CW_eta_2", 15, 138, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [2, 9994, 9994], [false, true, true]⟩
theorem basis815 : IsBasis c815.certificate := by lin_cert using ()
def c816 : Wire := ⟨1, "CW_eta_2", 15, 139, 5, [false, false, true, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false], [false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false], [2, 9000, 9994, 9997, 9998], [false, true, true, false, false]⟩
theorem basis816 : IsBasis c816.certificate := by lin_cert using ()
def c817 : Wire := ⟨1, "CW_eta_2", 15, 140, 4, [false, true, false, false, false, true, true, false, true, false, false, false, false, false, false, true], [false, false, true, false, true, false, false, false, true, true, false, false, false, false, false, true], [2, 5, 9000, 9998], [false, false, true, false]⟩
theorem basis817 : IsBasis c817.certificate := by lin_cert using ()
def c818 : Wire := ⟨1, "CW_eta_2", 15, 141, 4, [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [2, 2, 5, 9000], [false, false, false, true]⟩
theorem basis818 : IsBasis c818.certificate := by lin_cert using ()
def c819 : Wire := ⟨1, "CW_eta_2", 15, 142, 6, [false, false, false, true, false, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, true], [false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, true, false, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true], [2, 3, 9000, 9000, 9998, 9998], [false, false, true, true, false, false]⟩
theorem basis819 : IsBasis c819.certificate := by lin_cert using ()
def c820 : Wire := ⟨1, "CW_eta_2", 16, 138, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [3, 3, 9000], [false, false, true]⟩
theorem basis820 : IsBasis c820.certificate := by lin_cert using ()
def c821 : Wire := ⟨1, "CW_eta_2", 16, 139, 5, [false, false, false, false, true, false, false, true, false, false, false, false, true, true, false, true, false, false, false, false, false, true, false, false, false], [false, false, false, true, false, false, false, false, false, true, false, true, false, false, false, false, true, true, false, false, true, false, false, false, false], [2, 2, 9996, 9997, 9998], [false, false, false, false, false]⟩
theorem basis821 : IsBasis c821.certificate := by lin_cert using ()
def c822 : Wire := ⟨1, "CW_eta_2", 16, 140, 4, [false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, false], [false, true, false, false, false, false, false, true, true, false, false, false, false, false, true, false], [2, 3, 4, 9998], [false, false, false, false]⟩
theorem basis822 : IsBasis c822.certificate := by lin_cert using ()
def c823 : Wire := ⟨1, "CW_eta_2", 16, 141, 5, [false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, true], [false, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, true], [2, 9000, 9000, 9994, 9998], [false, true, true, true, false]⟩
theorem basis823 : IsBasis c823.certificate := by lin_cert using ()
def c824 : Wire := ⟨1, "CW_eta_2", 16, 142, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 3, 9000], [false, false, true]⟩
theorem basis824 : IsBasis c824.certificate := by lin_cert using ()
def c825 : Wire := ⟨1, "CW_eta_2", 16, 143, 6, [false, false, true, false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false], [false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false], [2, 2, 4, 9997, 9997, 9998], [false, false, false, false, false, false]⟩
theorem basis825 : IsBasis c825.certificate := by lin_cert using ()
def c826 : Wire := ⟨1, "CW_eta_2", 17, 139, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [3, 3, 9000], [false, false, true]⟩
theorem basis826 : IsBasis c826.certificate := by lin_cert using ()
def c827 : Wire := ⟨1, "CW_eta_2", 17, 140, 4, [false, true, false, false, false, true, true, false, false, true, true, true, true, false, false, false], [false, false, false, true, true, false, false, false, true, true, false, false, false, true, true, false], [2, 9997, 9997, 9998], [false, false, false, false]⟩
theorem basis827 : IsBasis c827.certificate := by lin_cert using ()
def c828 : Wire := ⟨1, "CW_eta_2", 17, 141, 5, [false, false, true, false, false, false, true, false, false, false, false, false, true, false, true, true, false, false, false, false, false, false, true, true, false], [false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, true, false, false, false, true, true, false, true, false, false], [2, 3, 9000, 9997, 9997], [false, false, true, false, true]⟩
theorem basis828 : IsBasis c828.certificate := by lin_cert using ()
def c829 : Wire := ⟨1, "CW_eta_2", 17, 142, 3, [true, false, false, false, true, false, false, false, true], [true, false, false, false, true, false, false, false, true], [3, 9996, 9998], [false, false, false]⟩
theorem basis829 : IsBasis c829.certificate := by lin_cert using ()
def c830 : Wire := ⟨1, "CW_eta_2", 17, 143, 4, [false, false, false, true, true, false, false, false, true, false, true, false, true, true, false, false], [false, true, false, false, false, true, false, true, false, true, true, false, true, false, false, false], [2, 2, 3, 9998], [false, false, false, false]⟩
theorem basis830 : IsBasis c830.certificate := by lin_cert using ()
def c831 : Wire := ⟨1, "CW_eta_2", 17, 144, 4, [false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, true], [false, false, true, false, false, true, false, false, true, false, false, false, false, false, false, true], [2, 3, 3, 9997], [false, false, false, false]⟩
theorem basis831 : IsBasis c831.certificate := by lin_cert using ()
def c832 : Wire := ⟨1, "CW_eta_2", 18, 140, 4, [false, false, true, false, false, false, false, true, false, true, false, false, true, false, false, false], [false, false, false, true, false, false, true, false, true, false, false, false, false, true, false, false], [2, 9996, 9997, 9998], [false, false, false, false]⟩
theorem basis832 : IsBasis c832.certificate := by lin_cert using ()
def c833 : Wire := ⟨1, "CW_eta_2", 18, 141, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [2, 3, 9998], [false, false, false]⟩
theorem basis833 : IsBasis c833.certificate := by lin_cert using ()
def c834 : Wire := ⟨1, "CW_eta_2", 18, 142, 2, [false, true, true, false], [false, true, true, false], [2, 9997], [false, false]⟩
theorem basis834 : IsBasis c834.certificate := by lin_cert using ()
def c835 : Wire := ⟨1, "CW_eta_2", 18, 143, 3, [true, false, false, true, false, true, false, true, false], [true, false, false, false, false, true, true, true, false], [9000, 9998, 9998], [true, false, false]⟩
theorem basis835 : IsBasis c835.certificate := by lin_cert using ()
def c836 : Wire := ⟨1, "CW_eta_2", 18, 144, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 4, 9000], [false, false, true]⟩
theorem basis836 : IsBasis c836.certificate := by lin_cert using ()
def c837 : Wire := ⟨1, "CW_eta_2", 18, 145, 5, [false, false, false, true, false, true, false, false, false, false, true, false, true, false, false, true, true, false, false, false, false, false, false, false, true], [false, true, false, false, false, false, true, false, true, false, false, true, true, false, false, true, false, false, false, false, false, false, false, false, true], [2, 2, 3, 9000, 9997], [false, false, false, true, false]⟩
theorem basis837 : IsBasis c837.certificate := by lin_cert using ()
def c838 : Wire := ⟨1, "CW_eta_2", 19, 141, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [2, 3, 9000], [false, false, true]⟩
theorem basis838 : IsBasis c838.certificate := by lin_cert using ()
def c839 : Wire := ⟨1, "CW_eta_2", 19, 142, 2, [false, true, true, false], [false, true, true, false], [9995, 9995], [false, true]⟩
theorem basis839 : IsBasis c839.certificate := by lin_cert using ()
def c840 : Wire := ⟨1, "CW_eta_2", 19, 143, 2, [false, true, true, false], [false, true, true, false], [2, 9996], [false, false]⟩
theorem basis840 : IsBasis c840.certificate := by lin_cert using ()
def c841 : Wire := ⟨1, "CW_eta_2", 19, 144, 4, [true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true], [true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true], [2, 9997, 9997, 9998], [false, false, false, false]⟩
theorem basis841 : IsBasis c841.certificate := by lin_cert using ()
def c842 : Wire := ⟨1, "CW_eta_2", 19, 145, 5, [false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false], [false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false], [3, 3, 9000, 9997, 9997], [false, false, true, false, false]⟩
theorem basis842 : IsBasis c842.certificate := by lin_cert using ()
def c843 : Wire := ⟨1, "CW_eta_2", 19, 146, 4, [false, false, false, true, false, true, false, false, true, false, false, false, false, false, true, false], [false, false, true, false, false, true, false, false, false, false, false, true, true, false, false, false], [2, 9000, 9997, 9997], [false, true, false, false]⟩
theorem basis843 : IsBasis c843.certificate := by lin_cert using ()
def c844 : Wire := ⟨1, "CW_eta_2", 20, 142, 5, [false, false, false, true, false, false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false], [false, false, false, false, true, false, false, true, false, false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, false], [2, 3, 3, 4, 9998], [false, false, false, false, false]⟩
theorem basis844 : IsBasis c844.certificate := by lin_cert using ()
def c845 : Wire := ⟨1, "CW_eta_2", 20, 143, 2, [false, true, true, false], [false, true, true, false], [3, 9000], [false, true]⟩
theorem basis845 : IsBasis c845.certificate := by lin_cert using ()
def c846 : Wire := ⟨1, "CW_eta_2", 20, 144, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 2, 9997], [false, false, false]⟩
theorem basis846 : IsBasis c846.certificate := by lin_cert using ()
def c847 : Wire := ⟨1, "CW_eta_2", 20, 145, 3, [true, false, false, false, false, true, false, true, false], [true, false, false, false, false, true, false, true, false], [9997, 9998, 9998], [false, false, false]⟩
theorem basis847 : IsBasis c847.certificate := by lin_cert using ()
def c848 : Wire := ⟨1, "CW_eta_2", 20, 146, 2, [false, true, true, false], [false, true, true, false], [3, 9998], [false, false]⟩
theorem basis848 : IsBasis c848.certificate := by lin_cert using ()
def c849 : Wire := ⟨1, "CW_eta_2", 20, 147, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [2, 2, 9997], [false, false, false]⟩
theorem basis849 : IsBasis c849.certificate := by lin_cert using ()
def c850 : Wire := ⟨1, "CW_eta_2", 21, 143, 4, [false, true, false, false, false, false, false, true, true, false, false, false, false, false, true, false], [false, false, true, false, true, false, false, false, false, false, false, true, false, true, false, false], [9000, 9000, 9998, 9998], [true, true, false, false]⟩
theorem basis850 : IsBasis c850.certificate := by lin_cert using ()
def c851 : Wire := ⟨1, "CW_eta_2", 21, 144, 2, [false, true, true, false], [false, true, true, false], [3, 9000], [false, true]⟩
theorem basis851 : IsBasis c851.certificate := by lin_cert using ()
def c852 : Wire := ⟨1, "CW_eta_2", 21, 145, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [2, 4, 9998], [false, false, false]⟩
theorem basis852 : IsBasis c852.certificate := by lin_cert using ()
def c853 : Wire := ⟨1, "CW_eta_2", 21, 146, 3, [true, false, false, false, true, false, true, false, true], [true, false, false, false, true, false, true, false, true], [9996, 9998, 9998], [false, false, false]⟩
theorem basis853 : IsBasis c853.certificate := by lin_cert using ()
def c854 : Wire := ⟨1, "CW_eta_2", 21, 147, 2, [false, true, true, false], [false, true, true, false], [3, 9996], [false, false]⟩
theorem basis854 : IsBasis c854.certificate := by lin_cert using ()
def c855 : Wire := ⟨1, "CW_eta_2", 21, 148, 5, [false, false, false, false, true, false, false, false, true, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false], [false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, true, false, false, false, true, false, false, false, false], [2, 9000, 9997, 9997, 9998], [false, true, false, false, false]⟩
theorem basis855 : IsBasis c855.certificate := by lin_cert using ()
def c856 : Wire := ⟨1, "CW_eta_2", 22, 144, 2, [true, false, false, true], [true, false, false, true], [9000, 9997], [true, false]⟩
theorem basis856 : IsBasis c856.certificate := by lin_cert using ()
def c857 : Wire := ⟨1, "CW_eta_2", 22, 146, 7, [false, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, true, false, false, false, false, false, false], [false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, false, false, false], [2, 2, 3, 3, 9000, 9996, 9998], [false, false, false, false, true, false, false]⟩
theorem basis857 : IsBasis c857.certificate := by lin_cert using ()
def c858 : Wire := ⟨1, "CW_eta_2", 22, 147, 4, [true, false, false, false, false, true, false, false, false, false, false, true, true, false, true, false], [true, false, false, false, false, true, false, false, true, false, false, true, false, false, true, false], [2, 3, 3, 9997], [false, false, false, false]⟩
theorem basis858 : IsBasis c858.certificate := by lin_cert using ()
def c859 : Wire := ⟨1, "CW_eta_2", 22, 148, 2, [false, true, true, false], [false, true, true, false], [3, 3], [false, false]⟩
theorem basis859 : IsBasis c859.certificate := by lin_cert using ()
def c860 : Wire := ⟨1, "CW_eta_2", 22, 149, 5, [false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false], [false, false, false, true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false], [2, 4, 9000, 9997, 9998], [false, false, true, false, false]⟩
theorem basis860 : IsBasis c860.certificate := by lin_cert using ()
def c861 : Wire := ⟨1, "CW_eta_2", 23, 145, 2, [false, true, true, false], [false, true, true, false], [9000, 9998], [true, false]⟩
theorem basis861 : IsBasis c861.certificate := by lin_cert using ()
def c862 : Wire := ⟨1, "CW_eta_2", 23, 146, 4, [false, true, false, false, false, false, true, false, true, false, false, false, false, false, false, true], [false, false, true, false, true, false, false, false, false, true, false, false, false, false, false, true], [2, 3, 4, 9000], [false, false, false, true]⟩
theorem basis862 : IsBasis c862.certificate := by lin_cert using ()
def c863 : Wire := ⟨1, "CW_eta_2", 23, 147, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 2, 3], [false, false, false]⟩
theorem basis863 : IsBasis c863.certificate := by lin_cert using ()
def c864 : Wire := ⟨1, "CW_eta_2", 23, 148, 1, [true], [true], [9998], [false]⟩
theorem basis864 : IsBasis c864.certificate := by lin_cert using ()
def c865 : Wire := ⟨1, "CW_eta_2", 23, 149, 3, [true, false, false, false, false, true, false, true, false], [true, false, false, false, false, true, false, true, false], [2, 3, 9996], [false, false, false]⟩
theorem basis865 : IsBasis c865.certificate := by lin_cert using ()
def c866 : Wire := ⟨1, "CW_eta_2", 23, 150, 2, [true, false, false, true], [true, false, false, true], [2, 9997], [false, false]⟩
theorem basis866 : IsBasis c866.certificate := by lin_cert using ()
def c867 : Wire := ⟨1, "CW_eta_2", 24, 146, 2, [false, true, true, false], [false, true, true, false], [5, 9000], [false, true]⟩
theorem basis867 : IsBasis c867.certificate := by lin_cert using ()
def c868 : Wire := ⟨1, "CW_eta_2", 24, 147, 1, [true], [true], [2], [false]⟩
theorem basis868 : IsBasis c868.certificate := by lin_cert using ()
def c869 : Wire := ⟨1, "CW_eta_2", 24, 148, 2, [false, true, true, false], [false, true, true, false], [9998, 9998], [false, false]⟩
theorem basis869 : IsBasis c869.certificate := by lin_cert using ()
def c870 : Wire := ⟨1, "CW_eta_2", 24, 149, 2, [false, true, true, false], [false, true, true, false], [9996, 9998], [false, false]⟩
theorem basis870 : IsBasis c870.certificate := by lin_cert using ()
def c871 : Wire := ⟨1, "CW_eta_2", 24, 150, 3, [false, false, true, true, false, false, false, true, false], [false, true, false, false, false, true, true, false, false], [2, 3, 3], [false, false, false]⟩
theorem basis871 : IsBasis c871.certificate := by lin_cert using ()
def c872 : Wire := ⟨1, "CW_eta_2", 24, 151, 3, [false, true, false, false, false, true, true, false, false], [false, false, true, true, false, false, false, true, false], [9997, 9998, 9998], [false, false, false]⟩
theorem basis872 : IsBasis c872.certificate := by lin_cert using ()
def c873 : Wire := ⟨1, "CW_eta_2", 25, 148, 2, [false, true, true, false], [false, true, true, false], [9998, 9998], [false, false]⟩
theorem basis873 : IsBasis c873.certificate := by lin_cert using ()
def c874 : Wire := ⟨1, "CW_eta_2", 25, 149, 4, [true, false, false, false, false, false, true, false, false, true, false, false, false, false, true, true], [true, false, false, false, false, false, true, false, false, true, false, false, false, true, false, true], [2, 3, 4, 9998], [false, false, false, false]⟩
theorem basis874 : IsBasis c874.certificate := by lin_cert using ()
def c875 : Wire := ⟨1, "CW_eta_2", 25, 150, 2, [false, true, true, false], [false, true, true, false], [4, 9998], [false, false]⟩
theorem basis875 : IsBasis c875.certificate := by lin_cert using ()
def c876 : Wire := ⟨1, "CW_eta_2", 25, 151, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [3, 9998, 9998], [false, false, false]⟩
theorem basis876 : IsBasis c876.certificate := by lin_cert using ()
def c877 : Wire := ⟨1, "CW_eta_2", 25, 152, 6, [false, false, true, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, true, true, false, false, false, true, false, false], [false, false, false, true, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, false, false, true, false, false, true, false], [2, 3, 9000, 9997, 9997, 9998], [false, false, true, false, false, false]⟩
theorem basis877 : IsBasis c877.certificate := by lin_cert using ()
def c878 : Wire := ⟨1, "CW_eta_nu", 1, 128, 1, [true], [true], [9998], [false]⟩
theorem basis878 : IsBasis c878.certificate := by lin_cert using ()
def c879 : Wire := ⟨1, "CW_eta_nu", 2, 128, 1, [true], [true], [9000], [true]⟩
theorem basis879 : IsBasis c879.certificate := by lin_cert using ()
def c880 : Wire := ⟨1, "CW_eta_nu", 2, 129, 1, [true], [true], [9998], [false]⟩
theorem basis880 : IsBasis c880.certificate := by lin_cert using ()
def c881 : Wire := ⟨1, "CW_eta_nu", 3, 129, 1, [true], [true], [2], [false]⟩
theorem basis881 : IsBasis c881.certificate := by lin_cert using ()
def c882 : Wire := ⟨1, "CW_eta_nu", 3, 130, 1, [true], [true], [9998], [false]⟩
theorem basis882 : IsBasis c882.certificate := by lin_cert using ()
def c883 : Wire := ⟨1, "CW_eta_nu", 4, 130, 2, [false, true, true, false], [false, true, true, false], [2, 9993], [false, true]⟩
theorem basis883 : IsBasis c883.certificate := by lin_cert using ()
def c884 : Wire := ⟨1, "CW_eta_nu", 4, 131, 1, [true], [true], [9998], [false]⟩
theorem basis884 : IsBasis c884.certificate := by lin_cert using ()
def c885 : Wire := ⟨1, "CW_eta_nu", 5, 130, 1, [true], [true], [9998], [false]⟩
theorem basis885 : IsBasis c885.certificate := by lin_cert using ()
def c886 : Wire := ⟨1, "CW_eta_nu", 5, 131, 1, [true], [true], [2], [false]⟩
theorem basis886 : IsBasis c886.certificate := by lin_cert using ()
def c887 : Wire := ⟨1, "CW_eta_nu", 5, 132, 2, [true, false, false, true], [true, false, false, true], [9998, 9998], [false, false]⟩
theorem basis887 : IsBasis c887.certificate := by lin_cert using ()
def c888 : Wire := ⟨1, "CW_eta_nu", 6, 130, 1, [true], [true], [9994], [false]⟩
theorem basis888 : IsBasis c888.certificate := by lin_cert using ()
def c889 : Wire := ⟨1, "CW_eta_nu", 6, 131, 2, [false, true, true, false], [false, true, true, false], [9995, 9995], [true, true]⟩
theorem basis889 : IsBasis c889.certificate := by lin_cert using ()
def c890 : Wire := ⟨1, "CW_eta_nu", 6, 132, 2, [false, true, true, false], [false, true, true, false], [2, 9995], [false, true]⟩
theorem basis890 : IsBasis c890.certificate := by lin_cert using ()
def c891 : Wire := ⟨1, "CW_eta_nu", 6, 133, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [2, 9998, 9998], [false, false, false]⟩
theorem basis891 : IsBasis c891.certificate := by lin_cert using ()
def c892 : Wire := ⟨1, "CW_eta_nu", 7, 130, 2, [true, false, false, true], [true, false, false, true], [9995, 9997], [true, false]⟩
theorem basis892 : IsBasis c892.certificate := by lin_cert using ()
def c893 : Wire := ⟨1, "CW_eta_nu", 7, 131, 3, [false, false, true, false, true, false, true, false, false], [false, false, true, false, true, false, true, false, false], [2, 9989, 9996], [false, true, true]⟩
theorem basis893 : IsBasis c893.certificate := by lin_cert using ()
def c894 : Wire := ⟨1, "CW_eta_nu", 7, 133, 4, [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false], [2, 2, 9998, 9998], [false, false, false, false]⟩
theorem basis894 : IsBasis c894.certificate := by lin_cert using ()
def c895 : Wire := ⟨1, "CW_eta_nu", 7, 134, 6, [false, false, false, true, false, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, true], [false, false, false, false, true, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, true], [2, 9996, 9996, 9998, 9998, 9998], [false, false, true, false, false, false]⟩
theorem basis895 : IsBasis c895.certificate := by lin_cert using ()
def c896 : Wire := ⟨1, "CW_eta_nu", 8, 130, 1, [true], [true], [9997], [true]⟩
theorem basis896 : IsBasis c896.certificate := by lin_cert using ()
def c897 : Wire := ⟨1, "CW_eta_nu", 8, 131, 2, [true, false, false, true], [true, false, false, true], [9996, 9997], [true, false]⟩
theorem basis897 : IsBasis c897.certificate := by lin_cert using ()
def c898 : Wire := ⟨1, "CW_eta_nu", 8, 132, 2, [true, false, true, true], [true, false, true, true], [9997, 9998], [false, false]⟩
theorem basis898 : IsBasis c898.certificate := by lin_cert using ()
def c899 : Wire := ⟨1, "CW_eta_nu", 8, 133, 3, [false, true, false, true, false, false, false, false, true], [false, true, false, true, false, false, false, false, true], [9995, 9998, 9998], [true, false, false]⟩
theorem basis899 : IsBasis c899.certificate := by lin_cert using ()
end StaircaseCertificates.Release8
