#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
export ELAN_HOME=/inspire/hdd/global_user/baokangjie-CZXS25250151/.elan
export LEAN_SYSROOT="$ELAN_HOME/toolchains/leanprover--lean4---v4.32.2"
export LEAN_PATH="$PWD/.lake/build/lib/lean"
for dep in ../../KIP126/.lake/packages/*/.lake/build/lib/lean; do
  export LEAN_PATH="$LEAN_PATH:$dep"
done
if [ -f /tmp/lean_proc_shim.so ]; then export LD_PRELOAD=/tmp/lean_proc_shim.so; fi
for module in \
  LinProgramCertificates/Verifier \
  LinProgramCertificates/Tactic \
  LinearCertificates/Basic \
  LinearCertificates/Checker \
  ResolutionCertificates/Basic \
  ResolutionCertificates/HomologyBasis \
  PageTransitionCertificates/Basic \
  PageTransitionCertificates/Quotient \
  LinearCertificates/Diagnostics \
  LinearCertificates/Import \
  PageTransitionCertificates/Import \
  PageTransitionCertificates/Trajectory \
  AggregateTargetInventory/EventAudit/Executable \
  SemanticTrajectoryCertificates/Page \
  PermanentCycleCertificates/System \
  PermanentCycleCertificates/Finite \
  OutgoingCycleCertificates/Basic \
  OutgoingCycleFiltrationCertificates/Basic \
  OutgoingCycleFiltrationCertificates/Boundary \
  OutgoingCycleFiltrationCertificates/Strong \
  ActualAdamsFiltration/Basic \
  ManualInputObligations/Reference/Foundations \
  ManualInputObligations/Reference/AlgebraTopology \
  ManualInputObligations/Reference/CohomologySteenrod \
  ManualInputObligations/Reference/SteenrodAdams \
  ManualInputObligations/Reference/AdamsHomology \
  ManualInputObligations/Reference/AdamsRules \
  ManualInputObligations/Typed \
  ActualAdamsSystemBridge/Basic \
  ActualAdamsSystemBridge/Trace \
  ActualAdamsFiltration/Actual \
  ActualAdamsAdditiveFiltration/Basic \
  ActualAdamsAdditiveFiltration/Subgroups \
  ActualAdamsAdditiveFiltration/Quotient \
  ActualAdamsAdditiveFiltration/Counterexamples \
  ActualAdamsAdditiveQuotient/Basic \
  OutgoingCycleFiltrationCertificates/Certificate \
  OutgoingCycleFiltrationCertificates/Examples \
  PermanentMapTailCertificates/Basic \
  PermanentMapTailCertificates/Certificate \
  PageTransitionCertificates/TrajectoryImport \
  PermanentCycleCertificates/Import \
  OutgoingCycleCertificates/Import \
  PermanentMapTailCertificates/Import \
  PermanentCycleCertificates/AdamsBounds \
  PermanentCycleCertificates/Examples \
  PermanentCycleCertificates/ImportExamples \
  ActualPermanenceBoundary/Basic \
  NamedElementCertificates/Basic \
  NamedElementCertificates/Generated \
  NamedElementCertificates/Evaluation \
  Fact762PageCertificates/Survivor \
  Fact763PageCertificates/Survivor \
  Fact721PageCertificates/First \
  Fact721PageCertificates/Second \
  ActualPermanenceBoundary/Cases \
  OutgoingCycleCertificates/Examples \
  PermanentMapTailCertificates/Examples \
  ActualAdamsFiltration/Examples \
  Row2925EtaD4/H05 \
  BranchReplayCertificates/Products \
  RealMapCertificates/Substitution \
  BranchReplayCertificates/MapColumns \
  BranchReplayCertificates/BasisSemantics \
  Row2925EtaD4/H05Semantics \
  Row2925EtaD4/Products \
  PageTransitionCertificates/InducedMap \
  Row2925EtaD4/Comparison \
  Row2925EtaD4/Higher \
  Row2925EtaD4/Naturality \
  NamedPageComparison/FiniteFaithfulness \
  PageProductCertificates/Basic \
  PageProductCertificates/Quotient \
  PageProductCertificates/Witness \
  PageProductCertificates/CycleWitness \
  PageProductCertificates/Import \
  Row2925EtaD4/LeftTerm \
  Row2574Detector/Products_h2 \
  Row2574Detector/Quotient \
  Row2574Detector/Additional/Products_f0 \
  Row2574Detector/Additional/Combined \
  AffineRemainingSearch/Data \
  AffineRemainingSearch/Branches \
  AffineRemainingSearch/Kernel \
  AffineRemainingSearch/Links \
  NamedElementCertificates/ModuleEvaluation \
  ModuleMapCertificates/Basic \
  ModuleMapCertificates/Import \
  ModuleMapCertificates/MatrixSemantics \
  ModuleToModuleCertificates/Basic \
  ModuleToModuleCertificates/Matrix \
  ModuleToModuleCertificates/Import \
  ModuleToModuleCertificates/WireSemantics \
  ModuleToModuleCertificates/ShiftedImport \
  Row2796D5Detector/Actual \
  Row2796D5Detector/Comparison \
  Row2796D5Detector/Higher \
  Row2796D5Detector/Target \
  Row2796D5Detector/Source \
  Row2796D5Detector/Matches \
  Row3019Detector/Actual \
  Row3019Detector/Comparison \
  Row3019Detector/Naturality \
  Row3019Detector/Matches \
  Row3020Detector/Meaning \
  Row2861D4Detector/Actual \
  Row2861D4Detector/Comparison \
  Row2861D4Detector/Higher \
  Row2861D4Detector/Naturality \
  Row2861D4Detector/Matches \
  Row2861D4Detector/ImportedMeaning \
  Row2695Detector/Actual \
  Row2695Detector/Comparison \
  Row2695Detector/Naturality \
  Row2695Detector/Matches \
  HighFiltrationD2Certificates/Basic \
  HighFiltrationD2Certificates/Data \
  HighFiltrationD2Certificates/Comparisons \
  Row2929Detector/Actual \
  Row2929Detector/Comparison \
  Row2929Detector/Naturality \
  Row2929Detector/Matches \
  Row2576D4Detector/Actual \
  Row2576D4Detector/Comparison \
  Row2576D4Detector/Target \
  Row2576D4Detector/Source \
  Row2576D4Detector/Matches \
  Row2576D4Detector/ImportedBoundary \
  Row2576Detector/Actual \
  Row2576Detector/Comparison \
  Row2576Detector/Products_h2 \
  Row2576Detector/Quotient \
  Row2576Detector/Matches \
  Row2925Detector/Actual \
  Row2925Detector/Comparison \
  Row2925Detector/Naturality \
  Row2925Detector/Matches \
  Row3325Detector/Products_h1 \
  Row3325Detector/Products_g8 \
  Row3325Detector/Products_g13 \
  Row3325Detector/Quotient \
  Row3325Detector/Combined \
  Row3325Detector/Matches \
  Row2796D4Detector/Shifted \
  Row2796D4Detector/Actual \
  Row2796D4Detector/Comparison \
  Row2796D4Detector/Target \
  Row2796D4Detector/Links \
  Row2796D4Detector/Source \
  Row2796Detector/Products_h3 \
  Row2796Detector/Quotient \
  Row2796Detector/Products_d0 \
  Row2796Detector/Combined \
  Row2796Detector/Matches \
  AllClaimZeroTargetCertificates/Basic \
  Fact761PageCertificates/Survivor \
  NamedPageComparison/Fact761 \
  Fact715PageCertificates/Survivor \
  PropagationCertificates/Level \
  NamedPageComparison/Fact761D3 \
  Fact715TrajectoryCertificates/ConditionalData \
  Fact715TrajectoryCertificates/MapActual \
  Fact715TrajectoryCertificates/MapComparison \
  Fact715TrajectoryCertificates/Naturality \
  Fact715TrajectoryCertificates/Conditional \
  Fact713TrajectoryCertificates/Row3076 \
  NamedPageComparison/ConditionalHigherData \
  NamedPageComparison/Row2858/Products_g \
  NamedPageComparison/Row2858/Products_h1 \
  NamedPageComparison/Row2858/Products_h3 \
  NamedPageComparison/Row2858/Refutation \
  NamedPageComparison/Row2858/Boundaries \
  PageProductCertificates/Row2858 \
  NamedPageComparison/Row3080 \
  NamedPageComparison/ConditionalHigher \
  AllClaimConditionalZeroCertificates/Basic \
  Fact713C2Row3143/MapActual \
  Fact713C2Row3143/MapComparison \
  Fact713C2Row3143/Next \
  Fact713C2Row3143/InjectiveNext \
  Fact713C2Row3143/Naturality \
  Fact713C2Row3143/FollowingColumns \
  Fact713C2Row3143/MapSemantics \
  Fact713C2Row3143/Matches \
  AllClaimC2ConditionalCertificates/Basic \
  Fact713C2Row3005/MapActual \
  Fact713C2Row3005/MapComparison \
  Fact713C2Row3005/Naturality \
  Fact713C2Row3005/MapSemantics \
  Fact713C2Row3005/Matches \
  AllClaimPrefixConditionalCertificates/Basic \
  Row2693Detector/Products_h2 \
  Row2693Detector/Quotient \
  Row2693Detector/Products_h0 \
  Row2693Detector/Combined \
  Row2693Detector/Matches \
  AllClaimLeibnizConditionalCertificates/Basic \
  AggregateTargetInventory/EventAudit/Basic \
  Row2861Csigma/Actual \
  Row2861Csigma/Comparison \
  Row2861Csigma/Naturality \
  Row2861Csigma/Matches \
  AggregateD5Conditional/Basic \
  AggregateD5Conditional/Data \
  AggregateTargetInventory/EventAudit/Indexed \
  AggregateTargetInventory/EventAudit/IndexedDiagnostics \
  IndexedFamilyCertificates/Basic \
  IndexedFamilyCertificates/Import \
  IndexedFamilyCertificates/Results \
  IndexedFamilyCertificates/Coherence \
  Row3151BranchCertificates/Branch00 \
  Row3151BranchCertificates/Branch01 \
  Row3151BranchCertificates/Branch10 \
  Row3151BranchCertificates/Branch11 \
  Row2708KernelConditional/Conflict \
  Row3151BranchCertificates/Semantics \
  RemainingThreeAudit/Consequences \
  PageTransitionCertificates/AdditiveQuotient \
  Row2925EtaD4/Restriction \
  Row2925EtaD4/Links \
  Row3152BranchCertificates/Generic \
  Row3152BranchCertificates/Import \
  Row3152BranchCertificates/Branch0 \
  Row3152BranchCertificates/Branch1 \
  Row3152BranchCertificates/Semantics \
  Row3151FullNeighborhood/Data \
  Row3151FullNeighborhood/Checks \
  Row3151FullNeighborhood/Semantics \
  Row3151FullNeighborhood/Links \
  Row3564LeibnizDetector/Products_h1 \
  Row3564LeibnizDetector/Products_h04 \
  Row3564LeibnizDetector/Quotient \
  Row3564LeibnizDetector/ProductSemantics \
  Row3564LeibnizDetector/Matches \
  AggregateLeibniz3564Conditional/Source \
  BranchReplayCertificates/GeneratedLeaves \
  BranchReplayCertificates/ProductRefutation \
  AdvancedRuleCertificates/Affine \
  BranchReplayCertificates/CandidateReduction \
  BranchReplayCertificates/MapRefutation \
  BranchReplayCertificates/E4Descent \
  BranchReplayCertificates/GeneratedProductColumns \
  BranchReplayCertificates/ProductBasisSemantics \
  BranchReplayCertificates/MapBasisSemantics \
  Fact764ConstrainedE5/Coordinates \
  Stem125HomologyCertificates/Basic \
  StaircaseCertificates/Basic \
  AggregateTargetInventory/Bases \
  AggregateTargetInventory/Aggregate \
  Stem125HomologyCertificates/D2 \
  Stem125HomologyCertificates/D3 \
  Stem125E4Search/Data \
  Stem125E4Search/Product \
  Stem125E4Search/Zero \
  Stem125E5Search/Data \
  Stem125E5Search/Known \
  Stem125E5Search/Product \
  Stem125E5Search/Branches \
  UniqueHomologyCertificates/Basic \
  Fact764ConstrainedE5/Conclusion \
  Fact764ConstrainedE5/Obstructions \
  UniqueHomologyCertificates/Import \
  Fact764ConstrainedE5/Imported \
  Stem125HomologyCertificates/Meaning \
  ActualUniqueHomologyCertificates/Basic \
  Fact764ConstrainedE5/Actual \
  Fact762IncomingCertificates/Data \
  Fact762IncomingCertificates/ZeroPropagation \
  Fact764CycleFromProduct/Data \
  Fact764CycleFromProduct/Basic \
  ActualAdamsProductCycleBridge/Basic \
  Row2925EtaD4/Actual \
  ActualAdamsSystemBridge/Tail \
  Fact762IncomingCertificates/Incoming \
  Fact762Source7Certificates/Finite \
  Fact762Source4Certificates/KernelBranch \
  Fact762Source7Certificates/Propagation \
  Fact762Source7Certificates/Semantics \
  Fact762AssemblyCertificates/Routes \
  Fact762AssemblyCertificates/Assembly \
  ActualAdamsIncomingBridge/Basic \
  Row3152BranchCertificates/Actual \
  Row3151ActualTransport/Basic \
  Row3151ActualTransport/Transport \
  Row3151ActualTransport/Named \
  ActualAdamsHomologyCoordinates/Basic \
  ActualAdamsHomologyCoordinates/Adapter \
  ActualAdamsIncomingBridge/Nonvacuity \
  ActualAdamsLimit/Basic \
  ActualAdamsLimit/Certificate \
  ActualAdamsProductCycleBridge/Zero \
  ActualAdamsProductCycleBridge/Finite \
  ActualAdamsProductTraceBridge/Basic \
  ActualAdamsProductTraceBridge/Factors \
  ActualAdamsProductTraceBridge/Named \
  ActualAdamsProductTraceBridge/Assembly \
  ActualAdamsUniqueBridge/Basic \
  ActualAdamsUniqueBridge/Quotient \
  ActualAdamsUniqueBridge/Fact764 \
  ActualAdamsUniqueNext/Basic \
  ActualAdamsUniqueNext/Fact764 \
  Stem125E5Search/Zero \
  Row3992BranchCertificates/Imports \
  Row3992BranchCertificates/Checks \
  Row3992BranchCertificates/Semantics \
  Stem125E5Search/Family \
  Stem125ConstrainedE5/Basic \
  Stem125ConstrainedE5/Whole \
  Stem125ConstrainedE5/Constraints \
  ActualStem125ConstrainedE5/Basic \
  ActualStem125ConstrainedE5/Actual \
  ActualStem125ConstrainedE5/Whole \
  ActualTraceRequests/Basic \
  ActualTraceRequests/Import \
  Fact715ConstructedActual/Basic \
  Fact715ConstructedActual/Trace \
  ActualTraceRequests/Fact715 \
  Fact719PageCertificates/Survivor \
  Fact719TrajectoryCertificates/Generated \
  Fact719TrajectoryCertificates/Named \
  Fact719ConstructedActual/Basic \
  Fact719ConstructedActual/Trace \
  ActualTraceRequests/Fact719 \
  ActualTraceRequests/Tactic \
  ActualTraceRequests/Examples \
  ActualTraceRequests/ParserTests \
  Row3143D0Leibniz/Data \
  Row3143D0Leibniz/Basic \
  Row2773D4Leibniz/Descent \
  Fact721ConstructedActual/Basic \
  Prop79IncomingSearch/Finite \
  Prop79TargetSearch/Finite \
  Prop79IncomingSearch/Maps \
  Prop79IncomingSearch/Comparison \
  NamedElementCertificates/CnuBottomCell \
  CnuPageCertificates/BottomCell \
  Prop79IncomingSearch/Naturality \
  Prop79IncomingSearch/CoordinateBridge \
  Prop79IncomingSearch/Actual \
  Prop79IncomingSearch/Incoming \
  Prop79TargetSearch/ActualIncoming \
  Prop79TargetSearch/NoHit \
  Prop79TargetSearch/Constructed \
  Prop79TargetSearch/ZeroSpaces \
  Row3143D0Leibniz/Descent \
  Row3143D0Leibniz/Actual \
  Fact713ComparisonBatches/Batch07 \
  HomologyCoordinateChoice/Basic \
  Row3143D0Leibniz/Binding \
  Row3143D0Leibniz/Assembly \
  Fact713Row2431Search/Maps \
  Fact713Row2431Search/Comparison \
  Fact713Row2431Search/Naturality \
  Fact713D4SourceSearch/ActualDescent \
  Fact713Row2431Search/Actual \
  Fact713ComparisonBatches/Batch06 \
  Fact713Row2431Search/CoordinateBridge \
  Fact713Row2916Search/Maps \
  Fact713Row2916Search/Comparison \
  Fact713Row2916Search/Naturality \
  Fact713Row2916Search/Actual \
  Fact713Row2916Search/CoordinateBridge \
  Row3135H0Leibniz/Data \
  Row3135H0Leibniz/Basic \
  Row3135H0Leibniz/Actual \
  Fact721FirstD4Search/Maps \
  Fact721FirstD4Search/Comparison \
  Fact721FirstD4Search/D3 \
  Fact721FirstD4Search/Naturality \
  Fact721FirstD4Search/Actual \
  Fact713Generator30P2/Maps \
  Fact713Generator30P2/Comparison \
  Fact713Row3247Source/ModuleLeibniz \
  Fact713Row3247Source/Maps \
  Fact713Row3247Source/Comparison \
  Fact713Row3247Source/JointDetection \
  Fact713Generator30P2/Detection \
  Fact713Row3247ProductSearch/Maps \
  Fact713Row3247ProductSearch/Comparison \
  Fact713Row3247ProductSearch/Factor \
  Fact713Row3247Source/Actual \
  Fact713Generator30P2/Assembly \
  Fact713Row3247Boundaries/Basic \
  Fact713Row3247Boundaries/Actual \
  Fact713D4SourceSearch/Maps \
  Fact713D4SourceSearch/Comparison \
  Fact713D4SourceSearch/Parameters \
  Fact713D4SourceSearch/Naturality \
  Row2773Leibniz/Data \
  Row2773Leibniz/Basic \
  Row2773Leibniz/Actual \
  Fact713D4SourceSearch/Incoming \
  Fact713D4SourceSearch/Actual \
  Fact713D4SourceSearch/Assembly \
  Fact713E12Search/Data \
  Fact713PageCertificates/Survivor \
  Fact713E12Search/Prefix \
  Fact713Row2773Refinement/Data \
  Fact713NextSourceSearch/Maps \
  Fact713NextSourceSearch/Comparison \
  Fact713NextSourceSearch/Naturality \
  Fact713NextSourceSearch/Actual \
  Fact713NextSourceSearch/Overlay \
  Fact713D4SourceSearch/CoordinateBridge \
  Row2773D4Leibniz/Data \
  Row2773D4Leibniz/Basic \
  EtaD3Source/Data \
  EtaD3Source/Basic \
  EtaD3Source/Actual \
  Row2773D4Leibniz/Actual \
  Row2773D4Leibniz/CoordinateBridge \
  Fact713Row2994Constraint/Maps \
  Fact713Row2994Constraint/Comparison \
  Fact713Row2994Constraint/Naturality \
  Fact713Row2994Constraint/Actual \
  Fact713Row2994Constraint/CoordinateBridge \
  Fact713Row2994Branches/Data \
  Fact713D4Branches/ZeroData \
  Fact713RefinedComparisonFamily/Basic \
  Fact713D4Branches/ZeroExtra \
  Fact713DC2h6Source/Maps \
  Fact713DC2h6Source/Comparison \
  Fact713DC2h6Source/Naturality \
  Fact713DC2h6Source/Actual \
  Fact713DC2h6Source/Overlay \
  Fact713DC2h6ComparisonFamily/Extra \
  Fact713NextComparisonFamily/Extra \
  Fact713Row2773ComparisonFamily/Extra \
  Fact713RefinedSourceSearch/Basic \
  Fact713ComparisonBatches/Batch08 \
  Fact713ComparisonBatches/Batch09 \
  Fact713ComparisonBatches/Batch17 \
  Fact713ComparisonBatches/Batch18 \
  Fact713RefinedSourceSearch/Data \
  Fact713RefinedComparisonFamily/Extra \
  Fact713ComparisonBatches/Batch00 \
  Fact713ComparisonBatches/Batch01 \
  Fact713ComparisonBatches/Batch02 \
  Fact713ComparisonBatches/Batch03 \
  Fact713ComparisonBatches/Batch04 \
  Fact713ComparisonBatches/Batch05 \
  Fact713ComparisonBatches/Batch10 \
  Fact713ComparisonBatches/Batch11 \
  Fact713ComparisonBatches/Batch12 \
  Fact713ComparisonBatches/Batch13 \
  Fact713ComparisonBatches/Batch14 \
  Fact713ComparisonBatches/Batch15 \
  Fact713ComparisonBatches/Batch16 \
  Fact713ComparisonBatches/Batch19 \
  Fact713ComparisonBatches/Batch20 \
  Fact713ComparisonBatches/Batch21 \
  Fact713ComparisonBatches/Batch22 \
  Fact713ComparisonBatches/Batch23 \
  Fact713ComparisonBatches/Batch24 \
  Fact713ComparisonBatches/Batch25 \
  Fact713ComparisonBatches/Batch26 \
  Fact713ComparisonBatches/Batch27 \
  Fact713ComparisonBatches/Batch28 \
  Fact713ComparisonBatches/Batch29 \
  Fact713ComparisonBatches/Batch30 \
  FamilyKeyOrder/Basic \
  Fact713ComparisonBatches/Imported \
  Fact713RefinedComparisonFamily/Cross \
  Fact713Row2773ComparisonFamily/Cross \
  Fact713NextComparisonFamily/Cross \
  Fact713DC2h6ComparisonFamily/Cross \
  Fact713D4Branches/ZeroCross \
  IndexedFamilyNeighborCheck/Basic \
  Fact713ComparisonBatches/Neighbors00 \
  Fact713ComparisonBatches/Neighbors01 \
  Fact713ComparisonBatches/Neighbors02 \
  Fact713ComparisonBatches/Neighbors03 \
  Fact713ComparisonBatches/Neighbors04 \
  Fact713ComparisonBatches/Neighbors05 \
  Fact713ComparisonBatches/Neighbors06 \
  Fact713ComparisonBatches/Neighbors07 \
  Fact713ComparisonBatches/Neighbors08 \
  Fact713ComparisonBatches/Neighbors09 \
  Fact713ComparisonBatches/Neighbors10 \
  Fact713ComparisonBatches/Neighbors11 \
  Fact713ComparisonBatches/Neighbors12 \
  Fact713ComparisonBatches/Neighbors13 \
  Fact713ComparisonBatches/Neighbors14 \
  Fact713ComparisonBatches/Neighbors15 \
  Fact713ComparisonBatches/Neighbors16 \
  Fact713ComparisonBatches/Neighbors17 \
  Fact713ComparisonBatches/Neighbors18 \
  Fact713ComparisonBatches/Neighbors19 \
  Fact713ComparisonBatches/Neighbors20 \
  Fact713ComparisonBatches/Neighbors21 \
  Fact713ComparisonBatches/Neighbors22 \
  Fact713ComparisonBatches/Neighbors23 \
  Fact713ComparisonBatches/Neighbors24 \
  Fact713ComparisonBatches/Neighbors25 \
  Fact713ComparisonBatches/Neighbors26 \
  Fact713ComparisonBatches/Neighbors27 \
  Fact713ComparisonBatches/Neighbors28 \
  Fact713ComparisonBatches/Neighbors29 \
  Fact713ComparisonBatches/Neighbors30 \
  Fact713ComparisonBatches/Coherence \
  Fact713RefinedComparisonFamily/Coherence \
  Fact713Row2773ComparisonFamily/Coherence \
  Fact713NextComparisonFamily/Coherence \
  Fact713DC2h6ComparisonFamily/Coherence \
  Fact713D4Branches/ZeroCoherence \
  Fact713Row2994Branches/Extra \
  Fact713Row2994Branches/Cross \
  Fact713Row2994Branches/Coherence \
  Fact713Row2994Branches/Coverage \
  Fact713D4Branches/Branches \
  Fact713D4ComparisonBranches/Data \
  Fact713D4ComparisonBranches/ZeroExtra \
  Fact713D4ComparisonBranches/ZeroCross \
  Fact713D4ComparisonBranches/ZeroCoherence \
  Fact713D4ComparisonBranches/ResidualExtra \
  Fact713D4ComparisonBranches/ResidualCross \
  Fact713D4ComparisonBranches/ResidualCoherence \
  Fact713D4ComparisonBranches/Branches \
  Fact713Row3247ConditionalBranches/Data \
  Fact713Row3247ConditionalBranches/ZeroExtra \
  Fact713Row3247ConditionalBranches/ZeroCross \
  Fact713Row3247ConditionalBranches/ZeroCoherence \
  Fact713Row3247ConditionalBranches/ResidualExtra \
  Fact713Row3247ConditionalBranches/ResidualCross \
  Fact713Row3247ConditionalBranches/ResidualCoherence \
  Fact713Row3247ConditionalBranches/Branches \
  Fact721FirstD4Continuation/Data \
  Fact721FirstD4Continuation/ZeroExtra \
  Fact721FirstD4Continuation/ZeroCross \
  Fact721FirstD4Continuation/ZeroCoherence \
  Fact721FirstD4Continuation/ResidualExtra \
  Fact721FirstD4Continuation/ResidualCross \
  Fact721FirstD4Continuation/ResidualCoherence \
  Fact721FirstD4Continuation/Branches \
  Fact713NextD3Continuation/Data \
  Fact713NextD3Continuation/ZeroExtra \
  Fact713NextD3Continuation/ZeroCross \
  Fact713NextD3Continuation/ZeroCoherence \
  Fact713NextD3Continuation/ResidualExtra \
  Fact713NextD3Continuation/ResidualCross \
  Fact713NextD3Continuation/ResidualCoherence \
  Fact713NextD3Continuation/Branches \
  Fact713Row2431Continuation/Data \
  Fact713Row2431Continuation/ZeroExtra \
  Fact713Row2431Continuation/ZeroCross \
  Fact713Row2431Continuation/ZeroCoherence \
  Fact713Row2431Continuation/ResidualExtra \
  Fact713Row2431Continuation/ResidualCross \
  Fact713Row2431Continuation/ResidualCoherence \
  Fact713Row2431Continuation/Branches \
  Fact713Row3143Continuation/Data \
  Fact713Row3143Continuation/ZeroExtra \
  Fact713Row3143Continuation/ZeroCross \
  Fact713Row3143Continuation/ZeroCoherence \
  Fact713Row3143Continuation/ResidualExtra \
  Fact713Row3143Continuation/ResidualCross \
  Fact713Row3143Continuation/ResidualCoherence \
  Fact713Row3143Continuation/Branches \
  Fact713NamedActual/Basic \
  Fact713ConstructedNamed/Basic \
  Fact713ConstructedNamed/Trace \
  Fact713ConstructedE8/Basic \
  Fact713ConstructedE8/Trace \
  Fact713ConstructedE9/Basic \
  Fact713ConstructedE9/Trace \
  Fact713ConstructedE9/Request \
  Fact713Row3143Continuation/Constructed \
  Fact713Row3143Continuation/Request \
  ActualTraceRequestsE10/Basic \
  ActualTraceRequestsE10/Tactic \
  ActualTraceRequestsE10/Examples \
  ActualTraceRequestsNext/Fact713 \
  Fact721ConstructedActual/First \
  Fact721FirstD4Search/Constructed \
  Fact713NextSourceSearch/CoordinateBridge \
  Fact721ConstructedActual/Second \
  ActualTraceRequestsNext/Fact721 \
  Prop79TargetSearch/Trace \
  ActualTraceRequestsNext/Prop79 \
  ActualTraceRequestsNext/Tactic \
  ActualTraceRequestsNext/Examples \
  BranchReplayCertificates/QuotientConclusion \
  UniqueHomologyCertificates/Examples \
  Stem125HomologyCertificates/MeaningExamples \
  ActualUniqueHomologyCertificates/Examples \
  AdvancedRuleCertificates/Connecting \
  AdvancedRuleCertificates/Tactic \
  AdvancedRuleCertificates/AffineHomology \
  AdvancedRuleCertificates \
  AdvancedRuleCertificates/Examples \
  AdvancedRuleCertificates/Remark77 \
  AdvancedRuleCertificates/TacticExample \
  AffineRemainingSearch/Tests \
  AffineRemainingSearch/CurrentImports \
  AffineRemainingSearch/Pipeline/Branch0 \
  AffineRemainingSearch/Pipeline/Branch1 \
  AffineRemainingSearch/Pipeline/Both \
  AffineRemainingSearch \
  AggregateC2D4Conditional/Basic \
  AggregateC2D4Conditional/Data \
  AggregateC2D4Conditional/Events \
  AggregateC2D4Conditional/Matches \
  AggregateC2D4Conditional \
  AggregateC2H2Conditional/Basic \
  AggregateC2H2Conditional/Data \
  AggregateC2H2Conditional/Events \
  AggregateC2H2Conditional/Matches \
  AggregateC2H2Conditional \
  AggregateC2Row3019Conditional/Basic \
  AggregateC2Row3019Conditional/Data \
  AggregateC2Row3019Conditional/Events \
  AggregateC2Row3019Conditional/Matches \
  AggregateC2Row3019Conditional \
  AggregateCW2EtaConditional/Basic \
  AggregateCW2EtaConditional/Data \
  AggregateCW2EtaConditional/Events \
  AggregateCW2EtaConditional/Matches \
  AggregateCW2EtaConditional \
  AggregateCnuConditional/Basic \
  AggregateCnuConditional/Data \
  AggregateCnuConditional/Events \
  AggregateCnuConditional/Matches \
  AggregateCnuConditional \
  AggregateCsigmaConditional/Basic \
  AggregateCsigmaConditional/Data \
  AggregateCsigmaConditional/Events \
  AggregateCsigmaConditional/Matches \
  AggregateCsigmaConditional \
  AggregateD4Conditional/Basic \
  AggregateD4Conditional/Data \
  AggregateD4Conditional/Events \
  AggregateD4Conditional/Matches \
  AggregateTargetInventory/EventAudit/Data \
  AggregateTargetInventory/EventAudit/Events \
  AllClaimLeibnizConditionalCertificates/Data \
  AllClaimLeibnizConditionalCertificates/Matches \
  AggregateTargetInventory/EventAudit/Matches \
  AggregateTargetInventory/EventAudit/CoordinateLinks \
  AggregateTargetInventory/EventAudit/SemanticLinks \
  AggregateTargetInventory/EventAudit/StageBasic \
  AggregateTargetInventory/EventAudit/EliminationStage \
  AggregateTargetInventory/EventAudit/TrajectoryCycles \
  AggregateTargetInventory/EventAudit/NonboundaryBasic \
  AggregateD4Conditional/Trace \
  AggregateD4Conditional/Executable3254 \
  AggregateD4Conditional \
  AggregateD5Conditional/Events \
  AggregateD5Conditional/Matches \
  AggregateD5Conditional/Pipeline/Trace3391 \
  AggregateD5Conditional/Pipeline/Executable3391 \
  AggregateD5Conditional \
  AggregateDC2h6Conditional/Basic \
  AggregateDC2h6Conditional/Data \
  AggregateDC2h6Conditional/Events \
  AggregateDC2h6Conditional/Matches \
  AggregateDC2h6Conditional \
  SemanticTrajectoryCertificates/Path \
  Step4ContractAudit/SemanticBridge \
  SemanticTrajectoryCertificates/Event \
  SemanticTrajectoryCertificates/Indexed \
  AggregateEliminationCertificates/Basic \
  AggregateEliminationCertificates/Counterexample \
  IndexedD5Certificates/Extension \
  IndexedHighD2Certificates/Family \
  AggregateHighD2Conditional/Basic \
  AggregateHighD2Conditional/Data \
  IndexedHighD2Certificates/GeneratedEntries \
  IndexedHighD2Certificates/GeneratedPairs00 \
  IndexedHighD2Certificates/GeneratedPairs01 \
  IndexedHighD2Certificates/GeneratedPairs02 \
  IndexedHighD2Certificates/GeneratedPairs03 \
  IndexedHighD2Certificates/GeneratedPairs04 \
  IndexedHighD2Certificates/GeneratedPairs05 \
  IndexedHighD2Certificates/GeneratedPairs06 \
  IndexedHighD2Certificates/GeneratedPairs07 \
  IndexedHighD2Certificates/GeneratedPairs08 \
  IndexedHighD2Certificates/GeneratedPairs09 \
  IndexedHighD2Certificates/GeneratedPairs10 \
  IndexedHighD2Certificates/GeneratedPairs11 \
  IndexedHighD2Certificates/GeneratedPairs12 \
  IndexedHighD2Certificates/GeneratedPairs13 \
  IndexedHighD2Certificates/GeneratedPairs14 \
  IndexedHighD2Certificates/GeneratedCoherence \
  IndexedD5Certificates/Family \
  AggregateTargetInventory/EventAudit/IndexedBatch0 \
  IndexedHighD2Certificates/GeneratedBatch0 \
  AggregateTargetInventory/EventAudit/IndexedBatch1 \
  IndexedHighD2Certificates/GeneratedBatch1 \
  AggregateTargetInventory/EventAudit/IndexedBatch2 \
  IndexedHighD2Certificates/GeneratedBatch2 \
  AggregateTargetInventory/EventAudit/IndexedBatch3 \
  IndexedHighD2Certificates/GeneratedBatch3 \
  AggregateTargetInventory/EventAudit/IndexedBatch4 \
  AggregateThreeProductConditional/Basic \
  AggregateThreeProductConditional/Data \
  AggregateThreeProductConditional/Events \
  AggregateThreeProductConditional/Matches \
  AggregateThreeProductConditional/Pipeline/Trace3744 \
  AggregateThreeProductConditional/Pipeline/Executable3744 \
  AggregateThreeProductConditional/Pipeline/Trace3745 \
  AggregateThreeProductConditional/Pipeline/Executable3745 \
  IndexedHighD2Certificates/GeneratedBatch4 \
  AggregateTargetInventory/EventAudit/IndexedBatch5 \
  IndexedHighD2Certificates/GeneratedBatch5 \
  AggregateTargetInventory/EventAudit/IndexedBatch6 \
  IndexedHighD2Certificates/GeneratedBatch6 \
  AggregateTargetInventory/EventAudit/IndexedBatch7 \
  IndexedHighD2Certificates/GeneratedBatch7 \
  AggregateTargetInventory/EventAudit/IndexedBatch8 \
  IndexedHighD2Certificates/GeneratedBatch8 \
  AggregateHighD2Conditional/Events \
  AggregateHighD2Conditional/Matches \
  AggregateHighD2Conditional/Pipeline/Trace6651 \
  AggregateHighD2Conditional/Pipeline/Executable6651 \
  AggregateHighD2Conditional/Pipeline/Trace7007 \
  AggregateHighD2Conditional/Pipeline/Executable7007 \
  AggregateHighD2Conditional/Pipeline/Trace7162 \
  AggregateHighD2Conditional/Pipeline/Executable7162 \
  AggregateHighD2Conditional/Pipeline/Trace7247 \
  AggregateHighD2Conditional/Pipeline/Executable7247 \
  IndexedHighD2Certificates/GeneratedBatch9 \
  IndexedHighD2Certificates/GeneratedAll \
  IndexedD5Certificates/Events \
  AggregateEliminationCertificates/Data \
  AggregateEliminationCertificates/Targets \
  AggregateHighD2Conditional \
  AggregateIncomingTargetCompletion/Data \
  AggregateIncomingTargetCompletion/Family \
  AggregateIncomingTargetCompletion/Targets \
  Row3743Successor/Data \
  Row3743Successor/Basic \
  Row3743Successor/Links \
  Row3743Successor/Named \
  AggregateIncomingTargetCompletion/FinalData \
  AggregateIncomingTargetCompletion/FinalFamily \
  AggregateIncomingTargetCompletion/FinalTarget \
  IndexedFamilyCertificates/RequestImport \
  AggregateIncomingTargetCompletion/Bundle \
  AggregateTargetInventory/EventAudit/SamePage \
  AggregateTargetInventory/EventAudit/TrajectoryNonboundary \
  AggregateTargetInventory/EventAudit/FiniteAPI \
  AggregateTargetInventory/EventAudit/Certificates \
  AggregateTargetInventory/EventAudit/APIExamples \
  AggregateTargetInventory/EventAudit/ExecutableExamples \
  AggregateTargetInventory/EventAudit/ExecutableBatch0 \
  AggregateTargetInventory/EventAudit/ExecutableBatch1 \
  AggregateTargetInventory/EventAudit/ExecutableBatch2 \
  AggregateTargetInventory/EventAudit/ExecutableBatch3 \
  AggregateTargetInventory/EventAudit/ExecutableBatch4 \
  AggregateTargetInventory/EventAudit/ExecutableBatch5 \
  AggregateTargetInventory/EventAudit/ExecutableBatch6 \
  AggregateTargetInventory/EventAudit/ExecutableBatch7 \
  AggregateTargetInventory/EventAudit/ExecutableBatch8 \
  AggregateTargetInventory/EventAudit/ExecutableAll \
  AggregateTargetInventory/EventAudit/IndexedAll \
  AggregateTargetInventory/EventAudit/IndexedExamples \
  AggregateTargetInventory \
  AggregateTargetInventory/EventAudit/IndexedDiagnosticsTests \
  AggregateThreeProductConditional \
  AggregateTwoDetectorConditional/Basic \
  AggregateTwoDetectorConditional/Data \
  AggregateTwoDetectorConditional/Events \
  AggregateTwoDetectorConditional/Matches \
  AggregateTwoDetectorConditional \
  AllClaimC2ConditionalCertificates/Data \
  AllClaimC2ConditionalCertificates/Matches \
  AllClaimC2ConditionalCertificates \
  AllClaimConditionalZeroCertificates/Data \
  AllClaimConditionalZeroCertificates/Matches \
  AllClaimConditionalZeroCertificates \
  AllClaimLeibnizConditionalCertificates \
  AllClaimPrefixConditionalCertificates/Data \
  AllClaimPrefixConditionalCertificates/Matches \
  AllClaimPrefixConditionalCertificates \
  AllClaimZeroTargetCertificates/Data \
  AllClaimZeroTargetCertificates \
  BranchReplayCertificates/D154545 \
  BranchReplayCertificates/D154545Leaves \
  BranchReplayCertificates \
  CnuPageCertificates \
  DerivedMapCertificates/Basic \
  DerivedMapCertificates/Import \
  CofiberE2Certificates/Basic \
  CofiberE2Certificates/Transport \
  CofiberE2Certificates \
  CofiberE2Certificates/CheckFile \
  CofiberE2Certificates/Counterexamples \
  CofiberE2Certificates/Linkage \
  CofiberE2Certificates/Tests \
  CofiberE2Certificates/TransportExample \
  DerivedMapCertificates/Linkage \
  DerivedMapCertificates \
  DerivedMapCertificates/CheckFile \
  DerivedMapCertificates/Counterexample \
  DerivedMapCertificates/Tests \
  DiagnosticTacticReview/Examples \
  GeneralizedLeibnizAudit/RepresentativeSquare \
  RepresentativeSquareCertificates/Basic \
  FilteredRepresentativeCrossing/Basic \
  FilteredMapExtension/Basic \
  FilteredExtensionCertificates/Basic \
  FilteredMapExtension/NextPage \
  FilteredMapExtension/TargetNext \
  FilteredMapExtension/Examples \
  FilteredMapExtension/TargetExamples \
  FilteredMapExtension/Crossing \
  FilteredCrossingCertificates/Basic \
  RepresentativeSquareCertificates/Import \
  FilteredExtensionCertificates/Import \
  FilteredCrossingCertificates/Import \
  FilteredCrossingCertificates/Examples \
  DiagnosticTacticReview/Actual \
  EtaD3Source/Semantics \
  ExtComplexCertificates/Basic \
  ExtComplexCertificates/Equivariant \
  ExtComplexCertificates/Presentation \
  MilnorCertificates/Basic \
  MilnorCertificates/Import \
  MilnorCertificates/Examples \
  ExtComplexCertificates/MilnorAction \
  ExtComplexCertificates/SqOneResolution \
  ExtComplexCertificates/ActualResolution \
  ExtComplexCertificates/RawResolutionExample \
  ResolutionCertificates/Import \
  ExtComplexCertificates/FiniteExactness \
  ExtComplexCertificates/ExactnessTactic \
  ExtComplexCertificates/MinimalHom \
  MilnorCertificates/Grading \
  MilnorCertificates/Frobenius \
  MilnorCertificates/GeneratorEvaluation \
  MilnorCertificates/FoldEvaluation \
  MilnorCertificates/WindowSoundness \
  MilnorCertificates/RankStability \
  MilnorCertificates/Coassociativity \
  MilnorCertificates/TriangleReindex \
  MilnorCertificates/IteratedEvaluation \
  MilnorCertificates/ExponentEncoding \
  MilnorCertificates/PolynomialExtraction \
  MilnorCertificates/GeneralTactic \
  MilnorCertificates/DualAlgebra \
  MilnorCertificates/Counit \
  MilnorCertificates/Unit \
  MilnorCertificates/BundledDual \
  ExtComplexCertificates/ActualResolutionRing \
  ExtComplexCertificates/ActualModuleComplex \
  MilnorCertificates/HomogeneousCoordinates \
  ExtComplexCertificates/ActualHomogeneousCoordinates \
  ExtComplexCertificates/ActualDifferentialCoordinates \
  ExtComplexCertificates/ActualExactnessExamples \
  ExtComplexCertificates/ActualHomogeneousExactness \
  ExtComplexCertificates/ActualAugmentation \
  ExtComplexCertificates/ActualAugmentationHom \
  ExtComplexCertificates/ActualHomCohomology \
  MilnorCertificates/GradedDual \
  MilnorCertificates/FinitePolynomialAlgebra \
  ExtComplexCertificates/ActualFiniteModule \
  ExtComplexCertificates/ActualFiniteExactness \
  ExtComplexCertificates/ActualFiniteHom \
  ExtComplexCertificates/ActualDegreeComplex \
  ExtComplexCertificates/ActualDegreeExactness \
  ExtComplexCertificates/ActualProjectiveComplex \
  ExtComplexCertificates/ActualChainAugmentation \
  ExtComplexCertificates/ActualChainHomology \
  ExtComplexCertificates/GenericFreeComplex \
  ExtComplexCertificates/GenericFreeComplexImport \
  ExtComplexCertificates/GenericHomogeneousCoordinates \
  ExtComplexCertificates/GenericDifferentialCoordinates \
  ExtComplexCertificates/GenericComponentImport \
  ExtComplexCertificates/GenericComponentExactness \
  ExtComplexCertificates/GenericComponentDiagnostics \
  ExtComplexCertificates/GenericAugmentationHom \
  ExtComplexCertificates/GenericAugmentationImport \
  ExtComplexCertificates/GenericCheckDecomposition \
  ExtComplexCertificates/GenericAugmentedExactness \
  ExtComplexCertificates/GenericAugmentedHomology \
  ExtComplexCertificates/GenericAugmentedImport \
  ExtComplexCertificates/GenericAugmentedLineImport \
  ExtComplexCertificates \
  ExtComplexCertificates/ActualResolutionExamples \
  ExtComplexCertificates/CheckAugmentedFile \
  ExtComplexCertificates/EquivariantExamples \
  ExtComplexCertificates/Examples \
  ExtComplexCertificates/GenericFreeComplexProducerExample \
  ExtComplexCertificates/GenericComponentExamples \
  ExtComplexCertificates/GenericAugmentationExamples \
  ExtComplexCertificates/GenericAugmentedExamples \
  ExtComplexCertificates/GenericAugmentedImportTests \
  ExtComplexCertificates/GenericAugmentedProducerExample \
  ExtComplexCertificates/GenericAugmentedReviewTests \
  GenericComponentT8/Sliced/DataOnly \
  ExtComplexCertificates/GenericAugmentedT8/Case0 \
  ExtComplexCertificates/GenericAugmentedT8/Case1 \
  ExtComplexCertificates/GenericAugmentedT8/Case2 \
  ExtComplexCertificates/GenericAugmentedT8/Case3 \
  ExtComplexCertificates/GenericAugmentedT8/Case4 \
  ExtComplexCertificates/GenericAugmentedT8/Case5 \
  ExtComplexCertificates/GenericAugmentedT8/Case6 \
  ExtComplexCertificates/GenericAugmentedT8/Case7 \
  ExtComplexCertificates/GenericAugmentedT8/Case8 \
  ExtComplexCertificates/GenericComponentTests \
  ExtComplexCertificates/GenericFreeComplexImportTests \
  ExtComplexCertificates/GenericFreeComplexProducerTests \
  ExtComplexCertificates/MinimalHomDimensions \
  ExtComplexCertificates/PresentationExamples \
  ExtComplexCertificates/RawParserTests \
  Fact713C2Row3005/MapImport \
  Fact713C2Row3005/MapImported \
  Fact713C2Row3005 \
  Fact713C2Row3143/MapImport \
  Fact713C2Row3143/MapImported \
  Fact713C2Row3143 \
  Fact713ComparisonBatches/Coverage \
  Fact713ConstructedE8/Branches \
  Fact713ConstructedE8/Request \
  Fact713CppCoordinateChoices/Data \
  Fact713Ctheta4Certificates/Basic \
  Fact713Ctheta4Certificates/Data \
  Fact713Ctheta4Certificates/Obstruction \
  Fact713Ctheta4Certificates \
  ModuleToModuleCertificates/RingRelations \
  Fact713D4SourceSearch/MapSemantics \
  Fact713DC2h6ComparisonFamily/Coverage \
  Fact713DC2h6ComparisonFamily/GraphData \
  Fact713DC2h6ComparisonFamily/GraphPartitions \
  Fact713DC2h6ComparisonFamily/GraphDisjoint \
  Fact713DC2h6ComparisonFamily/GraphCoverage \
  Fact713DC2h6ComparisonFamily/GraphParserTests \
  Fact713DC2h6Source/CoordinateBridge \
  Fact713DC2h6Source/MapSemantics \
  Fact713E12Search/Successor \
  Fact713E12Search/SuccessorData \
  Fact713E12Search/ZeroTargets \
  Row3305H0Search/Data \
  Row3305H0Search/Basic \
  Row3305H0Search/Actual \
  Row3136SquareCandidates/Data \
  Row3136SquareCandidates/Basic \
  Row3136SquareCandidates/Actual \
  Row3305H0Search/Assembly \
  Row3136SquareCandidates/Parameters \
  Row3136FamilyBranches/Data \
  Row3136FamilyBranches/ZeroA0Extra \
  Row3136FamilyBranches/ZeroA0Cross \
  Fact713FourBranchContinuation/ZeroA0 \
  Row3136FamilyBranches/ZeroA1Extra \
  Row3136FamilyBranches/ZeroA1Cross \
  Fact713FourBranchContinuation/ZeroA1 \
  Row3136FamilyBranches/ResidualA0Extra \
  Row3136FamilyBranches/ResidualA0Cross \
  Fact713FourBranchContinuation/ResidualA0 \
  Row3136FamilyBranches/ResidualA1Extra \
  Row3136FamilyBranches/ResidualA1Cross \
  Fact713FourBranchContinuation/ResidualA1 \
  Row3136FamilyBranches/Branches \
  Row3136FamilyBranches/CoordinateBridge \
  Row3136FamilyBranches/Actual \
  Fact713FourBranchContinuation/Branches \
  Fact713Row3143Continuation/ActualRule \
  Fact713FourBranchContinuation/Actual \
  Fact713FourBranchContinuation/Request \
  Fact713NextComparisonFamily/Coverage \
  Fact713NextD3Continuation/ActualRules \
  Fact713NextSourceSearch/MapSemantics \
  Fact713PageCertificates \
  Fact713RefinedComparisonFamily/Coverage \
  Fact713Row2431Continuation/ActualRule \
  Fact713Row2431Search/MapSemantics \
  Fact713Row2431Search/Tactic \
  Fact713Row2773ComparisonFamily/Coverage \
  Fact713Row2916Search/MapSemantics \
  Fact713Row2916Search/Tactic \
  Fact713Row2994Constraint/MapSemantics \
  Fact713Row3247Boundaries/Whole \
  Fact713Row3247Source/Binding \
  Fact713Row3247Source/MapSemantics \
  Fact713TrajectoryCertificates \
  Fact715ConstructedActual/Detector \
  Fact715ConstructedActual/Tactic \
  Fact715ConstructedActual/Assembly \
  Fact715PageCertificates \
  Fact715TrajectoryCertificates/MapSemantics \
  Fact715TrajectoryCertificates \
  Fact715TrajectoryCertificates/Generated \
  Fact715TrajectoryCertificates/MapImport \
  Fact715TrajectoryCertificates/MapImported \
  Fact715TrajectoryCertificates/MapShapeTests \
  Fact719ConstructedActual/Tactic \
  Fact719PageCertificates \
  Fact719TrajectoryCertificates \
  Fact721ConstructedActual/Tactic \
  Fact721FirstD4Continuation/ActualRule \
  Fact721FirstD4Search/MapSemantics \
  Fact721FirstD4Search/Tactic \
  Fact721PageCertificates \
  Fact761PageCertificates \
  Fact762CsigmasqD5/Maps \
  Fact762CsigmasqD5/Comparison \
  Fact762CsigmasqD5/Descent \
  Fact762CsigmasqD5/Source \
  Fact762CsigmasqD5/Target \
  Fact762CsigmasqD5/Actual \
  NamedElementCertificates/ModuleImport \
  Fact762CsigmasqD5/D2 \
  Fact762CsigmasqD5/D2Data \
  Fact762CsigmasqD5/D2Links \
  Fact762CsigmasqD5/Tests \
  Fact762IncomingCertificates/Source8 \
  Fact762IncomingCertificates/Tests \
  Fact762PageCertificates \
  Fact762Source7Certificates/Inputs \
  Fact763PageCertificates \
  Fact764TrajectoryAudit/Generated \
  Fact764TrajectoryAudit/Row3564 \
  Fact764TrajectoryAudit/MapImport \
  Fact764TrajectoryAudit/MapImported \
  Fact764TrajectoryAudit/MapActual \
  Fact764TrajectoryAudit/MapComparison \
  Fact764TrajectoryAudit/MapSemantics \
  Fact764TrajectoryAudit/C2Naturality \
  Fact764TrajectoryAudit/LaterDetector \
  Fact764TrajectoryAudit \
  FamilyKeyOrder/Examples \
  FilteredExtensionCertificateCompleteness/Linear \
  FilteredExtensionCertificateCompleteness/Basic \
  FilteredCrossingCertificateCompleteness/Basic \
  FilteredExtensionCertificateCompleteness/Search \
  FilteredExtensionCertificateCompleteness/Examples \
  FilteredCrossingCertificateCompleteness/Search \
  FilteredExtensionCertificates/Batch00 \
  FilteredExtensionCertificates/Batch01 \
  FilteredExtensionCertificates/Batch02 \
  FilteredExtensionCertificates/Batch03 \
  FilteredExtensionCertificates/Batch04 \
  FilteredExtensionCertificates/Batch05 \
  FilteredExtensionCertificates/Batch06 \
  FilteredExtensionCertificates/Batch07 \
  FilteredExtensionCertificates/Batch08 \
  FilteredExtensionCertificates/Batch09 \
  FilteredExtensionCertificates/Batch10 \
  FilteredExtensionCertificates/Batch11 \
  FilteredExtensionCertificates/Batch12 \
  FilteredExtensionCertificates/Batch13 \
  FilteredExtensionCertificates/Batch14 \
  FilteredExtensionCertificates/Batch15 \
  FilteredExtensionCertificates/Diagnostic \
  FilteredExtensionCertificates/Direct \
  FilteredExtensionCertificates/Examples \
  FilteredMapGradedComparison/Basic \
  FilteredExtensionSquare/Basic \
  FilteredMapGradedComparison/Event \
  FilteredMapGradedComparison/Recurrence \
  FilteredMapGradedComparison/AllTargets \
  FilteredTwoTermSequence/Algebra \
  FilteredTwoTermSequence/Basic \
  FilteredTwoTermSequence/Homology \
  FilteredExtensionPageBridge/Basic \
  FilteredExtensionPageBridge/Crossing \
  FilteredExtensionPageBridge/Certificate \
  FilteredExtensionPageBridge/Import \
  FilteredExtensionSquare/Square \
  FilteredExtensionSquare/Examples \
  FilteredExtensionPageBridge/Examples \
  FilteredExtensionReview/Import \
  FilteredExtensionReview/Negative00 \
  FilteredExtensionReview/Negative01 \
  FilteredExtensionReview/Negative02 \
  FilteredExtensionReview/Negative03 \
  FilteredExtensionReview/Negative04 \
  FilteredExtensionReview/Negative05 \
  FilteredExtensionReview/Negative06 \
  FilteredExtensionReview/Negative07 \
  FilteredExtensionReview/Negative08 \
  FilteredExtensionReview/Negative09 \
  FilteredExtensionReview/Negative10 \
  FilteredExtensionReview/Negative11 \
  FilteredExtensionReview/Negative12 \
  FilteredExtensionReview/Negative13 \
  FilteredExtensionReview/Negative \
  FilteredExtensionReview/Nonzero \
  FilteredMapKernelGraded/Basic \
  FilteredMapCokernelGraded/Basic \
  FilteredMapCokernelGraded/Conditions \
  FilteredTwoTermLimit/Basic \
  FilteredFiniteSourceLimit/Basic \
  FilteredFiniteSourceLimit/Examples \
  FilteredMapKernelGraded/Examples \
  FilteredLateDifferential/Basic \
  FilteredMapCokernelGraded/Examples \
  FilteredMapGradedComparison/Examples \
  FilteredMapGradedReview/Examples \
  FilteredRepresentativeCrossing/Counterexamples \
  FilteredTwoTermNaturality/Basic \
  FiniteFilteredSquareCertificates/Basic \
  FiniteFilteredSquareCertificateCompleteness/Basic \
  FilteredSquareNaturalityCertificate/Basic \
  FiniteFilteredSquareCertificates/Import \
  FiniteFilteredSquareProducer/Batch00 \
  FiniteFilteredSquareProducer/Batch01 \
  FiniteFilteredSquareProducer/Batch02 \
  FiniteFilteredSquareProducer/Batch03 \
  FiniteFilteredSquareProducer/Batch04 \
  FiniteFilteredSquareProducer/Batch05 \
  FiniteFilteredSquareProducer/Batch06 \
  FiniteFilteredSquareProducer/Batch07 \
  FiniteFilteredSquareProducer/Batch08 \
  FiniteFilteredSquareProducer/Batch09 \
  FiniteFilteredSquareProducer/Batch10 \
  FiniteFilteredSquareProducer/Batch11 \
  FiniteFilteredSquareProducer/Batch12 \
  FiniteFilteredSquareProducer/Batch13 \
  FiniteFilteredSquareProducer/Batch14 \
  FiniteFilteredSquareProducer/Batch15 \
  FiniteFilteredSquareProducer/Batch16 \
  FiniteFilteredSquareProducer/Batch17 \
  FiniteFilteredSquareProducer/Batch18 \
  FiniteFilteredSquareProducer/Batch19 \
  FiniteFilteredSquareProducer/Batch20 \
  FiniteFilteredSquareProducer/Batch21 \
  FiniteFilteredSquareProducer/Imported \
  FiniteFilteredSquareCertificates/Examples \
  FilteredSquareNaturalityCertificate/Examples \
  FilteredSquarePageBridge/Basic \
  FilteredSquarePageBridge/Import \
  FilteredSquarePageBridge/Examples \
  FilteredTwoTermNaturality/Laws \
  FilteredTwoTermNaturality/Examples \
  FiniteFilteredSquareCompletenessLimit/Counterexample \
  HighFiltrationD2Certificates/Tests \
  HighFiltrationD2Certificates \
  IndexedD5Certificates \
  IndexedFamilyCertificates/Tests \
  IndexedFamilyCertificates/ResultExamples \
  IndexedFamilyCertificates/SemanticTransport \
  IndexedFamilyCertificates/GeneratedFamily \
  IndexedFamilyCertificates/GeneratedBatch0 \
  IndexedFamilyCertificates/GeneratedBatch1 \
  IndexedFamilyCertificates/GeneratedBatch2 \
  IndexedFamilyCertificates/GeneratedBatch3 \
  IndexedFamilyCertificates/GeneratedBatch4 \
  IndexedFamilyCertificates/GeneratedBatch5 \
  IndexedFamilyCertificates/GeneratedBatch6 \
  IndexedFamilyCertificates/GeneratedBatch7 \
  IndexedFamilyCertificates/GeneratedBatch8 \
  IndexedFamilyCertificates/GeneratedAll \
  IndexedFamilyCertificates/GeneratedEntries \
  IndexedFamilyCertificates/GeneratedPairs00 \
  IndexedFamilyCertificates/GeneratedPairs01 \
  IndexedFamilyCertificates/GeneratedPairs02 \
  IndexedFamilyCertificates/GeneratedPairs03 \
  IndexedFamilyCertificates/GeneratedPairs04 \
  IndexedFamilyCertificates/GeneratedPairs05 \
  IndexedFamilyCertificates/GeneratedPairs06 \
  IndexedFamilyCertificates/GeneratedPairs07 \
  IndexedFamilyCertificates/GeneratedPairs08 \
  IndexedFamilyCertificates/GeneratedPairs09 \
  IndexedFamilyCertificates/GeneratedPairs10 \
  IndexedFamilyCertificates/GeneratedPairs11 \
  IndexedFamilyCertificates/GeneratedPairs12 \
  IndexedFamilyCertificates/GeneratedPairs13 \
  IndexedFamilyCertificates/GeneratedCoherence \
  IndexedFamilyCertificates \
  IndexedFamilyCertificates/CheckFile \
  IndexedFamilyCertificates/RequestCheckFile \
  IndexedFamilyNeighborCheck/Examples \
  IndexedHighD2Certificates/Example \
  IndexedHighD2Certificates/RequestExample \
  IndexedHighD2Certificates \
  KervaireProgram/Model \
  KervaireProgram/Certificate \
  KervaireProgram/Checker \
  KervaireProgram/KervaireClaims \
  KervaireProgram/Import \
  KervaireProgram \
  LinProgramCertificates/CertificateFormat \
  LinProgramCertificates \
  LinProgramCertificates/KervaireTactic \
  LinProgramCertificates/Examples \
  LinearCertificates \
  LinearCertificates/CheckMain \
  LinearCertificates/Examples \
  LinearCertificates/GeneratedExamples \
  LinearCertificates/ImportExamples \
  LinearCertificates/ParserExamples \
  MilnorCertificates/StableProduct \
  MilnorCertificates/StableTactic \
  MilnorCertificates \
  MilnorCertificates/CheckAllFile \
  MilnorCertificates/CheckFile \
  MilnorCertificates/FileExample \
  MilnorCertificates/GeneralImportedExample \
  MilnorCertificates/ImportedExample \
  ModuleMapCertificates/MatrixImport \
  ModuleMapCertificates/MatrixUse \
  ModuleMapCertificates \
  ModuleMapCertificates/Actual \
  ModuleMapCertificates/MatrixDiagnostics \
  ModuleMapCertificates/CheckMatrixFile \
  ModuleMapCertificates/MatrixActual \
  ModuleMapCertificates/DiagnosticsTests \
  ModuleMapCertificates/Imported \
  ModuleMapCertificates/ImportTests \
  ModuleMapCertificates/MatrixTests \
  ModuleMapCertificates/Tests \
  ModuleToModuleCertificates \
  ModuleToModuleCertificates/Actual \
  ModuleToModuleCertificates/CheckFile \
  ModuleToModuleCertificates/GeneralActual \
  ModuleToModuleCertificates/GeneralTests \
  ModuleToModuleCertificates/RingTarget \
  ModuleToModuleCertificates/ShiftedActual \
  ModuleToModuleCertificates/SentinelTests \
  ModuleToModuleCertificates/ShiftedTests \
  ModuleToModuleCertificates/Tests \
  ModuleToModuleCertificates/WireTests \
  NamedElementCertificates \
  NamedElementCertificates/EvaluationExamples \
  NamedElementCertificates/Fact713 \
  NamedElementCertificates/ModuleExported \
  NamedElementCertificates/ModuleImportExamples \
  NamedElementCertificates/Tests \
  NamedPageComparison/Row2858/Semantics_g \
  NamedPageComparison/Row2858/Semantics_h1 \
  NamedPageComparison/Row2858/Semantics_h3 \
  NamedPageComparison/Row2858/Products_h0 \
  NamedPageComparison/Row2858/H1Zero \
  NamedPageComparison/Row2858/Derivation \
  NamedPageComparison/Row2858/Assemble \
  NamedPageComparison \
  OutgoingCycleCertificates/CheckFile \
  OutgoingCycleCertificates/ImportExamples \
  OutgoingCycleMapTransport/Basic \
  OutgoingCycleMapTransport/Hit \
  OutgoingCycleMapTransport/Filtration \
  OutgoingCycleMapTransport/Fact762 \
  PermanentCycleCertificates/Counterexamples \
  OutgoingCycleMapTransport/Examples \
  PageCertificates/Model \
  PageCertificates/Checker \
  PageCertificates/Import \
  PageCertificates \
  PageCertificates/CheckMain \
  PageCertificates/Examples \
  PageProductCertificates/ActualH0 \
  PageProductCertificates/H1QuotientLeibniz \
  PageProductCertificates \
  PageProductCertificates/CheckFile \
  PageProductCertificates/Generated \
  PageTransitionCertificates/InducedImport \
  PageTransitionCertificates \
  PageTransitionCertificates/CheckFile \
  PageTransitionCertificates/Examples \
  PageTransitionCertificates/ImportExamples \
  PageTransitionCertificates/InducedExamples \
  PageTransitionCertificates/InducedImportExamples \
  PageTransitionCertificates/ParserExamples \
  PageTransitionCertificates/TrajectoryExamples \
  PageTransitionCertificates/TrajectoryGenerated \
  PageTransitionCertificates/TrajectoryImportExamples \
  PermanentCycleCertificates/CheckFile \
  SemanticTrajectoryCertificates/Examples \
  SemanticTrajectoryCertificates/Counterexamples \
  SemanticTrajectoryCertificates \
  Row2796D5Detector/MapSemantics \
  Row2796D5Detector/Tests \
  Row2796D5Detector/CurrentImports \
  Row2796D5Detector \
  Row3020Detector \
  Row3019Detector/MapSemantics \
  Row3019Detector/Tests \
  Row3019Detector/CurrentImports \
  Row3019Detector \
  Row2695Detector/MapSemantics \
  Row2695Detector/Tests \
  Row2695Detector/CurrentImports \
  Row2695Detector \
  Row2861D4Detector/MapSemantics \
  Row2861D4Detector/Tests \
  Row2861D4Detector/CurrentImports \
  Row2861D4Detector \
  Row2929Detector/MapSemantics \
  Row2929Detector/Tests \
  Row2929Detector/CurrentImports \
  Row2929Detector \
  Row2576D4Detector/MapSemantics \
  Row2576D4Detector/Tests \
  Row2576D4Detector/CurrentImports \
  Row2576D4Detector \
  Step4ContractAudit/FiniteBoundaryTests \
  Step4ContractAudit/ImportTests \
  Step4ContractAudit/ConditionalPremiseTests \
  Step4ContractAudit \
  Row2576Detector/MapSemantics \
  Row2576Detector/ProductSemantics \
  Row2576Detector/Tests \
  Row2576Detector/CurrentImports \
  Row2576Detector \
  Row2925Detector/Semantics \
  Row2925Detector \
  Row3325Detector \
  Row2796D4Detector \
  Row2574Detector \
  Row2796Detector/Restriction \
  Row2796Detector \
  Row2861Csigma \
  ResolutionCertificates \
  PropagationCertificates/Rules \
  PropagationCertificates/Import \
  PropagationCertificates/Tactic \
  PropagationCertificates/Branches \
  PropagationCertificates/MatrixNaturality \
  PropagationCertificates \
  StaircaseCertificates/Import \
  StaircaseCertificates/Survival \
  StaircaseCertificates/Coherence \
  StaircaseCertificates \
  RealMapCertificates/MatrixSemantics \
  RealMapCertificates/MatrixImport \
  RealMapCertificates \
  SemilinearMapCertificates/Basic \
  SemilinearMapCertificates/Import \
  SemilinearMapCertificates/AllVectors \
  ProofAudit \
  Prop79IncomingSearch/MapSemantics \
  Prop79TargetSearch/Maps \
  Prop79TargetSearch/Comparison \
  Prop79TargetSearch/Naturality \
  Prop79TargetSearch/Actual \
  Prop79TargetSearch/DerivedStep \
  Prop79TargetSearch/Tactic \
  Prop79TargetSearch/Assembly \
  Prop79NeighborCoordinates/Basic \
  Prop79NeighborCoordinates/Assembly \
  Prop79TargetSearch/MapSemantics \
  PropagationCertificates/Examples \
  PropagationCertificates/Main \
  Proposition78Certificates/Reduction \
  Proposition78Certificates \
  RealMapCertificates/Generated \
  RealMapCertificates/SemanticCheck \
  RealMapCertificates/SemanticExamples \
  RealMapCertificates/SemanticTests \
  RealMapCertificates/Tests \
  RepresentativeSquareCertificates/Examples \
  RepresentativeSquareProducer/Imported \
  ResolutionCertificates/CheckFile \
  ResolutionCertificates/Examples \
  Row2693Detector \
  Row2773D4Leibniz/Semantics \
  Row2773Leibniz/Semantics \
  Row2907PDeltaDetection/Data \
  Row2907PDeltaDetection/Basic \
  Row2907PDeltaDetection/Descent \
  Row2907PDeltaDetection/Actual \
  Row2907PDeltaDetection/Branches \
  Row2907PDeltaDetection/D2Links \
  Row2907PDeltaDetection/Semantics \
  Row2907PDeltaDetection/Tactic \
  Row2916D4Search/Maps \
  Row2916D4Search/Comparison \
  Row2916D4Search/Finite \
  Row2916D4Search/Actual \
  Row2916D4Search/Assembly \
  Row2916D4Search/Binding \
  Row2916D4Search/Semantics \
  Row2916D4Search/Tactic \
  Row2925Detector/Tests \
  Row2925EtaD4/ProductSemantics \
  Row2925EtaD4/TwoBranches \
  Row3135H0Leibniz/Semantics \
  Row3143D0Leibniz/Semantics \
  Row3143D0Leibniz/Tactic \
  Row3147Detector/Products_h0 \
  Row3147Detector/Products_h1 \
  Row3147Detector/Products_h3 \
  Row3147Detector/Products_g \
  Row3147Detector/Obstruction \
  Row3147Detector \
  Row3305H0Search/Semantics \
  SemanticTrajectoryCertificates/Request \
  SemanticTrajectoryCertificates/D5All \
  SemanticTrajectoryCertificates/IndexedExample \
  SemanticTrajectoryCertificates/RequestExample \
  SemilinearMapCertificates \
  SemilinearMapCertificates/Actual \
  SemilinearMapCertificates/DiagnosticsTests \
  SemilinearMapCertificates/Tests \
  StaircaseCertificates/CheckMain \
  StaircaseCertificates/Named \
  StaircaseCertificates/FiniteClaims \
  StaircaseCertificates/CoherenceExamples \
  StaircaseCertificates/QueryExamples \
  Stem125E4Search/Branches \
  Stem125E4Search/Family \
  Stem125HomologyCertificates/D4 \
  Stem125HomologyCertificates/MeaningCounterexamples \
  UniqueHomologyCertificates/CheckFile; do
  echo "Checking $module"
  mkdir -p ".lake/build/lib/lean/$(dirname "$module")"
  "$LEAN_SYSROOT/bin/lean" -j1 "$module.lean" -o ".lake/build/lib/lean/$module.olean"
done
