import KIPBase.StableHomotopy.SphereAdamsDifferentials

/-!
Generated by KIPBase/SphereAdamsProofs.generate.py; do not edit by hand.
Zenodo 14875701 / v126.3.cw49. Results only: no proof replay.
Concrete E2 labels and provenance only. Named axioms are in SphereAdamsProofs/Axiom.lean.
The companion JSON contains full database records and source hashes.
-/

set_option maxRecDepth 16384

namespace KIPBase.StableHomotopy.SphereAdamsProofs

open KIPBase.SphereE2 SphereAdamsDifferentials

/-- File identity is pinned; this metadata is not a proof certificate. -/
structure Provenance where
  dataset : String
  file : String
  sha256 : String
  table : String
  rowId : Nat
  reason : String
  paper : String
  sourceS : Nat
  sourceT : Nat
  page : Nat
  sourceIndices : List Nat
  targetIndices : List Nat
  outgoingSSRow : Nat
  incomingSSRow : Nat

/-- Fact 7.13(2); proofs.db:log.id=5990. -/
def d2_x125_8_provenance : Provenance := {
  dataset := "https://zenodo.org/records/14875701 / v126.3.cw49"
  file := "proofs.db"
  sha256 := "3a460683c023ee2d8f7e8f904ecef9044a474d88bb7184731e54978ba7dac248"
  table := "log"
  rowId := 5990
  reason := "d2"
  paper := "Fact 7.13(2)"
  sourceS := 8
  sourceT := 133
  page := 2
  sourceIndices := [1]
  targetIndices := [2, 4]
  outgoingSSRow := 2630
  incomingSSRow := 2690 }

/-- (s,t)=(8,133), local basis indices [1]. -/
def d2_x125_8_source : CSV.Expression 8 133 :=
  (.gen ⟨375, by decide⟩)

/-- (s,t)=(10,134), local basis indices [2, 4]. -/
def d2_x125_8_target : CSV.Expression 10 134 :=
  (.add (.mul (.gen ⟨1, by decide⟩) (.gen ⟨366, by decide⟩)) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.gen ⟨367, by decide⟩))))

/-- Lemma 7.16, classical Toda bracket argument; proofs.db:log.id=5541. -/
def d2_h6_provenance : Provenance := {
  dataset := "https://zenodo.org/records/14875701 / v126.3.cw49"
  file := "proofs.db"
  sha256 := "3a460683c023ee2d8f7e8f904ecef9044a474d88bb7184731e54978ba7dac248"
  table := "log"
  rowId := 5541
  reason := "d2"
  paper := "Lemma 7.16, classical Toda bracket argument"
  sourceS := 1
  sourceT := 64
  page := 2
  sourceIndices := [0]
  targetIndices := [0]
  outgoingSSRow := 401
  incomingSSRow := 416 }

/-- (s,t)=(1,64), local basis indices [0]. -/
def d2_h6_source : CSV.Expression 1 64 :=
  (.gen ⟨69, by decide⟩)

/-- (s,t)=(3,65), local basis indices [0]. -/
def d2_h6_target : CSV.Expression 3 65 :=
  (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨18, by decide⟩) (.gen ⟨18, by decide⟩)))

/-- Lemma 7.14(1); proofs.db:log.id=153768. -/
def d3_h4_x109_12_provenance : Provenance := {
  dataset := "https://zenodo.org/records/14875701 / v126.3.cw49"
  file := "proofs.db"
  sha256 := "3a460683c023ee2d8f7e8f904ecef9044a474d88bb7184731e54978ba7dac248"
  table := "log"
  rowId := 153768
  reason := "D"
  paper := "Lemma 7.14(1)"
  sourceS := 13
  sourceT := 137
  page := 3
  sourceIndices := [2]
  targetIndices := [0]
  outgoingSSRow := 2917
  incomingSSRow := 3074 }

/-- (s,t)=(13,137), local basis indices [2]. -/
def d3_h4_x109_12_source : CSV.Expression 13 137 :=
  (.mul (.gen ⟨7, by decide⟩) (.gen ⟨275, by decide⟩))

/-- (s,t)=(16,139), local basis indices [0]. -/
def d3_h4_x109_12_target : CSV.Expression 16 139 :=
  (.mul (.gen ⟨1, by decide⟩) (.gen ⟨424, by decide⟩))

/-- Lemma 7.14(2); proofs.db:log.id=462481. -/
def d3_h0Sq_x123_13_2_provenance : Provenance := {
  dataset := "https://zenodo.org/records/14875701 / v126.3.cw49"
  file := "proofs.db"
  sha256 := "3a460683c023ee2d8f7e8f904ecef9044a474d88bb7184731e54978ba7dac248"
  table := "log"
  rowId := 462481
  reason := "N"
  paper := "Lemma 7.14(2)"
  sourceS := 15
  sourceT := 138
  page := 3
  sourceIndices := [2]
  targetIndices := [2]
  outgoingSSRow := 3002
  incomingSSRow := 3138 }

/-- (s,t)=(15,138), local basis indices [2]. -/
def d3_h0Sq_x123_13_2_source : CSV.Expression 15 138 :=
  (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.gen ⟨418, by decide⟩)))

/-- (s,t)=(18,140), local basis indices [2]. -/
def d3_h0Sq_x123_13_2_target : CSV.Expression 18 140 :=
  (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.gen ⟨437, by decide⟩)))

/-- Lemma 7.16; proofs.db:log.id=929469. -/
def d3_x126_4_provenance : Provenance := {
  dataset := "https://zenodo.org/records/14875701 / v126.3.cw49"
  file := "proofs.db"
  sha256 := "3a460683c023ee2d8f7e8f904ecef9044a474d88bb7184731e54978ba7dac248"
  table := "log"
  rowId := 929469
  reason := "N"
  paper := "Lemma 7.16"
  sourceS := 4
  sourceT := 130
  page := 3
  sourceIndices := [0]
  targetIndices := [0]
  outgoingSSRow := 2437
  incomingSSRow := 2572 }

/-- (s,t)=(4,130), local basis indices [0]. -/
def d3_x126_4_source : CSV.Expression 4 130 :=
  (.gen ⟨341, by decide⟩)

/-- (s,t)=(7,132), local basis indices [0]. -/
def d3_x126_4_target : CSV.Expression 7 132 :=
  (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.gen ⟨340, by decide⟩)))

/-- Lemma 7.14(2); proofs.db:log.id=2671068. -/
def d7_x123_11_combination_provenance : Provenance := {
  dataset := "https://zenodo.org/records/14875701 / v126.3.cw49"
  file := "proofs.db"
  sha256 := "3a460683c023ee2d8f7e8f904ecef9044a474d88bb7184731e54978ba7dac248"
  table := "log"
  rowId := 2671068
  reason := "D"
  paper := "Lemma 7.14(2)"
  sourceS := 11
  sourceT := 134
  page := 7
  sourceIndices := [0, 1, 3]
  targetIndices := [1]
  outgoingSSRow := 2687
  incomingSSRow := 3139 }

/-- (s,t)=(11,134), local basis indices [0, 1, 3]. -/
def d7_x123_11_combination_source : CSV.Expression 11 134 :=
  (.add (.gen ⟨387, by decide⟩) (.add (.gen ⟨386, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨69, by decide⟩) (.gen ⟨80, by decide⟩)))))

/-- (s,t)=(18,140), local basis indices [1]. -/
def d7_x123_11_combination_target : CSV.Expression 18 140 :=
  (.mul (.gen ⟨1, by decide⟩) (.gen ⟨436, by decide⟩))

/-- Lemma 7.16, classical Toda bracket argument; S0_AdamsSS_t261.db:S0_AdamsE2_basis.id=513. -/
def d2_h0Pow6_h6_provenance : Provenance := {
  dataset := "https://zenodo.org/records/14875701 / v126.3.cw49"
  file := "S0_AdamsSS_t261.db"
  sha256 := "518a2ed86af6d4f7bcdc5db135ab6252bd50df34492ae208663aa1c140a820ed"
  table := "S0_AdamsE2_basis"
  rowId := 513
  reason := "basis.d2"
  paper := "Lemma 7.16, classical Toda bracket argument"
  sourceS := 7
  sourceT := 70
  page := 2
  sourceIndices := [2]
  targetIndices := [0]
  outgoingSSRow := 513
  incomingSSRow := 528 }

/-- (s,t)=(7,70), local basis indices [2]. -/
def d2_h0Pow6_h6_source : CSV.Expression 7 70 :=
  (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.gen ⟨69, by decide⟩)))))))

/-- (s,t)=(9,71), local basis indices [0]. -/
def d2_h0Pow6_h6_target : CSV.Expression 9 71 :=
  (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨0, by decide⟩) (.mul (.gen ⟨18, by decide⟩) (.gen ⟨18, by decide⟩)))))))))

end KIPBase.StableHomotopy.SphereAdamsProofs
