import ExtComplexCertificates.FiniteExactness
open ExtComplexCertificates.ActualResolution ResolutionCertificates
set_option maxRecDepth 20000
set_option maxHeartbeats 10000000
def exactWire0_0 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-0.json"
theorem exactCase0_0 : ExactAt (augmentedOutgoing actualRows 0 0) (freeDifferential actualRows 0 0) := checkRawExact_sound _ _ _ exactWire0_0 (by decide)
def exactWire0_1 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-1.json"
theorem exactCase0_1 : ExactAt (augmentedOutgoing actualRows 0 1) (freeDifferential actualRows 0 1) := checkRawExact_sound _ _ _ exactWire0_1 (by decide)
def exactWire1_1 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-1.json"
theorem exactCase1_1 : ExactAt (augmentedOutgoing actualRows 1 1) (freeDifferential actualRows 1 1) := checkRawExact_sound _ _ _ exactWire1_1 (by decide)
def exactWire0_2 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-2.json"
theorem exactCase0_2 : ExactAt (augmentedOutgoing actualRows 0 2) (freeDifferential actualRows 0 2) := checkRawExact_sound _ _ _ exactWire0_2 (by decide)
def exactWire1_2 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-2.json"
theorem exactCase1_2 : ExactAt (augmentedOutgoing actualRows 1 2) (freeDifferential actualRows 1 2) := checkRawExact_sound _ _ _ exactWire1_2 (by decide)
def exactWire2_2 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-2-2.json"
theorem exactCase2_2 : ExactAt (augmentedOutgoing actualRows 2 2) (freeDifferential actualRows 2 2) := checkRawExact_sound _ _ _ exactWire2_2 (by decide)
def exactWire0_3 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-3.json"
theorem exactCase0_3 : ExactAt (augmentedOutgoing actualRows 0 3) (freeDifferential actualRows 0 3) := checkRawExact_sound _ _ _ exactWire0_3 (by decide)
def exactWire1_3 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-3.json"
theorem exactCase1_3 : ExactAt (augmentedOutgoing actualRows 1 3) (freeDifferential actualRows 1 3) := checkRawExact_sound _ _ _ exactWire1_3 (by decide)
def exactWire2_3 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-2-3.json"
theorem exactCase2_3 : ExactAt (augmentedOutgoing actualRows 2 3) (freeDifferential actualRows 2 3) := checkRawExact_sound _ _ _ exactWire2_3 (by decide)
def exactWire3_3 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-3-3.json"
theorem exactCase3_3 : ExactAt (augmentedOutgoing actualRows 3 3) (freeDifferential actualRows 3 3) := checkRawExact_sound _ _ _ exactWire3_3 (by decide)
def exactWire0_4 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-4.json"
theorem exactCase0_4 : ExactAt (augmentedOutgoing actualRows 0 4) (freeDifferential actualRows 0 4) := checkRawExact_sound _ _ _ exactWire0_4 (by decide)
def exactWire1_4 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-4.json"
theorem exactCase1_4 : ExactAt (augmentedOutgoing actualRows 1 4) (freeDifferential actualRows 1 4) := checkRawExact_sound _ _ _ exactWire1_4 (by decide)
def exactWire2_4 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-2-4.json"
theorem exactCase2_4 : ExactAt (augmentedOutgoing actualRows 2 4) (freeDifferential actualRows 2 4) := checkRawExact_sound _ _ _ exactWire2_4 (by decide)
def exactWire3_4 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-3-4.json"
theorem exactCase3_4 : ExactAt (augmentedOutgoing actualRows 3 4) (freeDifferential actualRows 3 4) := checkRawExact_sound _ _ _ exactWire3_4 (by decide)
def exactWire4_4 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-4-4.json"
theorem exactCase4_4 : ExactAt (augmentedOutgoing actualRows 4 4) (freeDifferential actualRows 4 4) := checkRawExact_sound _ _ _ exactWire4_4 (by decide)
def exactWire0_5 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-5.json"
theorem exactCase0_5 : ExactAt (augmentedOutgoing actualRows 0 5) (freeDifferential actualRows 0 5) := checkRawExact_sound _ _ _ exactWire0_5 (by decide)
def exactWire1_5 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-5.json"
theorem exactCase1_5 : ExactAt (augmentedOutgoing actualRows 1 5) (freeDifferential actualRows 1 5) := checkRawExact_sound _ _ _ exactWire1_5 (by decide)
def exactWire2_5 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-2-5.json"
theorem exactCase2_5 : ExactAt (augmentedOutgoing actualRows 2 5) (freeDifferential actualRows 2 5) := checkRawExact_sound _ _ _ exactWire2_5 (by decide)
def exactWire3_5 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-3-5.json"
theorem exactCase3_5 : ExactAt (augmentedOutgoing actualRows 3 5) (freeDifferential actualRows 3 5) := checkRawExact_sound _ _ _ exactWire3_5 (by decide)
def exactWire4_5 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-4-5.json"
theorem exactCase4_5 : ExactAt (augmentedOutgoing actualRows 4 5) (freeDifferential actualRows 4 5) := checkRawExact_sound _ _ _ exactWire4_5 (by decide)
def exactWire5_5 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-5-5.json"
theorem exactCase5_5 : ExactAt (augmentedOutgoing actualRows 5 5) (freeDifferential actualRows 5 5) := checkRawExact_sound _ _ _ exactWire5_5 (by decide)
def exactWire0_6 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-6.json"
theorem exactCase0_6 : ExactAt (augmentedOutgoing actualRows 0 6) (freeDifferential actualRows 0 6) := checkRawExact_sound _ _ _ exactWire0_6 (by decide)
def exactWire1_6 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-6.json"
theorem exactCase1_6 : ExactAt (augmentedOutgoing actualRows 1 6) (freeDifferential actualRows 1 6) := checkRawExact_sound _ _ _ exactWire1_6 (by decide)
def exactWire2_6 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-2-6.json"
theorem exactCase2_6 : ExactAt (augmentedOutgoing actualRows 2 6) (freeDifferential actualRows 2 6) := checkRawExact_sound _ _ _ exactWire2_6 (by decide)
def exactWire3_6 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-3-6.json"
theorem exactCase3_6 : ExactAt (augmentedOutgoing actualRows 3 6) (freeDifferential actualRows 3 6) := checkRawExact_sound _ _ _ exactWire3_6 (by decide)
def exactWire4_6 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-4-6.json"
theorem exactCase4_6 : ExactAt (augmentedOutgoing actualRows 4 6) (freeDifferential actualRows 4 6) := checkRawExact_sound _ _ _ exactWire4_6 (by decide)
def exactWire5_6 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-5-6.json"
theorem exactCase5_6 : ExactAt (augmentedOutgoing actualRows 5 6) (freeDifferential actualRows 5 6) := checkRawExact_sound _ _ _ exactWire5_6 (by decide)
def exactWire6_6 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-6-6.json"
theorem exactCase6_6 : ExactAt (augmentedOutgoing actualRows 6 6) (freeDifferential actualRows 6 6) := checkRawExact_sound _ _ _ exactWire6_6 (by decide)
def exactWire0_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-7.json"
theorem exactCase0_7 : ExactAt (augmentedOutgoing actualRows 0 7) (freeDifferential actualRows 0 7) := checkRawExact_sound _ _ _ exactWire0_7 (by decide)
def exactWire1_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-7.json"
theorem exactCase1_7 : ExactAt (augmentedOutgoing actualRows 1 7) (freeDifferential actualRows 1 7) := checkRawExact_sound _ _ _ exactWire1_7 (by decide)
def exactWire2_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-2-7.json"
theorem exactCase2_7 : ExactAt (augmentedOutgoing actualRows 2 7) (freeDifferential actualRows 2 7) := checkRawExact_sound _ _ _ exactWire2_7 (by decide)
def exactWire3_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-3-7.json"
theorem exactCase3_7 : ExactAt (augmentedOutgoing actualRows 3 7) (freeDifferential actualRows 3 7) := checkRawExact_sound _ _ _ exactWire3_7 (by decide)
def exactWire4_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-4-7.json"
theorem exactCase4_7 : ExactAt (augmentedOutgoing actualRows 4 7) (freeDifferential actualRows 4 7) := checkRawExact_sound _ _ _ exactWire4_7 (by decide)
def exactWire5_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-5-7.json"
theorem exactCase5_7 : ExactAt (augmentedOutgoing actualRows 5 7) (freeDifferential actualRows 5 7) := checkRawExact_sound _ _ _ exactWire5_7 (by decide)
def exactWire6_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-6-7.json"
theorem exactCase6_7 : ExactAt (augmentedOutgoing actualRows 6 7) (freeDifferential actualRows 6 7) := checkRawExact_sound _ _ _ exactWire6_7 (by decide)
def exactWire7_7 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-7-7.json"
theorem exactCase7_7 : ExactAt (augmentedOutgoing actualRows 7 7) (freeDifferential actualRows 7 7) := checkRawExact_sound _ _ _ exactWire7_7 (by decide)
def exactWire0_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-0-8.json"
theorem exactCase0_8 : ExactAt (augmentedOutgoing actualRows 0 8) (freeDifferential actualRows 0 8) := checkRawExact_sound _ _ _ exactWire0_8 (by decide)
def exactWire1_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-1-8.json"
theorem exactCase1_8 : ExactAt (augmentedOutgoing actualRows 1 8) (freeDifferential actualRows 1 8) := checkRawExact_sound _ _ _ exactWire1_8 (by decide)
def exactWire2_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-2-8.json"
theorem exactCase2_8 : ExactAt (augmentedOutgoing actualRows 2 8) (freeDifferential actualRows 2 8) := checkRawExact_sound _ _ _ exactWire2_8 (by decide)
def exactWire3_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-3-8.json"
theorem exactCase3_8 : ExactAt (augmentedOutgoing actualRows 3 8) (freeDifferential actualRows 3 8) := checkRawExact_sound _ _ _ exactWire3_8 (by decide)
def exactWire4_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-4-8.json"
theorem exactCase4_8 : ExactAt (augmentedOutgoing actualRows 4 8) (freeDifferential actualRows 4 8) := checkRawExact_sound _ _ _ exactWire4_8 (by decide)
def exactWire5_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-5-8.json"
theorem exactCase5_8 : ExactAt (augmentedOutgoing actualRows 5 8) (freeDifferential actualRows 5 8) := checkRawExact_sound _ _ _ exactWire5_8 (by decide)
def exactWire6_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-6-8.json"
theorem exactCase6_8 : ExactAt (augmentedOutgoing actualRows 6 8) (freeDifferential actualRows 6 8) := checkRawExact_sound _ _ _ exactWire6_8 (by decide)
def exactWire7_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-7-8.json"
theorem exactCase7_8 : ExactAt (augmentedOutgoing actualRows 7 8) (freeDifferential actualRows 7 8) := checkRawExact_sound _ _ _ exactWire7_8 (by decide)
def exactWire8_8 : WireContraction := resolution_bundle% "ExtComplexCertificates/actual-s0/exactness/exact-8-8.json"
theorem exactCase8_8 : ExactAt (augmentedOutgoing actualRows 8 8) (freeDifferential actualRows 8 8) := checkRawExact_sound _ _ _ exactWire8_8 (by decide)
