import ExtComplexCertificates.MinimalHom
open ExtComplexCertificates.ActualResolution
example : actualHomDimension 0 0 = 1 := by decide
example : actualHomDimension 0 1 = 0 := by decide
example : actualHomDimension 1 1 = 1 := by decide
example : actualHomDimension 0 2 = 0 := by decide
example : actualHomDimension 1 2 = 1 := by decide
example : actualHomDimension 2 2 = 1 := by decide
example : actualHomDimension 0 3 = 0 := by decide
example : actualHomDimension 1 3 = 0 := by decide
example : actualHomDimension 2 3 = 0 := by decide
example : actualHomDimension 3 3 = 1 := by decide
example : actualHomDimension 0 4 = 0 := by decide
example : actualHomDimension 1 4 = 1 := by decide
example : actualHomDimension 2 4 = 1 := by decide
example : actualHomDimension 3 4 = 0 := by decide
example : actualHomDimension 4 4 = 1 := by decide
example : actualHomDimension 0 5 = 0 := by decide
example : actualHomDimension 1 5 = 0 := by decide
example : actualHomDimension 2 5 = 1 := by decide
example : actualHomDimension 3 5 = 0 := by decide
example : actualHomDimension 4 5 = 0 := by decide
example : actualHomDimension 5 5 = 1 := by decide
example : actualHomDimension 0 6 = 0 := by decide
example : actualHomDimension 1 6 = 0 := by decide
example : actualHomDimension 2 6 = 0 := by decide
example : actualHomDimension 3 6 = 1 := by decide
example : actualHomDimension 4 6 = 0 := by decide
example : actualHomDimension 5 6 = 0 := by decide
example : actualHomDimension 6 6 = 1 := by decide
example : actualHomDimension 0 7 = 0 := by decide
example : actualHomDimension 1 7 = 0 := by decide
example : actualHomDimension 2 7 = 0 := by decide
example : actualHomDimension 3 7 = 0 := by decide
example : actualHomDimension 4 7 = 0 := by decide
example : actualHomDimension 5 7 = 0 := by decide
example : actualHomDimension 6 7 = 0 := by decide
example : actualHomDimension 7 7 = 1 := by decide
example : actualHomDimension 0 8 = 0 := by decide
example : actualHomDimension 1 8 = 1 := by decide
example : actualHomDimension 2 8 = 1 := by decide
example : actualHomDimension 3 8 = 0 := by decide
example : actualHomDimension 4 8 = 0 := by decide
example : actualHomDimension 5 8 = 0 := by decide
example : actualHomDimension 6 8 = 0 := by decide
example : actualHomDimension 7 8 = 0 := by decide
example : actualHomDimension 8 8 = 1 := by decide
