import KIP126.Def.References.Provenance
import KIP126.Def.References.Literature.Claims
import KIP126.Def.References.Literature.Kervaire
import KIP126.Def.References.Literature.BJMOriginal
import KIP126.Interface.Challenge.Literature.Synthetic
import KIP126.Def.References.Evidence
import KIP126.Def.References.Results
import KIP126.Def.References.Literature.SourceInventory
import KIP126.Main.Axiom.Challenge2
import KIP126.Interface.Challenge.Literature.May
import KIP126.Interface.Challenge.Literature.InternalGeometry
import KIP126.Interface.Challenge.Challenge2
import KIP126.Def.References.Literature.EtaRows.Data
import KIP126.Def.References.Literature.Adams.OneLine
import KIP126.Def.References.Literature.AppendixTable.Rows.Catalogue.Data
