import KIP126.Main.Axiom.Provenance
import KIP126.Main.Axiom.Literature.Claims
import KIP126.Main.Axiom.Literature.Kervaire
import KIP126.Main.Axiom.Literature.BJMOriginal
import KIP126.Main.Axiom.Literature.Synthetic
import KIP126.Main.Axiom.Literature.SyntheticEInfty
import KIP126.Main.Axiom.Literature.SyntheticBockstein
import KIP126.Main.Axiom.Evidence
import KIP126.Main.Axiom.Results
import KIP126.Main.Axiom.Literature.SourceInventory
import KIP126.Main.Axiom.Challenge2
import KIP126.Main.Axiom.Literature.May
import KIP126.Main.Axiom.Literature.InternalGeometry
import KIP126.Main.Axiom.Literature.Route
import KIP126.Main.Axiom.Literature.EtaRows.Data
import KIP126.Main.Axiom.Literature.Adams.OneLine
import KIP126.Main.Axiom.Literature.AppendixTable.Rows.Catalogue.Data
