import KIP126.Main.Solution.Computation.Dimension
import KIP126.Main.Solution.Computation.Nonvanishing
import KIP126.Main.Solution.Computation.Reduction
import KIP126.Main.Solution.Computation.Vanishing
import KIP126.Main.Solution.Final.h6_sq_permanent
import KIP126.Main.Solution.Final.h6_sq_permanent_computational
import KIP126.Main.Solution.Near126.any_choice_criterion
import KIP126.Main.Solution.Near126.c3_excludes_c5
import KIP126.Main.Solution.Near126.c4_c5_choice_equivalence
import KIP126.Main.Solution.Near126.d12_dichotomy_and_condition_equivalence
import KIP126.Main.Solution.Near126.only_d12_differential_reduction
