import KIP126.Def.Synthetic.Source.Exactness
import KIP126.Def.Synthetic.Source.Day
import KIP126.Def.Synthetic.Source.Signs
import KIP126.Def.StableHomotopy.Source.Orthogonal.ShiftZigzag

/-! Derived bigrading comparisons, generated by actual point-set
replacement and suspension/loop maps in whole categories of diagrams.
The precomposition action reverses transformations; postcomposition is
covariant. No objectwise choice of a map in Ho(Sp) is used. -/
namespace KIP126.Synthetic.Source
open CategoryTheory CategoryTheory.Functor Opposite
open KIP126.StableHomotopy.Source
noncomputable section

abbrev ShiftWord := Orthogonal.ShiftWord
abbrev ShiftZigzag := Orthogonal.ShiftZigzag

theorem word_preserves_finite {F : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (h : ShiftWord F) (P : FiniteSite) : FiniteOrthogonal (F.obj P.obj) := by sorry

def finiteWord (F : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum) (h : ShiftWord F) :
    FiniteSite ⥤ FiniteSite where
  obj P := ⟨F.obj P.obj,word_preserves_finite h P⟩
  map f := ⟨F.map f.hom⟩
  map_id := by sorry
  map_comp := by sorry

def preWord (F : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum) (h : ShiftWord F) :
    SphericalDiagram ⥤ SphericalDiagram where
  obj X := ⟨(finiteWord F h).op ⋙ X.obj,by sorry⟩
  map f := ⟨whiskerLeft (finiteWord F h).op f.hom⟩
  map_id := by sorry
  map_comp := by sorry

def postWord (F : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum) (h : ShiftWord F) :
    SphericalDiagram ⥤ SphericalDiagram where
  obj X := ⟨X.obj ⋙ F,by sorry⟩
  map f := ⟨whiskerRight f.hom F⟩
  map_id := by sorry
  map_comp := by sorry

def preWordMap {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (hF : ShiftWord F) (hG : ShiftWord G) (a : F ⟶ G) :
    preWord G hG ⟶ preWord F hF where
  app X := ⟨{ app := fun P => X.obj.map (show
      (finiteWord F hF).obj P.unop ⟶ (finiteWord G hG).obj P.unop from
        ⟨a.app P.unop.obj⟩).op
              naturality := by sorry }⟩
  naturality := by sorry

def postWordMap {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (hF : ShiftWord F) (hG : ShiftWord G) (a : F ⟶ G) :
    postWord F hF ⟶ postWord G hG where
  app X := ⟨whiskerLeft X.obj a⟩
  naturality := by sorry

theorem preWordMap_equivalent {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (hF : ShiftWord F) (hG : ShiftWord G) (a : F ⟶ G)
    (ha : ∀ X, Orthogonal.stableEquivalences (a.app X)) (X : SphericalDiagram) :
    diagramStableEquivalences ((preWordMap hF hG a).app X) := by sorry

theorem postWordMap_equivalent {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (hF : ShiftWord F) (hG : ShiftWord G) (a : F ⟶ G)
    (ha : ∀ X, Orthogonal.stableEquivalences (a.app X)) (X : SphericalDiagram) :
    diagramStableEquivalences ((postWordMap hF hG a).app X) := by sorry

theorem preWord_equivalent (F : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum)
    (hF : ShiftWord F) {X Y : SphericalDiagram} (f : X ⟶ Y)
    (hf : diagramStableEquivalences f) : diagramStableEquivalences ((preWord F hF).map f) := by
  sorry

theorem postWord_equivalent (F : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum)
    (hF : ShiftWord F) {X Y : SphericalDiagram} (f : X ⟶ Y)
    (hf : diagramStableEquivalences f) : diagramStableEquivalences ((postWord F hF).map f) := by
  sorry

/-- These comparison components are identities of the SAME strict diagram.
Only functor-associativity and proof-irrelevant property fields are rewritten. -/
def preWordComp (F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum)
    (hF : ShiftWord F) (hG : ShiftWord G) :
    preWord (F ⋙ G) (.comp hF hG) ≅ preWord G hG ⋙ preWord F hF :=
  NatIso.ofComponents (fun X =>
    { hom := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      inv := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      hom_inv_id := by sorry
      inv_hom_id := by sorry }) (by sorry)

def postWordComp (F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum)
    (hF : ShiftWord F) (hG : ShiftWord G) :
    postWord (F ⋙ G) (.comp hF hG) ≅ postWord F hF ⋙ postWord G hG :=
  NatIso.ofComponents (fun X =>
    { hom := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      inv := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      hom_inv_id := by sorry
      inv_hom_id := by sorry }) (by sorry)

universe u v
variable {C : Type u} [Category.{v} C]

def preGenerator {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (hF : ShiftWord F) (hG : ShiftWord G) (a : F ⟶ G)
    (ha : ∀ X, Orthogonal.stableEquivalences (a.app X))
    (K : SphericalDiagram ⥤ C) (hK : diagramStableEquivalences.IsInvertedBy K) :
    preWord F hF ⋙ K ≅ preWord G hG ⋙ K :=
  (NatIso.ofComponents (fun X => by
    haveI : IsIso (K.map ((preWordMap hF hG a).app X)) :=
      hK _ (preWordMap_equivalent hF hG a ha X)
    exact @asIso C _ _ _ (K.map ((preWordMap hF hG a).app X))
      (hK _ (preWordMap_equivalent hF hG a ha X))) (by sorry)).symm

def postGenerator {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (hF : ShiftWord F) (hG : ShiftWord G) (a : F ⟶ G)
    (ha : ∀ X, Orthogonal.stableEquivalences (a.app X))
    (K : SphericalDiagram ⥤ C) (hK : diagramStableEquivalences.IsInvertedBy K) :
    postWord F hF ⋙ K ≅ postWord G hG ⋙ K :=
  NatIso.ofComponents (fun X => by
    haveI : IsIso (K.map ((postWordMap hF hG a).app X)) :=
      hK _ (postWordMap_equivalent hF hG a ha X)
    exact @asIso C _ _ _ (K.map ((postWordMap hF hG a).app X))
      (hK _ (postWordMap_equivalent hF hG a ha X))) (by sorry)

/-- Covariant interpretation in VALUES of entire strict diagrams. -/
def postInterpret {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (z : ShiftZigzag F G) (K : SphericalDiagram ⥤ C)
    (hK : diagramStableEquivalences.IsInvertedBy K) :
    postWord F z.words.1 ⋙ K ≅ postWord G z.words.2 ⋙ K :=
  match z with
  | .refl F hF => Iso.refl _
  | .q => postGenerator .q .id Orthogonal.cofibrantResolution.projection
      (fun X => Orthogonal.levelTrivialFibration_stable _
        (Orthogonal.cofibrantResolution.trivial X)) K hK
  | .r => postGenerator .id .r Orthogonal.fibrantResolution.inclusion
      Orthogonal.fibrantResolution.equivalent K hK
  | .unit => postGenerator .q (.comp .suspension .loops) Orthogonal.derivedShiftUnit
      Orthogonal.derivedShiftUnit_equivalence K hK
  | .counit => postGenerator (.comp .loops .suspension) .r Orthogonal.derivedShiftCounit
      Orthogonal.derivedShiftCounit_equivalence K hK
  | .symm z => (postInterpret z K hK).symm
  | .trans z w => postInterpret z K hK ≪≫ postInterpret w K hK
  | .left A hA z =>
      isoWhiskerRight (postWordComp A _ hA z.words.1) K ≪≫
      isoWhiskerLeft (postWord A hA) (postInterpret z K hK) ≪≫
      (isoWhiskerRight (postWordComp A _ hA z.words.2) K).symm
  | .right A hA z =>
      isoWhiskerRight (postWordComp _ A z.words.1 hA) K ≪≫
      postInterpret z (postWord A hA ⋙ K)
        (fun _ _ f hf => hK _ (postWord_equivalent A hA f hf)) ≪≫
      (isoWhiskerRight (postWordComp _ A z.words.2 hA) K).symm

/-- Contravariant SOURCE action. Every primitive map is reversed before
inverting its actual pointwise-equivalence image. -/
def preInterpret {F G : Orthogonal.Spectrum ⥤ Orthogonal.Spectrum}
    (z : ShiftZigzag F G) (K : SphericalDiagram ⥤ C)
    (hK : diagramStableEquivalences.IsInvertedBy K) :
    preWord F z.words.1 ⋙ K ≅ preWord G z.words.2 ⋙ K :=
  match z with
  | .refl F hF => Iso.refl _
  | .q => preGenerator .q .id Orthogonal.cofibrantResolution.projection
      (fun X => Orthogonal.levelTrivialFibration_stable _
        (Orthogonal.cofibrantResolution.trivial X)) K hK
  | .r => preGenerator .id .r Orthogonal.fibrantResolution.inclusion
      Orthogonal.fibrantResolution.equivalent K hK
  | .unit => preGenerator .q (.comp .suspension .loops) Orthogonal.derivedShiftUnit
      Orthogonal.derivedShiftUnit_equivalence K hK
  | .counit => preGenerator (.comp .loops .suspension) .r Orthogonal.derivedShiftCounit
      Orthogonal.derivedShiftCounit_equivalence K hK
  | .symm z => (preInterpret z K hK).symm
  | .trans z w => preInterpret z K hK ≪≫ preInterpret w K hK
  | .left A hA z =>
      isoWhiskerRight (preWordComp A _ hA z.words.1) K ≪≫
      preInterpret z (preWord A hA ⋙ K)
        (fun _ _ f hf => hK _ (preWord_equivalent A hA f hf)) ≪≫
      (isoWhiskerRight (preWordComp A _ hA z.words.2) K).symm
  | .right A hA z =>
      isoWhiskerRight (preWordComp _ A z.words.1 hA) K ≪≫
      isoWhiskerLeft (preWord A hA) (preInterpret z K hK) ≪≫
      (isoWhiskerRight (preWordComp _ A z.words.2 hA) K).symm

/-- Reassociation of the SAME point-set composite, with identity maps. -/
def biShiftWordPresentation (p : ℤ × ℤ) : biShiftDiagram p ≅
    preWord (Orthogonal.derivedShift (-p.2)) (Orthogonal.ShiftWord.derivedShift _) ⋙
      postWord (Orthogonal.derivedShift (p.1-p.2)) (Orthogonal.ShiftWord.derivedShift _) :=
  NatIso.ofComponents (fun X =>
    { hom := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      inv := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      hom_inv_id := by sorry
      inv_hom_id := by sorry }) (by sorry)

def biShiftCompositeWordPresentation (p q : ℤ × ℤ) :
    biShiftDiagram p ⋙ biShiftDiagram q ≅
    preWord (Orthogonal.derivedShift (-q.2) ⋙ Orthogonal.derivedShift (-p.2))
      (.comp (Orthogonal.ShiftWord.derivedShift _) (Orthogonal.ShiftWord.derivedShift _)) ⋙
    postWord (Orthogonal.derivedShift (p.1-p.2) ⋙ Orthogonal.derivedShift (q.1-q.2))
      (.comp (Orthogonal.ShiftWord.derivedShift _) (Orthogonal.ShiftWord.derivedShift _)) :=
  NatIso.ofComponents (fun X =>
    { hom := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      inv := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      hom_inv_id := by sorry
      inv_hom_id := by sorry }) (by sorry)

/-- Both integer normalizations use only the actual adjunction and
replacement generators. The source order is -q.weight then -p.weight. -/
def biShiftAddOnDiagrams (R : RealizedFoundation) (p q : ℤ × ℤ) :
    biShiftDiagram p ⋙ biShiftDiagram q ⋙ hypercompletion R ≅
      biShiftDiagram (p+q) ⋙ hypercompletion R := by
  let A := Orthogonal.shiftAddZigzag (-q.2) (-p.2)
  let B := Orthogonal.shiftAddZigzag (p.1-p.2) (q.1-q.2)
  let K := hypercompletion R
  let hK := hypercompletion_inverts_pointwise R
  let hpost : diagramStableEquivalences.IsInvertedBy
      (postWord _ B.words.1 ⋙ K) :=
    fun _ _ f hf => hK _ (postWord_equivalent _ B.words.1 f hf)
  let a := preInterpret A (postWord _ B.words.1 ⋙ K) hpost
  let b := isoWhiskerLeft (preWord _ A.words.2) (postInterpret B K hK)
  let e := isoWhiskerRight (biShiftCompositeWordPresentation p q) K ≪≫ a ≪≫ b
  have hd : -q.2 + -p.2 = -(p+q).2 := by simp only [Prod.snd_add]; omega
  have hv : (p.1-p.2)+(q.1-q.2) = (p+q).1-(p+q).2 := by
    simp only [Prod.fst_add,Prod.snd_add]; omega
  exact e ≪≫ isoWhiskerRight
    (show preWord (Orthogonal.derivedShift (-q.2 + -p.2)) A.words.2 ⋙
        postWord (Orthogonal.derivedShift ((p.1-p.2)+(q.1-q.2))) B.words.2 ≅
        biShiftDiagram (p+q) from by
      simpa only [hd,hv] using (biShiftWordPresentation (p+q)).symm) K

/-- Only identity maps re-associate the zero point-set shift. -/
def biShiftZeroOnDiagrams : biShiftDiagram (0,0) ≅ 𝟭 SphericalDiagram :=
  NatIso.ofComponents (fun X =>
    { hom := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      inv := ⟨{ app := fun _ => 𝟙 _, naturality := by sorry }⟩
      hom_inv_id := by sorry
      inv_hom_id := by sorry }) (by sorry)

/-- Descend the precise natural comparison along the original localization. -/
def biShiftAddPresented (R : RealizedFoundation) (p q : ℤ × ℤ) :
    hypercompletion R ⋙ (biShift R p ⋙ biShift R q) ≅
      hypercompletion R ⋙ biShift R (p+q) :=
  isoWhiskerRight (biShiftComparison R p) (biShift R q) ≪≫
    isoWhiskerLeft (biShiftDiagram p) (biShiftComparison R q) ≪≫
    biShiftAddOnDiagrams R p q ≪≫ (biShiftComparison R (p+q)).symm

def biShiftAddRaw (R : RealizedFoundation) (p q : ℤ × ℤ) :
    biShift R p ⋙ biShift R q ≅ biShift R (p+q) :=
  Localization.liftNatIso (hypercompletion R) (localStableEquivalences R)
    _ _ _ _ (biShiftAddPresented R p q)

/-- Keep the actual action composition unchanged. Pstragowski's sign
convention concerns a sphere TENSOR pairing. Identifying that pairing with
one induced by this action and the Day strength is a separate comparison;
an extra sign must not be inserted here merely from matching bidegrees. -/
def biShiftAdd (R : RealizedFoundation) (p q : ℤ × ℤ) :
    biShift R p ⋙ biShift R q ≅ biShift R (p+q) :=
  biShiftAddRaw R p q

def biShiftZeroPresented (R : RealizedFoundation) :
    hypercompletion R ⋙ biShift R (0,0) ≅ hypercompletion R ⋙ 𝟭 _ :=
  biShiftComparison R (0,0) ≪≫ isoWhiskerRight biShiftZeroOnDiagrams (hypercompletion R)

def biShiftZero (R : RealizedFoundation) : biShift R (0,0) ≅ 𝟭 _ :=
  Localization.liftNatIso (hypercompletion R) (localStableEquivalences R)
    _ _ _ _ (biShiftZeroPresented R)

/-- Regrading adds only transport along an equality of integer pairs. -/
def biShiftAddTo (R : RealizedFoundation) (a b c : ℤ × ℤ) (h : a+b=c) :
    biShift R a ⋙ biShift R b ≅ biShift R c :=
  biShiftAdd R a b ≪≫ eqToIso (congrArg (biShift R) h)

/-- Equations on the fixed normalization maps. Their proofs are derived
adjunction triangle identities and actual replacement naturality. -/
theorem biShiftAdd_associativity (R : RealizedFoundation)
    (a b c ab bc total : ℤ × ℤ) (hab : a+b=ab) (hbc : b+c=bc)
    (habc : ab+c=total) (habc' : a+bc=total) (X : HypercompleteCategory R) :
    (biShift R c).map ((biShiftAddTo R a b ab hab).hom.app X) ≫
      (biShiftAddTo R ab c total habc).hom.app X =
    (biShiftAddTo R b c bc hbc).hom.app ((biShift R a).obj X) ≫
      (biShiftAddTo R a bc total habc').hom.app X := by sorry

theorem biShiftAdd_left_unit (R : RealizedFoundation)
    (a : ℤ × ℤ) (X : HypercompleteCategory R) :
    (biShiftAddTo R 0 a a (zero_add a)).hom.app X =
      (biShift R a).map ((biShiftZero R).hom.app X) := by sorry

theorem biShiftAdd_right_unit (R : RealizedFoundation)
    (a : ℤ × ℤ) (X : HypercompleteCategory R) :
    (biShiftAddTo R a 0 a (add_zero a)).hom.app X =
      (biShiftZero R).hom.app ((biShift R a).obj X) := by sorry

/- Centrality of lambda is stated in Source/SpherePairing for the
preferred action convention. It is not also asserted for this raw
pre/post normalization without a comparison of its signs. -/

end
end KIP126.Synthetic.Source
