// Untrusted dense F2 witness producer. Lean independently verifies all identities.
#define main comparison_export_main
#include "../PageTransitionCertificates/export.cpp"
#undef main
#include <regex>
struct Cmp { unsigned k,m,n,h; Bits out,in,down; std::string json; };
std::string read(const std::string& p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot read "+p);return {std::istreambuf_iterator<char>(f),{}};}
unsigned number(const std::string&s,const std::string&key){std::smatch m;if(!std::regex_search(s,m,std::regex("\\\""+key+"\\\":([0-9]+)")))throw std::runtime_error("missing "+key);return nat(m[1]);}
Bits array(const std::string&s,const std::string&key){std::smatch m;if(!std::regex_search(s,m,std::regex("\\\""+key+"\\\":\\[([^\\]]*)\\]")))throw std::runtime_error("missing "+key);Bits b;std::string z=m[1];if(z.empty())return b;std::istringstream f(z);std::string tok;while(std::getline(f,tok,',')){if(tok!="true"&&tok!="false")throw std::runtime_error("bad boolean");b.push_back(tok=="true");}return b;}
Cmp cmp(const std::string&p){auto s=read(p);Cmp c{number(s,"k"),number(s,"m"),number(s,"n"),number(s,"h"),array(s,"outgoing"),array(s,"incoming"),array(s,"down"),s};if(c.out.size()!=c.k*c.m||c.in.size()!=c.m*c.n||c.down.size()!=c.m*c.k)throw std::runtime_error("comparison shape");while(!c.json.empty()&&isspace(c.json.back()))c.json.pop_back();return c;}
Bits projector(const Cmp&c){Bits p(c.m*c.m);for(unsigned i=0;i<c.m;i++)for(unsigned j=0;j<c.m;j++){p[i*c.m+j]=i==j;for(unsigned k=0;k<c.k;k++)p[i*c.m+j]^=c.down[i*c.k+k]&&c.out[k*c.m+j];}return p;}
Bits preimage(const Cmp&c,const Bits&v){std::vector<Bits>a(c.m,Bits(c.n+1));for(unsigned i=0;i<c.m;i++){for(unsigned j=0;j<c.n;j++)a[i][j]=c.in[i*c.n+j];a[i][c.n]=v[i];}unsigned r=0;std::vector<unsigned>ps;for(unsigned j=0;j<c.n&&r<c.m;j++){unsigned p=r;while(p<c.m&&!a[p][j])p++;if(p==c.m)continue;std::swap(a[p],a[r]);for(unsigned i=0;i<c.m;i++)if(i!=r&&a[i][j])for(unsigned k=j;k<=c.n;k++)a[i][k]^=a[r][k];ps.push_back(j);r++;}for(unsigned i=r;i<c.m;i++)if(a[i][c.n])throw std::runtime_error("boundary preimage does not exist");Bits x(c.n);for(unsigned i=0;i<r;i++)x[ps[i]]=a[i][c.n];return x;}
std::string produce(const std::string&line){std::istringstream f(line);std::string pa,pb,pc,tok,extra;if(!(f>>pa>>pb>>pc>>tok)||f>>extra)throw std::runtime_error("expected LEFT.json RIGHT.json TARGET.json TENSOR_BITS");Cmp a=cmp(pa),b=cmp(pb),c=cmp(pc);auto t=bits(tok,a.m*b.m*c.m);auto ap=projector(a),bp=projector(b);auto prod=[&](const Bits&x,const Bits&y){Bits z(c.m);for(unsigned k=0;k<c.m;k++)for(unsigned i=0;i<a.m;i++)for(unsigned j=0;j<b.m;j++)z[k]^=t[(k*a.m+i)*b.m+j]&&x[i]&&y[j];return z;};auto col=[](const Bits&m,unsigned rows,unsigned cols,unsigned j){Bits v(rows);for(unsigned i=0;i<rows;i++)v[i]=m[i*cols+j];return v;};Bits l(c.n*a.n*b.m),r(c.n*a.m*b.n);for(unsigned i=0;i<a.m;i++)for(unsigned j=0;j<b.m;j++){auto z=prod(col(ap,a.m,a.m,i),col(bp,b.m,b.m,j));for(unsigned k=0;k<c.k;k++){bool q=false;for(unsigned n=0;n<c.m;n++)q^=c.out[k*c.m+n]&&z[n];if(q)throw std::runtime_error("cycle product failure at "+std::to_string(i)+","+std::to_string(j));}}
for(unsigned i=0;i<a.n;i++)for(unsigned j=0;j<b.m;j++){auto v=preimage(c,prod(col(a.in,a.m,a.n,i),col(bp,b.m,b.m,j)));for(unsigned k=0;k<c.n;k++)l[(k*a.n+i)*b.m+j]=v[k];}
for(unsigned i=0;i<a.m;i++)for(unsigned j=0;j<b.n;j++){auto v=preimage(c,prod(col(ap,a.m,a.m,i),col(b.in,b.m,b.n,j)));for(unsigned k=0;k<c.n;k++)r[(k*a.m+i)*b.n+j]=v[k];}
std::ostringstream o;o<<"{\"left\":"<<a.json<<",\"leftBoundary\":";jsonBits(o,l);o<<",\"leftCorrection\":";jsonBits(o,a.down);o<<",\"leftProjector\":";jsonBits(o,ap);o<<",\"right\":"<<b.json<<",\"rightBoundary\":";jsonBits(o,r);o<<",\"rightCorrection\":";jsonBits(o,b.down);o<<",\"rightProjector\":";jsonBits(o,bp);o<<",\"target\":"<<c.json<<",\"tensor\":";jsonBits(o,t);o<<",\"version\":1}";return o.str();}
int main(int argc,char**argv){try{if(argc!=3||std::string(argv[1])!="--batch")throw std::runtime_error("usage: page-product-export --batch INPUT.txt");std::ifstream f(argv[2]);if(!f)throw std::runtime_error("cannot open batch");std::string line;unsigned n=0;while(std::getline(f,line)){n++;try{std::cout<<produce(line)<<'\n';}catch(const std::exception&e){throw std::runtime_error("line "+std::to_string(n)+": "+e.what());}}if(!n)throw std::runtime_error("empty batch");return 0;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 1;}}
