import Fact713Row3247ConditionalBranches.ZeroCross
namespace Fact713Row3247ConditionalBranches.Zero
open IndexedFamilyCertificates
theorem family_coherent : Coherent family :=
  Fact713RefinedComparisonFamily.coherent_append _ _ Fact713D4ComparisonBranches.Zero.family_coherent extra_coherent cross_checked
#print axioms family_coherent
end Fact713Row3247ConditionalBranches.Zero
