import KIP126.Def.AdamsE2.LinClasses.Proofs
import KIP126.Def.AdamsE2.LinModel.Data
import KIP126.Def.AdamsE2.LinModel.Proofs
import KIP126.Def.ClassicalAdams.Moss.Crossing.Predicates
import KIP126.Def.ClassicalAdams.Moss.Statement.Predicates
import KIP126.Def.ClassicalAdams.PageRepresentatives.Order.Proofs
import KIP126.Def.ClassicalAdams.SphereVanishing.Predicates
import KIP126.Def.Kervaire.Route.Conditions.Predicates
import KIP126.Def.Kervaire.Route.Model.Data
import KIP126.Def.Kervaire.Route.Model.Predicates
import KIP126.Def.Kervaire.Route.SourceLanguage
import KIP126.Def.Kervaire.Route.Triangles.Predicates
import KIP126.Def.Kervaire.Theta5.Synthetic.Predicates
import KIP126.Def.SpectralSequence.Computation.Proofs
import KIP126.Def.StableHomotopy.Implementation.Data
import KIP126.Def.StableHomotopy.Toda.Coset.Proofs
import KIP126.Def.StableHomotopy.Toda.Juggling.Proofs
import KIP126.Def.StableHomotopy.Toda.Law.Proofs
import KIP126.Def.StableHomotopy.Toda.Predicates
import KIP126.Def.Synthetic.AdamsFiltration.Convergence.Data
import KIP126.Def.Synthetic.Completion.Predicates
import KIP126.Def.Synthetic.EInfty.Presentation.Data
import KIP126.Def.Synthetic.EInfty.Presentation.Predicates
import KIP126.Interface.Challenge.Challenge2
import KIP126.Interface.Solution.AdamsOneLine
import KIP126.Interface.Solution.Challenge2
import KIP126.Interface.Solution.LinProgram.Route.Certification
import KIP126.Interface.Solution.Literature.Route.Moss
import KIP126.LinProgram.Interpretation.Near126.Classes.Data
import KIP126.LinProgram.Interpretation.Route.Data
import KIP126.LinProgram.Interpretation.Route.Predicates
import KIP126.LinProgram.Route.Selected
import KIP126.Main.Solution.ChoiceIndependence.any_choice_criterion
import KIP126.Main.Solution.Computation.Route
import KIP126.Main.Solution.Computation.Route.Consequences
import KIP126.Main.Solution.Computation.Tmf
import KIP126.Main.Solution.h6_sq_permanent
#check @KIP126.Challenge2.ComputationInterface
#check @KIP126.Challenge2.SphereMultiplicativeInterface
#check @KIP126.Classical.Adams.Moss.HasMossCrossing
#check @KIP126.Classical.Adams.Moss.StatementAt
#check @KIP126.Classical.Adams.Moss.crossingSourceDegree
#check @KIP126.Classical.Adams.PageRepresentatives.boundaries_le_permanentCycles
#check @KIP126.Classical.Adams.SphereVanishingLine
#check @KIP126.Computation.Near126.B
#check @KIP126.Computation.Near126.P
#check @KIP126.Computation.Near126.Q
#check @KIP126.Computation.Near126.T
#check @KIP126.Computation.Near126.X
#check @KIP126.Computation.Near126.Y
#check @KIP126.Computation.Near126.correction
#check @KIP126.Computation.Route.BasisCorrect
#check @KIP126.Computation.Route.BottomCorrect
#check @KIP126.Computation.Route.Derived.CnuDifferential
#check @KIP126.Computation.Route.Derived.CnuTargetThrough5
#check @KIP126.Computation.Route.Derived.SphereFacts
#check @KIP126.Computation.Route.Inputs
#check @KIP126.Computation.Route.LabelsCorrect
#check @KIP126.Computation.Route.Raw.bottomMaps
#check @KIP126.Computation.Route.Raw.claims
#check @KIP126.Computation.Route.Raw.degrees
#check @KIP126.Computation.Route.Raw.products
#check @KIP126.Computation.Route.Realization
#check @KIP126.Computation.Route.SphereBasisValue
#check @KIP126.Computation.Route.Statement
#check @KIP126.Computation.Route.TopCorrect
#check @KIP126.Computation.Route.classical_stem125_filtration26_zero
#check @KIP126.Computation.Route.cnu_d3
#check @KIP126.Computation.Route.cnu_target_through5
#check @KIP126.Computation.Route.high125_detected_choice_unique
#check @KIP126.Computation.Route.high125_label
#check @KIP126.Computation.Route.nonzero_permanent_of_survives1000
#check @KIP126.Computation.Route.permanent_cycle_of_reaches1000
#check @KIP126.Computation.Route.sphere_facts
#check @KIP126.Computation.Route.sphere_page_zero_above_uniform_bound
#check @KIP126.Computation.Route.sphere_page_zero_stem125_tail
#check @KIP126.Computation.Route.stem125_e5_zero_finite
#check @KIP126.Core.SpectralSequence.HasNonzeroDifferential.source_survives
#check @KIP126.Interface.Solution.LinProgram.Route.certification
#check @KIP126.Interface.Solution.Literature.Route.mossInputOfClassicalSource
#check @KIP126.Interface.Solution.may_lowDimensionalProducts_permanent
#check @KIP126.Kervaire.BJMSourceTotalBoundaryIdentity
#check @KIP126.Kervaire.BJMUntruncatedCriterion
#check @KIP126.Kervaire.Route.ComparisonCompatible
#check @KIP126.Kervaire.Route.ModelData
#check @KIP126.Kervaire.Route.NormalizedTriangleCompatible
#check @KIP126.Kervaire.Route.ThetaChoice
#check @KIP126.LinE2.csv_relation_zero
#check @KIP126.LinE2.definingIdeal
#check @KIP126.LinE2.definingRelations
#check @KIP126.LinE2.h1_mul_h2_eq_zero
#check @KIP126.Literature.Route.AlgebraData.withBinding
#check @KIP126.Literature.Route.BHSCompletionApplicability
#check @KIP126.Literature.Route.BHSCompletionComparison
#check @KIP126.Literature.Route.BHSPermanentLiftAt
#check @KIP126.Literature.Route.BHSRealizationDetectionAt
#check @KIP126.Literature.Route.BHSRealizationSourceResults
#check @KIP126.Literature.Route.BXDistinguishedInput
#check @KIP126.Literature.Route.BocksteinDifferential
#check @KIP126.Literature.Route.ClassicalHigh125Tail
#check @KIP126.Literature.Route.ClassicalProductDetection
#check @KIP126.Literature.Route.ClassicalSourceBinding
#check @KIP126.Literature.Route.ClassicalSourceData
#check @KIP126.Literature.Route.ClassicalSourceResults
#check @KIP126.Literature.Route.DifferentialRigidity
#check @KIP126.Literature.Route.E2WeightVanishing
#check @KIP126.Literature.Route.EInftyLabelAgreement
#check @KIP126.Literature.Route.FiniteLiftCriterion
#check @KIP126.Literature.Route.MayContext
#check @KIP126.Literature.Route.MayContext.Boundary
#check @KIP126.Literature.Route.MayContext.SignedBoundary
#check @KIP126.Literature.Route.MayPushpullData
#check @KIP126.Literature.Route.MossSourceInput
#check @KIP126.Literature.Route.MossTowerApplicability
#check @KIP126.Literature.Route.NuCofiberApplicability
#check @KIP126.Literature.Route.NuCofiberLiftBinding
#check @KIP126.Literature.Route.NuCofiberSourceResults
#check @KIP126.Literature.Route.OrderTwo62
#check @KIP126.Literature.Route.PermanentLiftCriterion
#check @KIP126.Literature.Route.QuotientAlgebraBinding
#check @KIP126.Literature.Route.QuotientAlgebras
#check @KIP126.Literature.Route.RealizationDetection
#check @KIP126.Literature.Route.SyntheticSourceInputs
#check @KIP126.Literature.Route.Theta5Existence
#check @KIP126.Literature.Route.Theta5FiltrationGap
#check @KIP126.Literature.Route.ThetaBMossInput
#check @KIP126.Literature.Route.TmfBinding
#check @KIP126.Literature.Route.TmfLabels.Standard
#check @KIP126.Literature.Route.TmfSourceData
#check @KIP126.Literature.Route.TmfSourceData.high125
#check @KIP126.Literature.Route.TmfSourceData.unit
#check @KIP126.Literature.Route.TmfSourceResults
#check @KIP126.Literature.Route.TodaApplication
#check @KIP126.Literature.Route.TodaInputs
#check @KIP126.Literature.Route.TodaSourceResults
#check @KIP126.Literature.Route.TripleToda
#check @KIP126.Literature.Route.classicalInputsOfSource
#check @KIP126.Literature.Route.sourceNormalizedTriangle
#check @KIP126.Literature.Route.syntheticTwo
#check @KIP126.Main.Solution.Computation.high125_nonzero_survival_of_computation
#check @KIP126.Main.Solution.Computation.tmf_inputs_of_computation
#check @KIP126.Solution.Near126.Thm7_3BJMBX.any_choice_criterion
#check @KIP126.StableHomotopy.Toda.Relation
#check @KIP126.StableHomotopy.Toda.absorb_first
#check @KIP126.StableHomotopy.Toda.absorb_last
#check @KIP126.StableHomotopy.Toda.juggling
#check @KIP126.StableHomotopy.Toda.map
#check @KIP126.StableHomotopy.Toda.postcompose
#check @KIP126.StableHomotopy.Toda.precompose
#check @KIP126.StableHomotopy.Toda.relation_iff_indeterminacy
#check @KIP126.StableHomotopy.Toda.shuffle_iff
#check @KIP126.StableHomotopy.Toda.tensor_left
#check @KIP126.StableHomotopy.Toda.tensor_right
#check @KIP126.Synthetic.Context.IsLambdaComplete
#check @KIP126.Synthetic.HomologyShortExact
#check @KIP126.Synthetic.LambdaAdicCompletenessInterface
#check @KIP126.Synthetic.NuCofiberCriterion
#check @KIP126.Synthetic.SpectralSequence.SyntheticEInftyMapCompatibility
#check @KIP126.Synthetic.SpectralSequence.SyntheticEInftyPresentation
#check @KIP126.Synthetic.SpectralSequence.TowerConvergence
#check @KIP126.Synthetic.SpectralSequence.towerFiltration
#check @KIP126.Synthetic.SyntheticInterface
#check @KIP126.Synthetic.SyntheticTriangleLift
#check @KIP126.Synthetic.SyntheticTriangleLiftComparison
#print axioms KIP126.StableHomotopy.Toda.relation_iff_indeterminacy
#print axioms KIP126.StableHomotopy.Toda.juggling
#print axioms KIP126.StableHomotopy.Toda.shuffle_iff
#print axioms KIP126.Computation.Route.sphere_facts
#print axioms KIP126.Computation.Route.high125_detected_choice_unique
#print axioms KIP126.LinE2.h1_mul_h2_eq_zero
#print axioms KIP126.LinE2.csv_relation_zero
#eval KIP126.LinE2.RawData.relations.contains "1,1,2,1"
#eval KIP126.LinE2.RawData.relations.contains "18,1,85,1"
#eval KIP126.LinE2.RawData.relations.contains "18,1,84,1"
#eval KIP126.LinE2.RawData.relations.contains "2,1,407,1"
#eval KIP126.LinE2.RawData.relations.contains "0,1,3,1,335,1;0,2,425,1"
