import KIP126.Main.Solution.h6_sq_permanent
import KIP126.Interface.Solution.Challenge2
#check @KIP126.Literature.Route.DifferentialRigidity
#check @KIP126.Literature.Route.E2WeightVanishing
#check @KIP126.Kervaire.Route.ModelData
#check @KIP126.Literature.Route.SyntheticSourceInputs
#check @KIP126.Synthetic.SpectralSequence.SyntheticEInftyPresentation
#check @KIP126.Synthetic.SpectralSequence.SyntheticEInftyMapCompatibility
#check @KIP126.Literature.Route.EInftyLabelAgreement
#check @KIP126.Literature.Route.FiniteLiftCriterion
#check @KIP126.Literature.Route.BocksteinDifferential
#check @KIP126.Literature.Route.PermanentLiftCriterion
#check @KIP126.Literature.Route.RealizationDetection
#check @KIP126.Literature.Route.BHSRealizationSourceResults
#check @KIP126.Literature.Route.ClassicalSourceResults
#check @KIP126.Literature.Route.Theta5Existence
#check @KIP126.Literature.Route.OrderTwo62
#check @KIP126.Literature.Route.Theta5FiltrationGap
#check @KIP126.Literature.Route.MayContext
#check @KIP126.Literature.Route.MayPushpullData
#check @KIP126.Literature.Route.MayContext.SignedBoundary
#check @KIP126.Literature.Route.MayContext.Boundary
#check @KIP126.Literature.Route.BXDistinguishedInput
#check @KIP126.Kervaire.BJMSourceTotalBoundaryIdentity
#check @KIP126.Kervaire.BJMUntruncatedCriterion
#check @KIP126.Synthetic.SyntheticInterface
#check @KIP126.Synthetic.NuCofiberCriterion
#check @KIP126.Synthetic.SyntheticTriangleLift
#check @KIP126.Literature.Route.NuCofiberApplicability
#check @KIP126.Literature.Route.NuCofiberSourceResults
#check @KIP126.Literature.Route.NuCofiberLiftBinding
#check @KIP126.Computation.Route.Derived.CnuDifferential
#check @KIP126.Computation.Route.cnu_d3
#check @KIP126.Computation.Route.BottomCorrect
#check @KIP126.Computation.Route.TopCorrect
#check @KIP126.Computation.Route.Derived.CnuTargetThrough5
#check @KIP126.Computation.Route.cnu_target_through5
#check @KIP126.Computation.Route.BasisCorrect
#check @KIP126.Computation.Route.Statement
#check @KIP126.Kervaire.Route.ComparisonCompatible
#check @KIP126.Literature.Route.BHSCompletionApplicability
#check @KIP126.Literature.Route.BHSCompletionComparison
#check @KIP126.Synthetic.SpectralSequence.TowerConvergence
#check @KIP126.Synthetic.SpectralSequence.towerFiltration
#check @KIP126.Synthetic.LambdaAdicCompletenessInterface
#check @KIP126.Synthetic.Context.IsLambdaComplete
#check @KIP126.Literature.Route.BHSPermanentLiftAt
#check @KIP126.Literature.Route.BHSRealizationDetectionAt
#check @KIP126.Literature.Route.ClassicalSourceData
#check @KIP126.Literature.Route.ClassicalSourceBinding
#check @KIP126.Literature.Route.classicalInputsOfSource
#print axioms KIP126.Computation.Route.sphere_facts
#print axioms KIP126.Computation.Route.cnu_d3
#print axioms KIP126.Computation.Route.cnu_target_through5
